### PR TITLE
feat: Added native_tool_call model option which enables tool use through API calls

### PR DESCRIPTION
**Pull request by smonux**
A new parameter model called "native_tool_call" is added.

If false (the default), the behaviour when there are tools enabled doesn't change: a prompt is built which asks the model to generate a function call compatible with the offered tools. If it's valid the ouput is the added to the context.

If true, the native mechanism that the API has is used instead. That means that the responses have to be inspected to detect if a tool_call has to be handled and act accordingly. This allows more complex behaviours where the model can try several strategies and call tools knowing the output of others.

Ollama tool calling API only supports non streaming requests. In case both streaming and native_tool call are present, native tool calling is silently ignored.
Testing

The feature has been tested through the ui and using a script which calls these endpoints using
/api/chat/completions
/ollama/api/chat

With the OpenAI API, these models have been tested, with varying success

    OK
    gpt-4o-mini
    qwen/qwen-2.5-72b-instruct (OpenRouter endpoint)
    anthropic/claude-3-haiku (OpenRouter endpoint)
    deepseek/deepseek-chat (OpenRouter endpoint)
    google/gemini-pro (OpenRouter endpoint)
    Partial support
    cohere/command-r-plus (OpenRouter endpoint)

-Fails
meta-llama/llama-3.1-70b-instruct (OpenRouter endpoint)

With the Ollama API, only llama3.2:3b has been tested.

These are prompts used with two functions provided:

    get_current_time
    get_sensor_data with a single argument which just returns the sensorid multiplied by two.

```
("what is the first letter of the latin alphabet",  "no tools needed"),
("what is the date of today (use the get_current_time function)", " 1 tool no args"),
("what is the value of sensor 1", " 1 tool with args"),
("what are the value of sensors 1 and 4", " 2 tools (the may be run in parallel if the API supports it )"),
("if the value of sensors 1 is less that 5 m/s report the value of sensor 4. Otherwise report sensor 3", " 2 tools (in s
equence if the model does it )"),


("choose a integer between 1 an 10 write it here. If it's bigger that 5 report sensor 4. Otherwise report sensor 1", " tool call after having generated some text"),
("what is the value of sensor 'HELLO' ",  "tool call raises an exception")
```
The full output is attached to the PR.[output.txt](https://github.com/user-attachments/files/17806506/output.txt)

- [X] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [X] **Description:** Provide a concise description of the changes made in this pull request.
- [X] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [-] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
Will update docs if gets accepted.
- [X] **Dependencies:** Are there any new dependencies? NO
- [X] **Testing:** Have you written and run sufficient tests for validating the changes?
- [X] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [X ] **Prefix:** To cleary categorize this pull request, prefix the pull request title, using one of the following:

# Changelog Entry

### Description
A new parameter model called "native_tool_call" is added. If set to true, the tool calls are performed using the API and instead of the prompt based approach which is the default.

### CODE REVIEW

**Comment by michaelpoluektov** [comment]
Testing this now. Later versions of ollama do support streaming requests, but I'm not sure if we have a way to ensure it's up to date.

**Comment by michaelpoluektov** [comment]
First of all, I really appreciate your work. I've spent a lot of time working towards this but didn't quite have the time to finish.

I've opened a PR to your branch. I've tested this with default `gpt-4o-mini`, here are a few observations:
- If a tool's arguments are incompatible with OpenAI for whatever reason, we get a backend exception. Perhaps we could handle this more gracefully? I've fixed the schema generation but the tool has to be re-loaded before the fix is applied.
- The rendering is funky if tool calls happen in between the response, example prompt: `write me a poem about pens, then call the weather tool for Bristol and tell me what the weather is`. Might be due to some token reaching the client first.
Screenshot 2024-11-21 at 18 40 48
- Nitpick: code quality is still not perfect, it generates a lot of Pyright errors and has quite a few heavily nested/copy-pasted sections.
Screenshot 2024-11-21 at 18 39 12
- Citations are inconsistent
- Ollama streaming should be supported ideally, but that can be done later.

Certainly needs more testing/ironing stuff out but overall really good progress!

**Comment by smonux** [comment]
Thank you @michaelpoluektov ! I have switched the PR to WIP until you it gets polished a bit.

So, with regard to your suggestions, I will try to address them one by one.

## Ollama and streaming support

Ollama does support streaming, but not for function calling, or at least it didn't when I tested it. This is what I got when I tried (:

```
 {"model":"llama3.2","created_at":"2024-10-24T14:22:20.132691078Z","message":{"role":"assistant","content":"{\""},"done":false}
 {"model":"llama3.2","created_at":"2024-10-24T14:22:20.33554706Z","message":{"role":"assistant","content":"name"},"done":false} 
 {"model":"llama3.2","created_at":"2024-10-24T14:22:20.502733708Z","message":{"role":"assistant","content":"\":\""},"done":false} 
 {"model":"llama3.2","created_at":"2024-10-24T14:22:20.656243171Z","message":{"role":"assistant","content":"get"},"done":false} 
 {"model":"llama3.2","created_at":"2024-10-24T14:22:20.822777839Z","message":{"role":"assistant","content":"_current"},"done":false} 
 {"model":"llama3.2","created_at":"2024-10-24T14:22:20.964589544Z","message":{"role":"assistant","content":"_time"},"done":false} 
 {"model":"llama3.2","created_at":"2024-10-24T14:22:21.136555505Z","message":{"role":"assistant","content":"\",\""},"done":false} 
 {"model":"llama3.2","created_at":"2024-10-24T14:22:21.287671297Z","message":{"role":"assistant","content":"parameters"},"done":false}
 {"model":"llama3.2","created_at":"2024-10-24T14:22:21.431889334Z","message":{"role":"assistant","content":"\":"},"done":false} 
 {"model":"llama3.2","created_at":"2024-10-24T14:22:21.586345438Z","message":{"role":"assistant","content":"{"},"done":false} 
 {"model":"llama3.2","created_at":"2024-10-24T14:22:21.736116317Z","message":{"role":"assistant","content":"}}"},"done":false} 
 {"model":"llama3.2","created_at":"2024-10-24T14:22:21.905902646Z","message":{"role":"assistant","content":""},"done_reason":"stop","done":true,"total_duration":23090998025,"load_duration":6420601624,"prompt_eval_count":156,"prompt_eval_duration":14892508000,"eval_count":12,"eval_duration":1765368000} 
```

I have confirmed it in the ollama docs 
https://github.com/ollama/ollama/blob/723f285813f504375f0e6be6c76edfbaaabd961f/docs/api.md?plain=1#L123

*- `tools`: tools for the model to use if supported. Requires `stream` to be set to `false`*

So, apparently can't be done by now :-(

## Tools arguments schema/Backend exception when arguments are incompatible with OpenAI 

I assume this is where the bulk of your changes go, right? If you have coded all this in so little time I'm really impressed.

I haven't realized it was happening. I have only tried with string arguments and, tbh, I doubt the prompt based approach worked perfectly either. But I will add some functions with a bit more complex signatures and will see how models handle it.

BTW, I test the back end with a script instead of the GUI. I will attach them in case anyone think they are useful.

With regards with the exception, I think letting it go through isn't that bad. I don't know what else to do. The prompt based handling code just captures and reraises when the content isn't valid json. I honestly don't see the point of catching for reraising, but I may be wrong.

## Funky rendering

Will try to replicate. I haven't detected it, but I have used the UI very little, I have mostly tested it from the script.

## Code Quality

It's messy, I know. I will look into it, although I can't make a lot of sense of those pyright warnings. 

## Citations are inconsistent

Hadn't observed it, I will try to replicate.

Again, thanks a lot. Merging your changes now. I hope to get some time this weekend to look into them

**Comment by michaelpoluektov** [comment]
Interesting, seems like the issue was re-opened... https://github.com/ollama/ollama/issues/5796

Maybe ignore Ollama streaming for now then. I know that it's worked before via some langchain magic but since we don't want to offload anything to langchain it might be best to wait until the API is finalised so we don't need to change it again

**Comment by smonux** [comment]
Yeah, apparently the feature is still on the works.

Just tested your changes a bit... the if the docstring has quotes the llm call fails. Will try to debug it later, now I'm inside another rabbit hole.

**Comment by michaelpoluektov** [comment]
I'm looking into it in more detail now: there seem to be a lot of _really_ confusing parts in the backend (which is why I had originally given up implementing this). Most of it is not you though, but I'm going to dump this here in case it's helpful or in case someone can provide more clarity/an opinion as to how this is best resolved.

Doing this in a good a stable way will require a lot more refactoring, here's why:
1. Chat completion requests are sent to `/chat/completions/`
2. They are captured by `ChatCompletionMiddleware`, which in turn call `call_next` (the next chat completion: can be OAI or Ollama) then wraps it in `handle_streaming_response` or `handle_non_streaming_response`
3. Here's the confusing part: both `handle_streaming_response` and `handle_non_streaming_response` actually expect a `StreamingResponse`, here's the relevant code snippet from `handle_non_streaming_response`:

```python
async def handle_nonstreaming_response(
    request: Request,
    response: StreamingResponse,
    tools: dict,
    user: UserModel,
    models,
) -> JSONResponse:
    # It only should be one response since we are in the non streaming scenario
    content = ""
    async for data in response.body_iterator: # <---- only streaming response will have a body_iterator
        content += data.decode()
```

And both of those call `generate_chat_completion` directly, despite there being other functions that are captured by the middleware.

To make things even more annoying to debug, the type definition of `generate_chat_completion` is `Callable[..., StreamingResponse | dict]` and whether it's `StreamingResponse` or `dict` depends on the contents of the body.

**Comment by michaelpoluektov** [comment]
Once a request hits an endpoint, we need to check whether or not it expects a streaming or non streaming response, then recursion should be constrained to whichever type of response we're handling, so instead of:

`generate_chat_completion -> is_streaming ? stream_wrapper(generate_chat_completion) : some_other_wrapper(generate_chat_completion)`

It should be:

`generate_stream_chat_completion -> stream_wrapper(generate_streaming_chat_completion)`
`generate_nonstream_chat_completion -> some_other_wrapper(generate_nonstream_chat_completion)`
`generate_chat_completion -> is_streaming ? generate_stream_chat_completion : generate_nonstream_chat_completion`

**Comment by michaelpoluektov** [comment]
Also, am I correct in saying that `bypass_filter` will default to True if the role is _not_ `user`? Now that there are roles other than `user` and `admin` wouldn't that mean that anyone with a non-default role will have access to any model if they call the endpoint directly?

**Comment by michaelpoluektov** [comment]
Here's my to do list for this, which I'll get to hopefully sometime this week:
- Factor out parts of `ChatCompletionMiddleware` into it's respective endpoints: any special Ollama/OpenAI logic should be part of the Ollama/OpenAI endpoints respectively, the middleware should only check that the user has access to the model and call filters. Handling native tool calls shouldn't be done there.
- Refactor `generate_chat_completions` into 2 functions: 1 for streaming and one for non streaming. Both of those functions should be recursive if "native_tool_calls" is set.
- Refactor each of those new functions into 4 functions for ollama, openai, arena and functions. The arena function should call either one of the 3 others. For now, only implement "native_tool_calls" in openai, worry about ollama later. Native tool calls don't need to be implemented for functions since those have access to the `__tools__` parameter and will probably want to handle them separately.

That way each function will know exactly what to expect as an input/output schema so we can validate it and not worry about weird edge cases.

**Comment by smonux** [comment]
Wow, lots of interesting stuff. You are way more ambitious that I was. Given that native_tool_call was an optional feature, and I wasn't very confident about my abilities, I intentionally tried to avoid to touch the existing "critical path" as much I could. I think is such a important feature, that I thought was preferrable to make a half-assed implementation than not having anything at all.

Your approach is much better, but also has some risks. The pace of change of main.py is pretty high (for example, the docstring parsing you did has already changed). I would like to hear @tjbck opinion on the PR and the approach because it has a good chance of getting out of hand-impossible to synchronize.

Now, with regards of the general approach. If I understand correctly how fastapi works, would a layered approach make sense?. I mean:
 - the first layer does some initialization (for example, stores the models, user and other reusable data in the request.state)
 - next layer authorization
 - next layer Functions
 - next layer RAG
 - next layer Tools (whatever the approach)
 -...
  - last layer calls OpenAI or Ollama API (which, btw, could be further simplified because Ollama has OpenAI compatible API).

Idk, what do you think?

**Comment by michaelpoluektov** [comment]
> Ollama has an OpenAI compatible API

I believe their OpenAI API isn't as powerful as the native one because there are some options it doesn't accept

> layer layer calls OpenAI/Ollama API

The thing is we need to also calls those in the layers before

There's a lot of things that can be simplified though, for example checking whether or not a user has access to a model is just copy pasted 4 times in every possible function right now.

All of this is probably best done as a series of smaller PRs

**Comment by michaelpoluektov** [comment]
I think if we keep on trying to avoid the "critical path" it will just keep on getting worse. We might break things in the process but if it becomes maintainable again I think it's a worthwhile thing long term. I guess that's for Tim to decide though. If we refactor this now the project will likely be much more stable a few versions down the line when even more functionality gets added.

**Comment by lowlyocean** [comment]
Is there an estimate of the time it'd take to do either approach? This feature seems critical to have for those running local models, so there probably should be a balance between doing things the "right way" (making edits to critical path) and getting this to see the light of day in timely fashion.

**Comment by RodolfoCastanheira** [comment]
+1 for merging this initial implementation of native tool call and making other PR for the refactoring. Seems to me (one of?) the greatest missing feature of open-webui right now

**Comment by michaelpoluektov** [comment]
I have implemented a function that does exactly that, available here: https://openwebui.com/f/michaelpoluektov/react_agent

It covers OpenAI and Ollama models, sends citation events and optionally supports langfuse.

> +1 for merging this initial implementation of native tool call and making other PR for the refactoring. Seems to me (one of?) the greatest missing feature of open-webui right now

This PR implements functionality that's already been implemented in a function, but in an (arguably) less reliable way. If this gets merged in it's current state, it will be even harder to refactor. This PR handles additional responses in the middleware, with a function that recursively calls another function, which is itself bound to that aforementioned middleware. This creates a really messy dependency loop where changing either 1 of the 3 components can affect all sorts of things in unpredictable ways.

> Is there an estimate of the time it'd take to do either approach? This feature seems critical to have for those running local models, so there probably should be a balance between doing things the "right way" (making edits to critical path) and getting this to see the light of day in timely fashion.

As mentioned above, if you need this _now_ you can use the custom function. As for a timeline: I can't personally commit to anything. I do this on the weekends (this coming weekend excluded). I don't believe this is Tim's priority right now.

If anyone else is willing to take this on I'm always willing to review/discuss but I think this has to be done properly.

**Comment by lowlyocean** [comment]
> have implemented a function that does exactly that, available here: https://openwebui.com/f/michaelpoluektov/react_agent

Is there documentation on how to use this? It seems to do more than just native tool calling.

Is there a benefit from Open WebUI having used non-native tool calling? Was it a matter of having been implemented before native tool calling was available?

**Comment by michaelpoluektov** [comment]
The docs aren't complete but here they are:

https://docs.openwebui.com/features/plugin/functions/

Functions are in admin settings -> functions, press "create new" and copy paste the code.

> It seems to do more than just native tool calling.

It does native tool calling and monitoring with langfuse if you provide langfuse credentials in the valves. Otherwise it's literally just native tool calling. "ReAct" means that once the model calls a tool it gets to respond again until it finishes without tool calls.

**Comment by michaelpoluektov** [comment]
Speaking of, another limitation with both the above function and this implementation is that tool messages aren't saved in the conversation. Meaning that the sequence of `tool` and `assistant` messages between 2 `human` messages becomes a single `assistant` message and the outputs of `tool` messages are forgotten.

**Comment by lowlyocean** [comment]
I added your Function and Enabled it. I configured the Valves for it to call Ollama using OpenAI interface. It created a new Model (a duplicate of model I specified, with a new prefix of ReAct/). I enabled tools for that new ReAact/ model, but they don't seem to ge tcalled. If I check the logs, the old "generic" non-native prompt seems to still be being sent.

**Comment by michaelpoluektov** [comment]
When you say "they don't seem to be called" I'm assuming the prompt called for tool calls? I don't really have "docs" but I have a GH repo: https://github.com/michaelpoluektov/OWUI-ReAct, could you open an issue there and post your logs?

The prompt doesn't get changed, it just adds the tools with each requests, the provider choses how to deal with them. It works for OpenAI and (regular) Ollama for me.

**Comment by lowlyocean** [comment]
If I understand, you mean that your Function will still just pass-through the _tools_function_calling_prompt_ below to the Ollama instance? If that's the case - I don't think there's an issue to report - it's just not the desired behavior.

```
'Available Tools: [{tool1 details},{tool2 details},...]\nReturn an empty string if no tools match the query. If a function tool matches, construct and return a JSON object in the format {"name": "functionName", "parameters": {"requiredFunctionParamKey": "requiredFunctionParamValue"}} using the appropriate tool and its parameters. Only return the object and limit the response to the JSON object without additional text.'
```

**Comment by smonux** [comment]
Hello!

I'm in mobile now, and can't review it properly, but I find strange that uses the API tool calling mechanism given that ollama still don't support it in streaming mode. How can it be possible? 

I'm not saying it's not useful, and the code looks really good, but I find it surprising. It's crucial for me use case that the llm can see its mistakes and other tools output.  (I can't test if it's the case)

...

Is this implementation?

https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/agents/react/agent.py

Sorry, I will write a more compete post when I get time to review properly,, probably tomorrow.

**Comment by michaelpoluektov** [comment]
> If I understand, you mean that your Function will still just pass-through the _tools_function_calling_prompt_ below to the Ollama instance? If that's the case - I don't think there's an issue to report - it's just not the desired behavior.
> 
> ```
> 'Available Tools: [{tool1 details},{tool2 details},...]\nReturn an empty string if no tools match the query. If a function tool matches, construct and return a JSON object in the format {"name": "functionName", "parameters": {"requiredFunctionParamKey": "requiredFunctionParamValue"}} using the appropriate tool and its parameters. Only return the object and limit the response to the JSON object without additional text.'
> ```

All custom prompts are ignored other than the assistant prompt (and potentially title generation). For every chat message, only 2 calls are actually being passed through: the actual conversation and the title generation prompt.

When you send a message it passes your tool specs with the request, that's it.

**Comment by michaelpoluektov** [comment]
> Hello!
> 
> I'm in mobile now, and can't review it properly, but I find strange that uses the API tool calling mechanism given that ollama still don't support it in streaming mode. How can it be possible?
> 
> I'm not saying it's not useful, and the code looks really good, but I find it surprising. It's crucial for me use case that the llm can see its mistakes and other tools output. (I can't test if it's the case)
> 
> ...
> 
> Is this implementation?
> 
> https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/agents/react/agent.py
> 
> Sorry, I will write a more compete post when I get time to review properly,, probably tomorrow.

Yeah this is why I was saying Ollama _should_ work. It is the case that the LLM can see it's mistakes and correct it's output, but as I've mentioned, tool calls are forgotten after any `human` message, which is not desired. I could probably hack together something to save them in the assistant prompt though but that'd be a massive ugly hack.

**Comment by lowlyocean** [comment]
Your function needs documentation or at least some example video, because it's not clear how to use it properly.

> You shouldn't need a custom tool calling prompt
I am sure this is true when you are using the Function properly, but as of now I'm still seeing the Open WebUI "custom prompt" for tool use being sent to the model

**Comment by michaelpoluektov** [comment]
> Your function needs documentation or at least some example video, because it's not clear how to use it properly.
> 
> > You shouldn't need a custom tool calling prompt
> 
> I am sure this is true when you are using the Function properly, but as of now I'm still seeing the Open WebUI "custom prompt" for tool use being sent to the model

Weird, that's not supposed to happen. Will later: feel free to open an issue. There should be a condition that says something along the lines of `if __task__ == "tool_use": return`

**Comment by tjbck** [comment]
@michaelpoluektov I'm not going to guarantee the refac PRs will be directly merged to our repo. I also definitely plan on refactoring a whole bunch as well. With that being said, I'd still highly encourage you to proceed with the refactored implementation of chat completion path, and I'll incorporate/cherry pick some the changes.

**Comment by RodolfoCastanheira** [comment]
@michaelpoluektov I had the same experience of @lowlyocean using your function:

Screenshot 2024-11-29 at 18-33-17 Chat Completions - OpenAI API


But not always:

Screenshot 2024-11-29 at 18-33-25 Chat Completions - OpenAI API

I got the impression that, maybe, open-webui is calling the task model (for it to decide to use a tool call or not) before sending the message to the pipeline, but I didn't read the code.

**Comment by RodolfoCastanheira** [comment]
> @michaelpoluektov I'm not going to guarantee the refac PRs will be directly merged to our repo. I also definitely plan on refactoring a whole bunch as well. With that being said, I'd still highly encourage you to proceed with the refactored implementation of chat completion path, and I'll incorporate/cherry pick some of the changes.
> 
> For everyone's information: The current implementation is structured the way it is for very deliberate reasons, reflecting specific technical and architectural considerations that may not be immediately apparent. These decisions were made to address real-world constraints and edge cases that come with the complexity of the system. I designed it with these factors in mind, and I fully understand both the reasoning behind its structure and the downstream consequences of changing it. If someone describes the implementation as "unmaintainable," it’s likely because they don’t fully understand the context, trade-offs, or problem space it is designed to address. Of course, I don’t expect anyone—especially if you're not the author—to necessarily find everything intuitive or to fully agree with all decisions.
> 
> Past experience—including lessons from prior contributions—has repeatedly shown that even seemingly minor modifications can result in unforeseen regressions or failures in unexpected edge cases, often caused by a lack of visibility into the system’s intricacies. For this reason, I will only consider atomic, highly focused PRs for direct merging, as they are more straightforward to evaluate. That said, I am open to reviewing larger proposals and may judiciously incorporate portions that are demonstrably valuable and compatible with the current architecture. Ultimately, everything is the way it is for a reason, and changes will only be adopted when they preserve the integrity, stability, and intent of the codebase.

Ok, got it, seems very reasonable. In light of this approach to prefer more focused PRs, what do you think of this PR here?

**Comment by smonux** [comment]
Ok now I'm on a keyboard, I can make my points properly. The thread has gone wild in a couple hours!

1: The function

I haven't tried it but I'm pretty sure it can't be functionally equivalent. The lang chain code I linked before shows that it's a prompt based implementation and not an API based one (correct me if I'm wrong).

Still, it solves most of the problems:  it's llm agnostic (any llm can use it even if it doesn't support tools), it allows for "reentrancy" and more importantly... it shows that the problem can be solved at that level!! (A completely functionally equivalent function which uses the tools API could be made).

But I also think having the option of using the API mechanism, the one the llm's are specifically trained for (with specific tokens to support it), has its place, at least as an optional setting.

Inside openwebui preferably (if it's possible), but as a pipe if there is no other choice.

BTW, I'm basing my opinion in this article: 

https://medium.com/@rushing_andrei/function-calling-with-open-source-llms-594aa5b3a304

2 The PR

It's obvious that the Michael goals and mine ones are different even if they seemed closer at first glance. I'm aware of my initial PR limitations, but it's also true that I tried those limitations didn't affect the main path, while he's looking for a bigger refactorization.

I think it's better to leave this PR for the original intent, and include the refactoring changes in another one. I will try  to test it a bit more and I will submit it when I think it's ready (hopefully soon) 

I may also roll back Michael's contributions if I don't feel confortable with them (although I think they are ok).

3 The outcomes

At the end, it's @tjbck  the one who has the knowledge and the capacity to make the call. He can: 

- accept the PR
- ask for changes (which I will try to implement)
- reject it. I will then use my branch for my own for a while and will try to use Michael's function or a close implementation for "scratching my itch" in the long term.

Any of them will be fine.

Thanks everyone for showing up here!

**Comment by tjbck** [comment]
Agreed, my intention was to get to this PR and revise when I have the capacity. I'll definitely get to this when I have more bandwidth!

**Comment by smonux** [comment]
Changes to the PR
- Fixed bug in which part of the content generated by the llm wasn't resent to the endpoint in subsequent calls. This probably was related to the oddly formatted content and other issues.
- Eliminated duplicated code in the tool_calling part
- Fixed subtle bugs, only present with some models
- Refactored and Improved the code quality a bit (I hope), at the very least pyright doesn't scream as it did before.
- Fixed bug in user settings (the UI wasnt showing modifications change)

Some comments:
 - Non streaming mode doesn't support citations. As far as I have seen this also happens in the current implementation.
 - Also in nonstreaming mode, if the tool sends a __event_emitter__ message, it gets displayed but that content is deleted when the final data is sent 
 - Weird behaviour with string/str types. Sometimes OpenAI seems to only accept "string", but others seem accept "str". Some models accept both while others only accept "str". I have let "str" for the moment but the hack is present as a comment in tools.py until I understand what's going on.
 - skip_files now only makes sense (IMO) if all the tools are file handlers. We can't know in advance which are being to be called. 
 - I have left the tools.py refactoring commits, but that part is orthogonal to the rest of the PR.

I have applied the changes over the v0.4.7-smonux branch in case anyone wants to check them.
https://github.com/smonux/open-webui/tree/v0.4.7-smonux

In the meantime Ollama added streaming support! I'm going to check how hard it can be to support it, although it's a bit painful without GPU.

**Comment by AliveDedSec** [comment]
I want to thank you for the great work you've done on this PR! This is a really important improvement, and I truly appreciate all the effort you've put into creating a more flexible tool-calling system. I can see how much effort you've invested in solving problems, and how you're pushing the project to the next level!

That said, I understand the task isn't fully completed yet, and there are a few things that might need further work (like considering streaming support or fixing some minor bugs). I’d like to kindly ask you to continue the work and bring this functionality to completion. It’s crucial that this improvement is fully realized, and I’m confident your contribution will make the system much more powerful and user-friendly for everyone.

Thank you so much for your hard work and for continuing to move the project forward! I’m looking forward to seeing the final version soon.

**Comment by smonux** [comment]
Ok, I'm calling this as ready for review. Some comments:

The good news is that now ollama with "native_tool_call" and "streaming" works.

The bad is that ollama's support for this is basically... stop streaming and send all output at once instead. (see https://github.com/ollama/ollama/issues/5796)

They have the intention of improving this at some point in the future (https://github.com/ollama/ollama/issues/7886) and I'm somewhat confident that this implementation should work with small changes when that happens.

I have tested it in these OpenAI compatible models:
    "openai/gpt-4o-mini",
    "anthropic/claude-3-haiku",
    "deepseek/deepseek-chat",
    "google/gemini-pro", 
    "cohere/command-r"

Command-R which I listed before as "partial support" works fine, it's just a bit picky about what it does accept.

There were more than used to work (Qwen), but now return a "No endpoints found that support tool use". There are other that don't fail, but doesn't use any (the new Amazon Nova's for example).

But for those who do, the difference is day and night, IMO.

I hope @tjbck  finds some time to review this. Open to make any improvement or respond to any question. Thanks to @michaelpoluektov for his input and help.

**Comment by smonux** [comment]
Hello @tjbck,

I have seen this PR has now conflicts due recent changes. I can try to look into solve them, but I'd like to know what's your opinion on it, if it has any chance of getting it merged.

Thank you.

**Comment by lowlyocean** [comment]
Are PRs like this gated by a single approver?

**Comment by lowlyocean** [comment]
@smonux @tjbck Any chance of this getting re-opened and reviewed? Or has some other approach for native tool use been added?

**Comment by tjbck** [comment]
Will take a look when I have the capacity. Appreciate your patience.

**Comment by smonux** [comment]
> Any chance of this getting re-opened and reviewed? Or has some other approach for native tool use been added?

@lowlyocean,  I closed the PR because after the 0.5.x refac it was clear it required considerable rewriting to make it work and the PR was too messy already. If there is some validation about the approach/code of this PR I would try to adapt it again.

Given I want to use the functionality for my use cases I'm working in a Function-Pipe implementation I can use with 0.5.  But, it will only support OpenAI, since the "tools" parameter isn't kept in  backend ollama API calls (it uses the OpenWebUI internal functions instead of using the API url's directly, so there are limitations).

This is the current state if you are interested (warning, it's very hacky).

https://github.com/smonux/open-webui-docker-execution/blob/dev/nativecall_pipe.py

Best regards

**Comment by lowlyocean** [comment]
Thanks @smonux, I understand that 0.5.x made this PR stale and you need commitment from @tjbck about your approach here before you begin any attempt to rebase it.

FWIW, I think that we should avoid having someone install a Function, etc. to activate native tool calling. It's a feature I think anyone using Open-WebUI to connect to Ollama would expect "out of the box"

It would seem sensible that Open-WebUI detect if the model supports native tool calling - and if so, prefer to use that. Otherwise, fall back to the existing generic prompt-based approach.

**Comment by tjbck** [comment]
@lowlyocean like I mentioned, I'll get to it. Things just take time, I appreciate your patience.

**Comment by lowlyocean** [comment]
Can we at least re-open this issue to track? Thanks

**Comment by bdqfork** [comment]
Any update?

**Comment by tjbck** [comment]
I'll be allocating my capacity to get this feature merged for 0.5.8, testing wanted after it's merged to dev!

**Comment by lowlyocean** [comment]
I tested latest Dev (including [this change](https://github.com/open-webui/open-webui/commit/642a093d0274eb6e0c706e8eb4b04188573f7a95), but I see it's still doing the following pattern when I query "Tell me the date" after enabling the "today's date" tool:
```
1. Pass prompt as "[INST] Available Tools: [json] If one or more tools match the query, ... Query: ... History: ... USER: Tell me the date Query: Tell me the date [/INST]"
2. Pass prompt as "[INST] ### Task: Respond to the user query using the provided context, incorporating ... <context><source><source_context>Today's date is Sunday, February 02, 2025</source_context></source></context><user_query>Tell me the date</user_query>Tell me the date [/INST]"
3. The response comes back as exactly the source_context value: Today's date is Sunday, February 02, 2025
```

I think I am instead expecting something much simpler, i.e. similar to the [Get Weather example](https://platform.openai.com/docs/guides/function-calling?example=get-weather) on OpenAI's API docs:

1. Single prompt is passed, which has "tools" field populated with whatever tools are Enabled by user. It contains no template in the prompt, just the user's query alone

**Comment by tjbck** [comment]
@lowlyocean not merged to dev yet.

**Comment by tjbck** [comment]
Basic implementation has been merged to dev! Testing wanted here!

**Comment by ProjectMoon** [comment]
Does this work for both ollama and OpenAI tool APIs?

**Comment by smonux** [comment]
> Basic implementation has been merged to dev! Testing wanted here!
> 
It works very fluidly! Pretty impressed. I need time to test it properly, but at first glance looks great. Very honored of being mentioned in the commits, too! (thank you).

First impressions:

- bug: it doesn't work with streaming disabled .
- not sure if bug or intentional: event messages don't reach the content box, unlike regular tool calls. In fact, after closing inspection, the output appears for a second, but gets overwritten (just like it happens to my pipe, something I haven't been able to solve).
imagen
vs
imagen

- cosmetic/format: Tool output is included in further completions, which I think its a good choice because that context is beneficial (specially if "event messages" don't work). But the format is weird:

```
            "content": "\n<details type=\"tool_calls\" done=\"true\" content=\"[{&quot;index&quot;: 0, &quot;id&quot;: &quot;call_KitiBlxTfTikIiTSqCTWyuza&quot;, &quot;type&quot;: &quot;function&quot;, &quot;function&quot;: {&quot;name&quot;: &quot;get_sensor_data&quot;, &quot;arguments&quot;: &quot;{\\&quot;sensorid\\&quot;: \\&quot;4\\&quot;}&quot;}}, {&quot;index&quot;: 1, &quot;id&quot;: &quot;call_xnL2L9JnSMUn9hhTc8hOYt8M&quot;, &quot;type&quot;: &quot;function&quot;, &quot;function&quot;: {&quot;name&quot;: &quot;get_sensor_data&quot;, &quot;arguments&quot;: &quot;{\\&quot;sensorid\\&quot;: \\&quot;3\\&quot;}&quot;}}]\" results=\"[{&quot;tool_call_id&quot;: &quot;call_KitiBlxTfTikIiTSqCTWyuza&quot;, &quot;content&quot;: &quot;the value of sensorid 4: 8 m/s&quot;}, {&quot;tool_call_id&quot;: &quot;call_xnL2L9JnSMUn9hhTc8hOYt8M&quot;, &quot;content&quot;: &quot;the value of sensorid 3: 6 m/s&quot;}]\">\n<summary>Tool Executed</summary>\n\n> get_sensor_data: the value of sensorid 4: 8 m/s\n> get_sensor_data: the value of sensorid 3: 6 m/s\n</details>\nThe values of the sensors are as follows:\n- Sensor 4: 8 m/s\n- Sensor 3: 6 m/s\n",
```

I will continue testing it, these are just the first impressions...

**Comment by lowlyocean** [comment]
Not working here. I'm using Ollama model mistral-small:22b-instruct-2409-q2_K

Tried both OpenAI and Ollama connection. When I turn "Function Calling" to native, I get a totally empty chat response. When I look at the Ollama log file, I see this prompt still being used:

```
[AVAILABLE_TOOLS] [{\"type\":\"function\",\"function\":{\"name\":\"get_current_date\",\"description\":\"\\n        Get the current date.\\n        \",\"parameters\":{\"type\":\"object\",\"required\":[],\"properties\":{}}}}][/AVAILABLE_TOOLS] [INST] today’s date [/INST]
```

**Comment by smonux** [comment]
Another bug I have detected, the second call that's performed, the "tools"  tag doesn't appear, so the model only executes tools once (although it can use several of them in parallel in this only execution).

2nd Request:
```
{
    "messages": [
        {
            "content": "list the files in the cwd using R\n\n",
            "role": "user"
        },
        {
            "content": "I'll help you list the files in the current working directory using R. I'll use the `list.files()` function to accomplish this.",
            "role": "assistant",
            "tool_calls": [
                {
                    "function": {
                        "arguments": "{\"code\": \"# List files in the current working directory\\ncurrent_files <- list.files()\\nprint(current_files)\"}",
                        "name": "run_r_code"
                    },
                    "id": "toolu_01VsCUDjb9oyadN8vPx5ku91",
                    "index": 0,
                    "type": "function"
                }
            ]
        },
        {
            "content": "\n<interpreter_output>\n<description>\nThis is the output of the tool called \"DockerInterpreter (R only)\", appended here for\nreference in the response. Use it to answer the query of the user.\n</description>\n<executed_code>\n# List files in the current working directory\ncurrent_files <- list.files()\nprint(current_files)\n</executed_code>\n<output>\n[1] \"distribution_plots\"     \"distributions.xlsx\"     \"old\"                   \n[4] \"searxng\"                \"testfile.sqlite\"        \"wine_quality_vs_ph.png\"\n\n</output>\n</interpreter_output>\n",
            "role": "tool",
            "tool_call_id": "toolu_01VsCUDjb9oyadN8vPx5ku91"
        }
    ],
    "model": "anthropic/claude-3.5-haiku",
    "stream": true
}
```

Response
```
data: {"error":{"message":"Provider returned error","code":400,"metadata":{"raw":"{\\"type\\":\\"error\\",\\"error\\":{\\"type\\":\\"invalid_request_error\\",\\"message\\":\\"Requests which include `tool_use` or `tool_result` blocks must define tools.\\"}}","provider_name":"Anthropic"}},"user_id":"user_2jKp3JNlDXqIQgKa69AfEc5AZhq"}
```

Anthropic throws an error, while openai accepts the input (but it severily limits the ability of the model to work through a solution).

@tjbck  May be should take this conversation to Discussions?

**Pull request closed without merging**
