### PR TITLE
Chore: Allow installing with python 3.12

### PR DESCRIPTION
**Pull request by i0ntempest**
# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [x] **Testing:** Have you written and run sufficient tests for validating the changes?
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [x] **Prefix:** To cleary categorize this pull request, prefix the pull request title, using one of the following:
  - **BREAKING CHANGE**: Significant changes that may affect compatibility
  - **build**: Changes that affect the build system or external dependencies
  - **ci**: Changes to our continuous integration processes or workflows
  - **chore**: Refactor, cleanup, or other non-functional code changes
  - **docs**: Documentation update or addition
  - **feat**: Introduces a new feature or enhancement to the codebase
  - **fix**: Bug fix or error correction
  - **i18n**: Internationalization or localization changes
  - **perf**: Performance improvement
  - **refactor**: Code restructuring for better maintainability, readability, or scalability
  - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
  - **test**: Adding missing tests or correcting existing tests
  - **WIP**: Work in progress, a temporary label for incomplete or ongoing work

# Changelog Entry

### Description

- Allow installing with python 3.12

### CODE REVIEW

**Comment by i0ntempest** [comment]
See https://github.com/open-webui/open-webui/issues/7824#event-15652893916 and https://github.com/open-webui/open-webui/discussions/7836

**Comment by tjbck** [comment]
Have you tested everything is working as intended with 3.12?

**Comment by i0ntempest** [comment]
> Have you tested everything is working as intended with 3.12?

I have run open webui on my server with 3.12 for half a month, noticed no major issues. I have run multiple llms and have OpenAI API setup. For the issues I did found there’re existing issues.
If you have a specific list of stuff to test I’ll be happy to do that if I can.

**Comment by tjbck** [comment]
Sound good, Thanks!

**Comment by dnck** [comment]
Any plans to support current release, 3.13?

**Comment by tjbck** [comment]
@dnck Supporting 3.13 almost has nothing to do with us but rather our upstream dependencies, if someone can make sure using 3.13 works without no issue, feel free to open a PR!

**Comment by Classic298** [comment]
So if there are no more issues running OWUI on python 3.12, i think we can update the docs to mention that (as of right now it says 3.12 is more or less untested?)

_"Python 3.11 is the development environment. Python 3.12 seems to work but has not been thoroughly tested. Python 3.13 is entirely untested—use at your own risk."_

**Comment by astr0gator** [comment]
If I follow main page of repo, I don't have issues with 3.11:
>Open WebUI can be installed using pip, the Python package installer. Before proceeding, ensure you're using Python 3.11 to avoid compatibility issues

With 3.12 I have this error when trying to install:

```
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/opt/anaconda3/envs/py312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/anaconda3/envs/py312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/anaconda3/envs/py312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/opt/anaconda3/envs/py312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/anaconda3/envs/py312/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/private/var/folders/tp/0mxcwsvx5898txtggfbhhgnw0000gn/T/pip-build-env-fpld80bh/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/private/var/folders/tp/0mxcwsvx5898txtggfbhhgnw0000gn/T/pip-build-env-fpld80bh/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/private/var/folders/tp/0mxcwsvx5898txtggfbhhgnw0000gn/T/pip-build-env-fpld80bh/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
```

**Comment by wilson0x4d** [comment]
> /opt/anaconda3/envs/

You might also be interested in this SO Q&A which suggests the pip version being used is mismatched/outdated: https://stackoverflow.com/a/77364602/131420

separately, you might use Python Core + venv instead of relying on conda and see how it goes.

**Comment by astr0gator** [comment]
@wilson0x4d Thank you. I tried to follow that SO thread before, haven't resolved it. Still using conda system-wide, so for now just created venv for 3.11.

**Pull request merged**
