### PR TITLE
docs: add api workflow

### PR DESCRIPTION
**Pull request by anuraagdjain**
- helps in development to understand what's happening under the hood

### CODE REVIEW

**Comment by tjbck** [comment]
Nice addition to our documentation! I think the diagram has some tiny mistakes, so you might want to modify the diagram code to the following:

```
sequenceDiagram
participant User as User
participant Ollama_UI_Server as Ollama WebUI Server (Python)
participant Ollama_Server as Ollama Server

User->>+Ollama_UI_Server: Opens browser, visits localhost:8080
Ollama_UI_Server-->>-User: Returns welcome page from svelte build
Note over User, Ollama_UI_Server: WebUI is loaded to browser
User->>+Ollama_UI_Server: Sends API request to /api/v1
Ollama_UI_Server-->>-User: Returns API response data
Note over User, Ollama_UI_Server: WebUI receives and processes API response data
User->>+Ollama_UI_Server: Sends API request to /ollama/api
Ollama_UI_Server->>+Ollama_Server: Proxies request to ollama server
Ollama_Server-->>-Ollama_UI_Server: Responds with data
Ollama_UI_Server-->>-User: Returns API response data
Note over User, Ollama_UI_Server: User receives and processes API response data
```

Thanks as always!

**Comment by anuraagdjain** [comment]
> Nice addition to our documentation! I think the diagram has some tiny mistakes, so you might want to modify the diagram code to the following:
> 
> ```
> sequenceDiagram
> participant User as User
> participant Ollama_UI_Server as Ollama WebUI Server (Python)
> participant Ollama_Server as Ollama Server
> 
> User->>+Ollama_UI_Server: Opens browser, visits localhost:8080
> Ollama_UI_Server-->>-User: Returns welcome page from svelte build
> Note over User, Ollama_UI_Server: WebUI is loaded to browser
> User->>+Ollama_UI_Server: Sends API request to /api/v1
> Ollama_UI_Server-->>-User: Returns API response data
> Note over User, Ollama_UI_Server: WebUI receives and processes API response data
> User->>+Ollama_UI_Server: Sends API request to /ollama/api
> Ollama_UI_Server->>+Ollama_Server: Proxies request to ollama server
> Ollama_Server-->>-Ollama_UI_Server: Responds with data
> Ollama_UI_Server-->>-User: Returns API response data
> Note over User, Ollama_UI_Server: User receives and processes API response data
> ```
> 
> Thanks as always!

Good catch, fixed the issue.

**Comment by tjbck** [comment]
LGTM, Thanks!

**Comment by justinh-rahb** [comment]
This helps a lot for a couple of the details I was unclear on, thanks a lot @anuraagdjain! 👏

**Pull request merged**
