### PR TITLE
config: allow custom default user role

### PR DESCRIPTION
**Pull request by duhow**
For internal (restricted) websites, allow customize the `DEFAULT_USER_ROLE` with ENV values (set to `user` or `admin` for example).
Since at the moment we need to manually enable the user (`pending` -> `user`), I want to allow self-register for quick access.

### CODE REVIEW

**Comment by duhow** [comment]
Ah, just noticed that latest version does allow changing the default value...

image

**Comment by justinh-rahb** [comment]
Does your modification allow setting that with an envvar now? If so I'd say LGTM, doesn't hurt to have options.

**Comment by duhow** [comment]
Yes, that's the idea, allow customizing value optionally. It defaults to pending if not set.

**Comment by jannikstdl** [comment]
Maybe you cloud ad this as a env to the Dockerfile / as a K8s value too since not to many are looking into the code

**Comment by duhow** [comment]
Sounds good @jannikstdl , I can work on that in future PRs once we address the current ones :)

**Comment by justinh-rahb** [comment]
> Sounds good @jannikstdl , I can work on that in future PRs once we address the current ones :)

We're going to try and clear some of the backlog this weekend ☝️

**Pull request merged**
