### PR TITLE
Min-P override support via chat settings for openai backend 

### PR DESCRIPTION
**Pull request by cosmosgenius**
# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [ ] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [ ] **Testing:** Have you written and run sufficient tests for validating the changes?
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [x] **Prefix:** To cleary categorize this pull request, prefix the pull request title, using one of the following:
  - **BREAKING CHANGE**: Significant changes that may affect compatibility
  - **build**: Changes that affect the build system or external dependencies
  - **ci**: Changes to our continuous integration processes or workflows
  - **chore**: Refactor, cleanup, or other non-functional code changes
  - **docs**: Documentation update or addition
  - **feat**: Introduces a new feature or enhancement to the codebase
  - **fix**: Bug fix or error correction
  - **i18n**: Internationalization or localization changes
  - **perf**: Performance improvement
  - **refactor**: Code restructuring for better maintainability, readability, or scalability
  - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
  - **test**: Adding missing tests or correcting existing tests
  - **WIP**: Work in progress, a temporary label for incomplete or ongoing work

# Changelog Entry

### Description

- Add min-p override support via Chat Control. I notice the overrides where not being sent to openai api server(lm-studio).

### Added

- None

### Changed

- None

### Deprecated

- None

### Removed

- None

### Fixed

- add min-p param support similar to top_p in `src/lib/components/chat/Chat.svelte` for `generateOpenAIChatCompletion` function call.

### Security

- None

### Breaking Changes

- None

### Screenshots or Videos

Default Chat Settings
image

Override for Temperature and Min-P
image

### CODE REVIEW

**Comment by cosmosgenius** [comment]
I felt like this was miss when min-p integration was done. Let me know if a discussion needs to be opened around it or any further testing is needed by my side...

For context I am using lm-studio as my backend and `min-p` values were not being send.

**Comment by tjbck** [comment]
This might potentially break compatibility with other OpenAI compatible service providers, if you could verify that this PR works with notable providers, I'd greatly appreciate it!

**Comment by cosmosgenius** [comment]
Yes its breaking with groq `https://api.groq.com/openai/v1` 😭.
image

**Comment by cosmosgenius** [comment]
What do you suggest? By the way it only breaks if you override it otherwise its fine as only overridden values are being sent.

If I remove the min-p override from UI and only keep the temperature override it works.

**Comment by cosmosgenius** [comment]
`https://openrouter.ai/` seems to be working.

**Comment by tjbck** [comment]
I would say if we want additional param support we should use Functions and UserValves for now.

**Comment by cosmosgenius** [comment]
Functions worked nice. Thanks @tjbck. 

```
"""
title: MinP
author: cosmosgenius
author_url: https://github.com/cosmosgenius
funding_url: https://github.com/cosmosgenius
version: 0.1
"""

from pydantic import BaseModel, Field
from typing import Optional


class Filter:
    class Valves(BaseModel):
        pass

    class UserValves(BaseModel):
        min_p: float = Field(default=0.01, description="Add MinP paramater")

    def __init__(self):
        # Indicates custom file handling logic. This flag helps disengage default routines in favor of custom
        # implementations, informing the WebUI to defer file-related operations to designated methods within this class.
        # Alternatively, you can remove the files directly from the body in from the inlet hook
        # self.file_handler = True

        # Initialize 'valves' with specific configurations. Using 'Valves' instance helps encapsulate settings,
        # which ensures settings are managed cohesively and not confused with operational flags like 'file_handler'.
        self.valves = self.Valves()

    def inlet(self, body: dict, __user__: Optional[dict] = None) -> dict:
        body["min_p"] = __user__["valves"].min_p
        return body

    def outlet(self, body: dict, __user__: Optional[dict] = None) -> dict:
        return body
```

**Comment by cosmosgenius** [comment]
Closing the pr, as it can be done via Functions if needed.

**Pull request closed without merging**
