### PR TITLE
feat: Add Google Drive integration for Open-Webui

### PR DESCRIPTION
**Pull request by taylorwilsdon**
# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [ ] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [x] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [x] **Testing:** Have you written and run sufficient tests for validating the changes?
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [x] **Prefix:** To cleary categorize this pull request, prefix the pull request title, using one of the following:
  - **BREAKING CHANGE**: Significant changes that may affect compatibility
  - **build**: Changes that affect the build system or external dependencies
  - **ci**: Changes to our continuous integration processes or workflows
  - **chore**: Refactor, cleanup, or other non-functional code changes
  - **docs**: Documentation update or addition
  - **feat**: Introduces a new feature or enhancement to the codebase
  - **fix**: Bug fix or error correction
  - **i18n**: Internationalization or localization changes
  - **perf**: Performance improvement
  - **refactor**: Code restructuring for better maintainability, readability, or scalability
  - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
  - **test**: Adding missing tests or correcting existing tests
  - **WIP**: Work in progress, a temporary label for incomplete or ongoing work

# Changelog Entry

### Description

- Adds support for requested functionality in feat: data sources #5872 for Google Drive directly in the chat flow

### Added

- New item where "Upload files" is in the "+" picker for Google Drive uploads
- Support for docs, sheets and slides
- Support for Google oauth id and secret key in config endpoint
- Error handling

### Additional Information

See discussion #4079 

### Screenshots or Videos

Video:

https://github.com/user-attachments/assets/863fecc0-4217-43b5-9fde-698404df42a9

### CODE REVIEW

**Comment by tjbck** [comment]
Looks great, let's get those conflicts resolved 😅

**Comment by taylorwilsdon** [comment]
> Looks great, let's get those conflicts resolved 😅

yeah dang I built this off main and there's a few conflicts, will fix and push up shortly

**Comment by taylorwilsdon** [comment]
@tjbck also thinking to hide the google icon from the plus menu unless the env var is set. big picture if we want to capture this like an openai api key, where should that input live... maybe the Documents tab of the admin section? ie checkbox to enable google drive integration and two input fields to capture the creds?

**Comment by tjbck** [comment]
@taylorwilsdon `Documents` tab definitely sounds reasonable! As for the UI icons, I'll take care of it once this PR gets merged!

**Comment by taylorwilsdon** [comment]
Ok @tjbck I have added a toggle to the Documents section and fixed all the merge conflicts. Currently requires env vars for the secrets rather than text inputs which could be a fast follow but for my purposes I prefer hiding those values even from the admin panel. Let me know what you think!

**Comment by tjbck** [comment]
I'll work on some refacs once merged, but it definitely looks fantastic. Appreciate the hard work!

**Comment by tjbck** [comment]
@taylorwilsdon could you confirm this works as intended in dev branch?

**Comment by taylorwilsdon** [comment]
Let me pull the latest dev branch and test, a few days back the current state was non op so I fixed it in my local dev branch - I'll confirm that's still needed and cut a PR here @tjbck

**Comment by taylorwilsdon** [comment]
Found the issue @tjbck was just capitalization in routers/retrieval.py - PR here will make all well and I'll cut a doc PR as well https://github.com/open-webui/open-webui/pull/8115/files

**Comment by taylorwilsdon** [comment]
Doc PR here https://github.com/open-webui/docs/pull/342

**Comment by taylorwilsdon** [comment]
Hey @tjbck did this ever get deployed to main? I just stood up a new instance and am not seeing the toggle.

**Pull request merged**
