### PR TITLE
enhance: support Teams Incoming Webhook

### PR DESCRIPTION
**Pull request by changchiyou**
## Pull Request Checklist

- [x] **Description:** Briefly describe the changes in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [x] **Documentation:** Have you updated relevant documentation?
  > There are no relevant documents, so there's no need for an update.
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
  > No. No need.

---

## Description

Enhance the new feature `🔗 Webhook Integration` in [v0.1.114](https://github.com/open-webui/open-webui/releases/tag/v0.1.114) to support:

1. Teams Incoming Webhook:

    |Default|`CUSTOM_NAME=doge`|
    |-|-|
    | image | image |
  
    Refer to:
    
    - [Microsoft Learn - Send notifications to a Microsoft Teams channel from an Azure Data Factory or Synapse Analytics pipeline](https://learn.microsoft.com/en-us/azure/data-factory/how-to-send-notifications-to-teams?tabs=data-factory)
    - [Microsoft Learn - Create Incoming Webhooks](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=newteams%2Cdotnet)

2. Google Chat webhooks: 

    https://github.com/open-webui/open-webui/pull/1305/commits/d69dfb7c8b2183a633bd849839e056e9317d4803 by @justinh-rahb  

---

### Changed

- The subscription for new user sign-up events via webhook now extends its support to Teams Incoming Webhook, Google Chat webhook as well, having previously been limited to Discord and Slack only.

### CODE REVIEW

**Comment by justinh-rahb** [comment]
@changchiyou I'd do this PR myself but since it would conflict with yours and you've got it open anyway, you could modify your code slightly to support Google Chat webhooks as well:

```python
import json
import requests
from config import VERSION, WEBUI_FAVICON_URL, WEBUI_NAME

def post_webhook(url: str, message: str, event_data: dict) -> bool:
    try:
        payload = {}

        # Slack and Google Chat Webhooks
        if "https://hooks.slack.com" in url or "chat.googleapis.com" in url:
            payload["text"] = message
        # Discord Webhooks
        elif "https://discord.com/api/webhooks" in url:
            payload["content"] = message
        # Microsoft Teams Webhooks
        elif "webhook.office.com" in url:
            action = event_data.get("action", "undefined")
            facts = [
                {"name": name, "value": value}
                for name, value in json.loads(event_data.get("user", {})).items()
            ]
            payload = {
                "@type": "MessageCard",
                "@context": "http://schema.org/extensions",
                "themeColor": "0076D7",
                "summary": message,
                "sections": [
                    {
                        "activityTitle": message,
                        "activitySubtitle": f"{WEBUI_NAME} ({VERSION}) - {action}",
                        "activityImage": WEBUI_FAVICON_URL,
                        "facts": facts,
                        "markdown": True,
                    }
                ],
            }
        # Default Payload
        else:
            payload = {**event_data}

        r = requests.post(url, json=payload)
        r.raise_for_status()
        return True
    except Exception as e:
        print(e)
        return False
```

**Comment by changchiyou** [comment]
@justinh-rahb Done.

**Comment by justinh-rahb** [comment]
> @justinh-rahb Done.

I'll give this a test, but don't see any reason it won't work :) Thanks for the PR!

**Comment by tjbck** [comment]
LGTM, Thanks!

**Comment by justinh-rahb** [comment]
Just wanted to share, Google Chat modification works :)

Screenshot 2024-03-27 at 10 13 18 AM

**Pull request merged**
