### PR TITLE
feat: allow authenticating with a trusted email header

### PR DESCRIPTION
**Pull request by cheahjs**
## Pull Request Checklist

- [x] **Description:** Briefly describe the changes in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation?
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?

---

## Description

Adds an environment variable `WEBUI_AUTH_TRUSTED_EMAIL_HEADER` that can be specified to be used as the source of a trusted email header that should be used to automatically register and sign in.

Automatic sign in is achieved by adding the boolean `trusted_header_auth` to the result of calling `/api/config`. If this is set to true, the web app immediately triggers a sign in.

On the backend, if the header is set, a few changes are made:
1. `/signin` will always use the value of header specified by `WEBUI_AUTH_TRUSTED_EMAIL_HEADER` as the email address of the user, and we will ignore the password field
    * If the user is not registered, the backend will automatically register the user, with the name set as the email address from the header, and the password set as a random UUID string (to avoid modifying any more of the authentication logic)
2. A user calling `/update/password` will return an error, since a password is useless when the header is set.

It is a security hole to have `WEBUI_AUTH_TRUSTED_EMAIL_HEADER` set and an authenticating reverse proxy that sets the header is not the only way to reach the backend, as a user would be able to spoof any email address in the header and gain access to that email's account.

Styling of the automatic sign in page, and the error message when hitting `open-webui` without the necessary header.
image

This is tangentially related to the request https://github.com/open-webui/open-webui/issues/483, but this delegates the OAuth bit to a reverse proxy and doesn't handle OAuth inside of open-webui.

---

### Added

- 🔒 **Trusted Email Header**: `WEBUI_AUTH_TRUSTED_EMAIL_HEADER` can be used to authenticate users when used with an authenticating reverse proxy.

### CODE REVIEW

**Comment by tjbck** [comment]
is there an easy way to test this feature?

**Comment by tjbck** [comment]
I'll merge this to our dev branch for now and test more, Thanks!

**Comment by MarlNox** [comment]
Is this feature implemented in the recent releases, or still in dev?

**Comment by justinh-rahb** [comment]
@MarlNox been implemented for quite a while now, yes.

**Pull request merged**
