### PR TITLE
feat: fuzzy model search

### PR DESCRIPTION
**Pull request by thearyadev**
# Changelog Entry

## Description

this pr implements #4100 

fuzzy finding is very powerful, especially when querying data with special characters, or multiple fields. ~~The substring lookup has been replaced with fuzzy search using QuickScore~~

## Added

- ~~dependency: quick-score: 0.2.0~~
- fuzzy search algorithm. Fork of `quick-score`, simplified. 

## Changed

- removed substring filter

---

# Additional Information

- probably works on all languages
**chinese**
``` 
模型: [ "小型模型", "高级模型", "GPT模型" ]  -> Model: [ "Small model", "Advanced model", "GPT model" ]
小型: [ "小型模型" ] -> Small: [ "small model" ]
高级: [ "高级模型" ] -> Advanced: [ "Advanced Model" ]
```

# Screenshots or Videos

## old search

https://github.com/user-attachments/assets/c04275eb-dc8a-4c42-b351-754e98bc3157

## new search

https://github.com/user-attachments/assets/500987b5-9d85-4df2-9708-6a670b3fdcd6

## also works with tags

image

### CODE REVIEW

**Comment by silentoplayz** [comment]
MEOW, but also LGTM! 😸

**Comment by thearyadev** [comment]
im going to verify this isn't a dumpster fire for some different languages before ready.

**Comment by justinh-rahb** [comment]
One point I'd like to address is that introducing new dependencies solely for time-saving purposes may not always be the best approach. For a straightforward and self-contained function, such as a search algorithm, we could choose to re-implement just the necessary methods or copy the logic internally. This way, we won't have to be concerned about potential issues that could arise with that dependency down the line. As long as the algorithm fulfills its intended purpose, it’s unlikely to require significant modifications in the future.

**Comment by thearyadev** [comment]
> One point I'd like to address is that introducing new dependencies solely for time-saving purposes may not always be the best approach. For a straightforward and self-contained function, such as a search algorithm, we could choose to re-implement just the necessary methods or copy the logic internally. This way, we won't have to be concerned about potential issues that could arise with that dependency down the line. As long as the algorithm fulfills its intended purpose, it’s unlikely to require significant modifications in the future.

I understand the concern about introducing a new dependency for a small enhancement like this. 

a fuzzy implementation would still bring the most dynamic search experience, in comparison to other search methods. 

That being said, you're concerned about the about the unnecessary overhead of adding another dependency, perhaps we could explore bundling quick-score or even creating a refactored fork with only the necessary features and bundling that to satisfy this use case? This way, we can still leverage the existing implementation without having to implement a fuzzy search algorithm, and avoid adding a million deps.

**Comment by justinh-rahb** [comment]
> > One point I'd like to address is that introducing new dependencies solely for time-saving purposes may not always be the best approach. For a straightforward and self-contained function, such as a search algorithm, we could choose to re-implement just the necessary methods or copy the logic internally. This way, we won't have to be concerned about potential issues that could arise with that dependency down the line. As long as the algorithm fulfills its intended purpose, it’s unlikely to require significant modifications in the future.
> 
> a fuzzy implementation would still bring the most dynamic search experience in comparison to other search methods.
> 
> That being said, you're concerned about the about the unnecessary overhead of adding another dependency, perhaps we could explore bundling quick-score or even creating a refactored fork with only the necessary features and bundling that to satisfy this use case? This way, we can still leverage the existing implementation without having to implement a fuzzy search algorithm and avoid adding a million deps.

Copy-pasta works for me, the code seems pretty static so I don't think we'll be missing out on any hot new features 😆

**Comment by thearyadev** [comment]
made some changes to the code to make it more typescript compliant, and to remove some features that aren't strictly required for this use case. should make the code easier to maintain.

**Comment by justinh-rahb** [comment]
I'll give the PR a test and we'll see how she goes

**Comment by tjbck** [comment]
Let's refactor this with https://www.npmjs.com/package/fuse.js

**Comment by tjbck** [comment]
Closing in favour of https://github.com/open-webui/open-webui/pull/4273/commits/6ac40552b485ab1977f6e2b8a233859e3bf2b6af

**Comment by thearyadev** [comment]
> Closing in favour of https://github.com/open-webui/open-webui/pull/4273/commits/6ac40552b485ab1977f6e2b8a233859e3bf2b6af

In my testing I found that fuse.js had weird results, specifically with special characters. 

I didn't spend much time turning dials so it's likely possible to get better results. Either way, should be better than substring search.

**Pull request closed without merging**
