### PR TITLE
feat: show warning for deleted files context

### PR DESCRIPTION
**Pull request by jonathan-rohde**
# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [ ] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [x] **Testing:** Have you written and run sufficient tests for validating the changes?
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [x] **Label:** To cleary categorize this pull request, assign a relevant label to the pull request title, using one of the following:
  - **BREAKING CHANGE**: Significant changes that may affect compatibility
  - **build**: Changes that affect the build system or external dependencies
  - **ci**: Changes to our continuous integration processes or workflows
  - **chore**: Refactor, cleanup, or other non-functional code changes
  - **docs**: Documentation update or addition
  - **feat**: Introduces a new feature or enhancement to the codebase
  - **fix**: Bug fix or error correction
  - **i18n**: Internationalization or localization changes
  - **perf**: Performance improvement
  - **refactor**: Code restructuring for better maintainability, readability, or scalability
  - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
  - **test**: Adding missing tests or correcting existing tests
  - **WIP**: Work in progress, a temporary label for incomplete or ongoing work

# Changelog Entry

### Description

- Once a document has been removed from the vector database, the context is compromised and chat messages either result in an invalid/wrong answer or the LLM will just reply with "I don't know"

### Added

- Warning to each chat response from LLM, if at least one document checksum was not found in vector database

---

### Screenshots or Videos

image

### CODE REVIEW

**Comment by justinh-rahb** [comment]
I like this, this is quite useful.

**Comment by tjbck** [comment]
This is great! but I believe it's better to check for checksum during document attachment process then alert users "Selected file no longer exists" and also remove the DB. Let me know what you guys think!

**Comment by Daerphen** [comment]
I would not delete the document entry in case any user is trying to use it without having the embeddings in the vector database, maybe change the document handling in the document list, that as soon as a document is deleted from the list also the corresponding embeddings are removed. Right now the embeddings still exists in the vector database.

Of course then existing chats still referencing the document will get the warnings from this PR.

**Comment by jonathan-rohde** [comment]
I would not delete the document entry in case any user is trying to use it without having the embeddings in the vector database, maybe change the document handling in the document list, that as soon as a document is deleted from the list also the corresponding embeddings are removed. Right now the embeddings still exists in the vector database.

Of course then existing chats still referencing the document will get the warnings from this PR.

**Comment by tjbck** [comment]
I believe the solution here is to just revectorise them then, check for files in the uploads directory, then once the matching file has been found, parse the document and add them back to the vector db. If the file is absent, alert the users there isn't any embeddings for this file and block them from attaching/interacting with it.

**Comment by jonathan-rohde** [comment]
Okay maybe we are talking about completely different things and intentions.

- During a message input you can only select documents and collections that exist in the relational database.
- The current architecture makes it almost impossible to have a Document entry without having embeddings available as embeddings are only deleted, when an admin wipes the vector database

So in my opinion we only need to consider the case that in the past a user has selected a document or a collection containing a document that in the meantime has been vanished from relational database, vector database and most probably from the data directory. All answers from LLM will not contain the referenced document.

See here another screenshot. Between the first and the second message the embeddings and document entries were removed by an admin

image

**Comment by tjbck** [comment]
Perhaps we're talking about two different things, but my point still stands. It should block people from interacting with the chat entirely.

**Comment by tjbck** [comment]
Closing due to conflicts, but I highly encourage you to reopen!

**Pull request closed without merging**
