### PR TITLE
feat: custom openai endpoint

### LINKED ISSUE #230: feat: configurable OpenAI API endpoint.
**Is your feature request related to a problem? Please describe.**
Make the API endpoint url configurable so the user can connect other OpenAI-compatible APIs with the web-ui.

**Describe the solution you'd like**
Make it configurable through environment variables or add a new field in the **Settings** > **Add-ons**.

**Describe alternatives you've considered**
Tried [this](https://www.typingmind.com/) but it is not open source and self-hostable.

**Additional context**
Nill.

### PR DESCRIPTION
**Pull request by tjbck**
Resolves #230

### CODE REVIEW

**Comment by justinh-rahb** [comment]
> Hey guys! Just added the custom api endpoint feature to #265 branch. If any of you guys could try it out and confirm that it works, I'll merge it to main! Thanks!

@tjbck Loading the model names from the /models endpoint is working:
Screenshot 2023-12-22 at 11 55 51 PM

However, generation is not responding:
Screenshot 2023-12-22 at 11 58 15 PM

I got the same response with all models. Unfortunately the Docker log doesn't show me anything useful, anywhere else I can look or enable debugging?

**Comment by justinh-rahb** [comment]
No error this time, but hangs on generation:
Screenshot 2023-12-23 at 12 09 47 AM

**Comment by tjbck** [comment]
@justinh-rahb Could you share your browser console logs with us? That would be extremely helpful! Thanks as always!

**Comment by justinh-rahb** [comment]
> @justinh-rahb Could you share your browser console logs with us? That would be extremely helpful! Thanks as always!

I edited just after when I realized I forgot, sorry

**Comment by justinh-rahb** [comment]
Here's the one you need:
Screenshot 2023-12-23 at 12 15 26 AM

**Comment by tjbck** [comment]
All these api endpoints have different behaviours 😅, I think I know what to do now

**Comment by tjbck** [comment]
Fingers crossed, everything should just work now!

**Comment by justinh-rahb** [comment]
Instant response!

Screenshot 2023-12-23 at 12 27 36 AM

Will try with local APIs next, but this is already a win!

**Comment by tjbck** [comment]
Sounds good, Will do some more testing and merge this branch to main! @justinh-rahb Thanks a lot for helping with the testing!

**Comment by justinh-rahb** [comment]
Can confirm it works with textgen's API, as well as LM Studio:

Screenshot 2023-12-23 at 12 38 06 AM

**Comment by tjbck** [comment]
LGTM, Thanks everyone!

**Comment by justinh-rahb** [comment]
Screenshot 2023-12-23 at 12 50 08 AM
mustgofaster

**Pull request merged**
