### PR TITLE
feat: dropdown suggestions for the 'Pull a model from Ollama.com' input box 

### LINKED ISSUE #1242: feat: typeahead/autocomplete/dropdown suggestions for the 'Pull a model from Ollama.com' input box
**Is your feature request related to a problem? Please describe.**
This would be a nice-to-have feature for improved UX.  Potentially saves the user time from going to https://ollama.com/models, copy pasting the name of a model and going back to OpenWebUI to pull the model. 

**Describe the solution you'd like**
A typeahead, autocomplete, and/or a suggestion select menu dropdown implemented, which would effectively turn the input box into a search bar, using a hardcoded list of models on the frontend. 

**Describe alternatives you've considered**
Non hard-coded solution, however Ollama.com doesn't have an API that returns a list of the available models to pull, thus we would need to web scrape ollama.com/models to get a list of the models each time

**Additional context**
I have a suggestion select menu dropdown using a hardcoded list of models implemented locally, can make a draft PR but would like to see if anyone has any input or comment on this.

### PR DESCRIPTION
**Pull request by dannyl1u**
## Pull Request Checklist

- [ ] **Description:** Briefly describe the changes in this pull request.
- [ ] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation?
- [ ] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?

---

## Description

This PR introduces a new feature in the input box where model names from ollama.com are suggested to the user as they type. This feature enhances the user experience by providing real-time suggestions and reducing the time users spend typing or remembering specific models.

---

### Added

- Implemented searchable dropdown feature for model names from ollama.com

Closes #1242

### CODE REVIEW

**Comment by jannikstdl** [comment]
Cool👍🏼

**Comment by tjbck** [comment]
To provide more pointers, we might want to add a route to our Ollama proxy server that scraps official Ollama website!

**Comment by jannikstdl** [comment]
> To provide more pointers, we might want to add a route to our Ollama proxy server that scraps official Ollama website!

@tjbck just be aware that this would be a external connection and we should give it a fallback and/or the ability to deactivate since  just clicking in the inputfield would make an external request and many users are running OpenWebUI in an isolated environment.

**Comment by dannyl1u** [comment]
> > To provide more pointers, we might want to add a route to our Ollama proxy server that scraps official Ollama website!
> 
> @tjbck just be aware that this would be a external connection and we should give it a fallback and/or the ability to deactivate since just clicking in the inputfield would make an external request and many users are running OpenWebUI in an isolated environment.

@jannikstdl I considered this as well, but the actual pulling of models requires external connection anyways, so I think it's safe to assume that if a user is using open-webui to pull a model, they are OK with it making an external connection.

**Comment by jannikstdl** [comment]
> > > To provide more pointers, we might want to add a route to our Ollama proxy server that scraps official Ollama website!
> 
> > 
> 
> > @tjbck just be aware that this would be a external connection and we should give it a fallback and/or the ability to deactivate since just clicking in the inputfield would make an external request and many users are running OpenWebUI in an isolated environment.
> 
> 
> 
> @jannikstdl I considered this as well, but the actual pulling of models requires external connection anyways, so I think it's safe to assume that if a user is using open-webui to pull a model, they are OK with it making an external connection.

Yes that was my first thought too but now as the GGUF upload feature is out of experimental state users **might** use this instead of pulling models from ollama which does not require external connections.

**Comment by tjbck** [comment]
Let's get the ball rolling for this feature, If I have time I'll implement the web scrap feature as well.

**Comment by tjbck** [comment]
Closing due to conflicts, I strongly encourage you to open a new PR! 🙌

**Pull request closed without merging**
