### PR TITLE
Added some i18n keys & updated german locale

### PR DESCRIPTION
**Pull request by jannikstdl**
- Added some i18n keys (Mostly for tooltips)
- Updated german locale
- ran i18n:parse script to parse new i18n strings in the translation JSON files

### CODE REVIEW

**Comment by jannikstdl** [comment]
@Maximilian-Pichler if i missed something let me know.

**Comment by tjbck** [comment]
Conflicts :/

**Comment by jannikstdl** [comment]
@tjbck will add the keys without the updated locale JSONs. You can run the parser by yourself afterwards. The locale conflicts are driving me nuts.

**Comment by jannikstdl** [comment]
@tjbck should be good now! I think there should be no non i18n strings left, otherwise let me know.

**Comment by tjbck** [comment]
Thanks!

**Pull request merged**
