### PR TITLE
feat: move to native `sentence_transformers`

### PR DESCRIPTION
**Pull request by buroa**
Using the ChromaDB ones are very limiting, and under the hood they are just sentence-transformer models anyways. Let's open it up and let them use any embedding model `sentence_transformers` supports loading.

### CODE REVIEW

**Comment by justinh-rahb** [comment]
Thank you for submitting this pull request! It's much appreciated. 

I noticed that the PR template wasn't used this time around. Could you let us know if you've completed regression testing, updated the changelog, and all relevant documentation? It would also be great if you could include some notes on how this changes default behaviours, and any other relevant info in the [docs repo](https://github.com/open-webui/docs). 

It's really helpful to have a clear understanding of the work, so we can merge with confidence!

**Comment by buroa** [comment]
> docs repo

Hey @justinh-rahb. I went and tested these changes by building the container on my local branch, launching the UI and embedding some local documents and querying them via `/rag/api/v1/query/doc`. I also updated the embedding model to something that wasn't supported before, such as `mixedbread-ai/mxbai-embed-large-v1`.

There should be no change to users that are using the default embedding model as I kept it `all-MiniLM-L6-v2`.  This just extends functionality to users that want to use other non-`sentence-transformer` embedding models.

I will update the changelog on this branch as well as update the docs repo and will link the PRs together.

**Comment by justinh-rahb** [comment]
Sounds good @buroa just checking we got all our ducks in a row. Tim still needs to sign off before it can be merged but as long as it's not impacting previous expectations I say LGTM

**Comment by tjbck** [comment]
LGTM, Thanks!

**Comment by buroa** [comment]
> @tjbck @justinh-rahb @buroa Why was `local_files_only` and `RAG_EMBEDDING_MODEL_AUTO_UPDATE` removed? This has re-introduced the huggingface network dependency on startup. It will also automatically update the embedding model and potentially break collections when the models are changed.

I overlooked this. I'll get a PR out soon to fix it up. Sorry about that!

**Comment by tjbck** [comment]
@lainedfles Should be reverted on our dev branch now, let us know if you're encountering any issues!

**Pull request merged**
