### PR TITLE
Adds support for Azure OpenAI

### PR DESCRIPTION
**Pull request by frandominguezl**
## Pull Request Checklist

- [x] **Target branch:** Pull requests should target the `dev` branch.
- [x] **Description:** Briefly describe the changes in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [ ] **Testing:** Have you written and run sufficient tests for the changes?
- [x] **Code Review:** Have you self-reviewed your code and addressed any coding standard issues?

---

## Description

Adds native support for Azure OpenAI, in a similar way that it's implemented for OpenAI, rather than relying in LiteLLM.

---

### Added

- Support for Azure OpenAI

### CODE REVIEW

**Comment by justinh-rahb** [comment]
Builds on Mac, but I haven't got an Azure API to test with.

**Comment by jannikstdl** [comment]
This should be already possible with litellm, isn't it?

**Comment by tjbck** [comment]
Ideally we'd want to integrate azure support to current existing openai codebase. I appreciate the effort!

Related #1667

**Comment by rcarmo** [comment]
Can we get a resolution here? #1667 is also closed, and this would be an extremely useful feature.

**Comment by justinh-rahb** [comment]
> Can we get a resolution here? #1667 is also closed, and this would be an extremely useful feature.

Closed for same reason: it was implemented as an entirely separate app within the backend when what Tim desires is for the existing openai app to be extended to support azure endpoints instead.

**Comment by frandominguezl** [comment]
Sorry for coming back to this, but it would be good to implement this by default. Could you please let me know how do you want to do this using the existing OpenAI codebase so I can work on it?

Thanks in advance @tjbck

**Pull request closed without merging**
