### PR TITLE
feat: show total number of documents

### PR DESCRIPTION
**Pull request by jannikstdl**
### Description

- Display the total number of documents in the UI. This is useful when uploading a large number of documents to verify that all have been uploaded.

### Screenshots or Videos

image

### CODE REVIEW

**Review by Peter-De-Ath — APPROVED** [review]

**Comment by Peter-De-Ath** [comment]
Handy  :1st_place_medal:

**Comment by silentoplayz** [comment]
Neat! I was just thinking though, could we maybe adopt this look for the documents.length value, where `|` is used to add space between the `Documents` text and the documents.length value rather than `()` to contain the documents.length value?

e.g:
image

**Comment by jannikstdl** [comment]
@silentoplayz yes definitely! I was searching this style haha, will add it when I'm at home.

**Comment by tjbck** [comment]
LGTM, Thanks!

**Pull request merged**
