### PR TITLE
feat: added custom workflow support for ComfyUI

### PR DESCRIPTION
**Pull request by JohnTheNerd**
# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [x] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [x] **Testing:** Have you written and run sufficient tests for validating the changes?
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [x] **Prefix:** To cleary categorize this pull request, prefix the pull request title, using one of the following:
  - **BREAKING CHANGE**: Significant changes that may affect compatibility
  - **build**: Changes that affect the build system or external dependencies
  - **ci**: Changes to our continuous integration processes or workflows
  - **chore**: Refactor, cleanup, or other non-functional code changes
  - **docs**: Documentation update or addition
  - **feat**: Introduces a new feature or enhancement to the codebase
  - **fix**: Bug fix or error correction
  - **i18n**: Internationalization or localization changes
  - **perf**: Performance improvement
  - **refactor**: Code restructuring for better maintainability, readability, or scalability
  - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
  - **test**: Adding missing tests or correcting existing tests
  - **WIP**: Work in progress, a temporary label for incomplete or ongoing work

# Changelog Entry

### Description

this PR adds the ability to define any workflow to be ran via ComfyUI, allowing users to do all sorts of things like LoRA's, using new models without waiting for official Open-WebUI support, and much much more.

see docs at https://github.com/open-webui/docs/pull/185 because the only way I found to get the workflow in the correct format is very strange. pushed a standard image (without CUDA or ollama) at `ghcr.io/johnthenerd/open-webui:comfyui-custom-workflows` which is what I'm running right now.

since I don't like front-end work, we add yet more environment variables:

- COMFYUI_CUSTOM_WORKFLOW_PATH: a local path in which a JSON file with the ComfyUI workflow exists. must be mounted in the Docker container, if running inside Docker.
- COMFYUI_CUSTOM_WORKFLOW_SEED_INDEX/COMFYUI_CUSTOM_WORKFLOW_PROMPT_INDEX: since we no longer have exact indices to update, this is the least we need to be able to generate images based on the user's input. technically they are optional, but well, you probably want a seed and a prompt right?

### Added

- the ability to use custom workflows with ComfyUI, instead of being stuck with the inlined defaults bundled with Open WebUI.
    - this in turn means the ComfyUI integration is much more customizable and we won't have to maintain it as much for supporting new models, etc

### CODE REVIEW

**Comment by hartmark** [comment]
It would have been nice to have more parameters exposed, I'm quite noob with both this project and python.
 
I'm thinking on having some workflow with face-swapping using ReActor. So it would be nice to have a key-value pair that the LLM can populate.

One solution would be to have the comfyUI function use a key-value pair it replaces all it can find in the json-file.

**Comment by JohnTheNerd** [comment]
one issue with allowing the LLM to make changes in the workflow is that the LLM can be tricked to do things it's not supposed to. furthermore, I do not know of a way exposed in the UI to give it parameters like that based on the LLM response.

however, I was actually just working on a solution that tries to meet in the middle (I wanted the LLM to have the ability to enable the realism lora for flux, which is why I created this pull request in the first place). I'm defining an option to override the parameters passed to the ComfyUI plugin (but not exposing it in the web UI), so that custom tools such as https://openwebui.com/t/justinrahb/image_gen can be modified to just modify the entire workflow, with exactly as much guidance from the LLM as is previously defined in the tool parameters (so we can avoid issues with the LLM making changes it's not supposed to, and make the generation process as reliable as possible regardless of LLM hallucinations).

the image is building right now, I'll first test it and if it works, will commit it here so you can try it too!

**Comment by JohnTheNerd** [comment]
I added a new parameter to `image_generations()` named `prompt_override` which, if `custom_workflow` is defined will replace the entire ComfyUI workflow. see file below for how I currently use it (this is a tool added to Open-WebUI, allowing a parameter to enable the realism LoRA for Flux):

[comfyui-flux-realism-lora-test.txt](https://github.com/user-attachments/files/16640004/comfyui-flux-realism-lora-test.txt)

@hartmark the image is available at ghcr.io/johnthenerd/open-webui:comfyui-custom-workflows if you'd like to test this!

**Comment by tjbck** [comment]
I'll also personally take a look to make it entirely flexible as well if possible!

**Comment by JohnTheNerd** [comment]
great! let me know if I can help!

**Comment by hartmark** [comment]
Cool, I'll try out your image when I get the time.

I'm trying to achieve a chatbot for image generation.

I have been having problems getting it to consistently generate images 
https://github.com/open-webui/open-webui/discussions/4658

**Comment by hartmark** [comment]
@JohnTheNerd I tried out your docker image and added the tool you linked.

I seem to not be able to generate any images.

I'm using the gemma2 9B model

This is what I get in the log:
```
ollama-webui  | generate_ollama_chat_completion
ollama-webui  | content: ["image_gen_flux"] 	
ollama-webui  | 
ollama-webui  | ['image_gen_flux']
ollama-webui  | image_gen_flux
ollama-webui  | History:
ollama-webui  | USER: """generate a photorealistic cat"""
ollama-webui  | Query: generate a photorealistic cat
ollama-webui  | generate_ollama_chat_completion
ollama-webui  | content: ```json
ollama-webui  | {
ollama-webui  |  "name": "generate_image",
ollama-webui  |  "parameters": {
ollama-webui  |   "prompt": "A highly realistic depiction of a domesticated feline, showcasing its fur texture and lifelike eyes, set against a backdrop that complements the cat's natural beauty.",
ollama-webui  |   "photorealism": true
ollama-webui  |  }
ollama-webui  | }
ollama-webui  | ```
ollama-webui  | Error: Expecting value: line 1 column 1 (char 0)
ollama-webui  | False
ollama-webui  | tool_contexts: []

```

**Comment by JohnTheNerd** [comment]
interesting. I have it running myself and it works just fine. have you tried the flux realism lora on ComfyUI itself? I believe it requires some custom nodes by xlabs to run. any useful logs on the ComfyUI instance?

**Comment by hartmark** [comment]
Do you have anything special in the system prompt in ollama?

Can I just take the JSON in your image tool and make a file and load it into comfyUI?

**Comment by JohnTheNerd** [comment]
I don't use ollama. I use a very custom version of vllm that has commits cherry-picked from a fork and with patches I wrote myself to work with tool calling. I don't think it would matter, though, as long as the tools are called properly by the LLM.

**Comment by JohnTheNerd** [comment]
I don't think you can use the JSON used in the tool with ComfyUI directly, because the format sent to the API differs from the format used in the UI. but, I just used the default workflow (see the respective documentation PR on how to get any JSON workflow in a format usable in Open WebUI). https://github.com/XLabs-AI/x-flux-comfyui/blob/main/workflows/lora_workflow.json

**Comment by hartmark** [comment]
Is it the same format if I do the export (api format) button?
image

I need to first enable this in the settings to get the alternative.
image

**Comment by hartmark** [comment]
How does the vllm work btw?

**Comment by JohnTheNerd** [comment]
> Is it the same format if I do the export (api format) button?
> image
> 
> I need to first enable this in the settings to get the alternative.
> image
> 

no idea, it's interesting though as it's much easier than using the browser devtools. please do tell if it functions the same!


> How does the vllm work btw?

vllm is meant for serving multiple people at once with optimizations for aggregate throughput rather than single-user performance, but in the current state (tool calling is still an open PR, and you need specific models that are actually trained to support tool calling, which is what you need for what you're doing here) I wouldn't recommend it for you.

**Comment by hartmark** [comment]
btw, shouldn't image gen tool use:
COMFYUI_CUSTOM_WORKFLOW_SEED_INDEX/COMFYUI_CUSTOM_WORKFLOW_PROMPT_INDEX
if they are set?

**Comment by hartmark** [comment]
It seems the image generator get stuck somehow, I don't know if the LLM is somehow still waiting for more than the image or something.

I have now that it consistently generates images. But after the image is generated and shown in the chat it just waits forever and now more text is added.

image



Log:
```
ollama-webui  | INFO  [apps.images.utils.comfyui] WebSocket connection established.
ollama-webui  | INFO  [apps.images.utils.comfyui] queue_prompt
ollama-webui  | INFO  [apps.images.utils.comfyui] get_history
ollama-webui  | INFO  [apps.images.utils.comfyui] get_image
ollama-webui  | No requirements found in frontmatter.
ollama-webui  | Loaded module: autotool_filter
ollama-webui  | generate_ollama_chat_completion
ollama-webui  | content: ["image_gen_flux"] 
ollama-webui  | 
ollama-webui  | ['image_gen_flux']
ollama-webui  | image_gen_flux
ollama-webui  | History:
ollama-webui  | USER: """cute cat"""
ollama-webui  | Query: cute cat
ollama-webui  | generate_ollama_chat_completion
ollama-webui  | content: {"name": "generate_image", "parameters": {"prompt": "Generate an adorable image of a fluffy kitten with bright eyes and playful whiskers."}} 
ollama-webui  | 
ollama-webui  | {'name': 'generate_image', 'parameters': {'prompt': 'Generate an adorable image of a fluffy kitten with bright eyes and playful whiskers.'}}
ollama-webui  | False
ollama-webui  | tool_contexts: ["Tell the user that an image was successfullly generated. Don't tell them that it was 'already generated' as they can only see it as you respond. Respond in the user's own language, which might not be English. Also tell the user that the exact prompt given to Flux was: Generate an adorable image of a fluffy kitten with bright eyes and playful whiskers."]
ollama-webui  | INFO:     172.19.0.1:50776 - "GET /cache/image/generations/77368131-8ae7-48d4-9367-36fd0bb755d9.png HTTP/1.1" 200 OK
ollama-webui  | INFO  [apps.ollama.main] url: http://bernard.lan:11434
ollama        | [GIN] 2024/08/18 - 23:15:18 | 200 |  6.386021874s |      172.19.0.1 | POST     "/api/chat"

```

**Comment by JohnTheNerd** [comment]
interesting. i think it calls the LLM again after the image generation is complete. is it possible ollama is stuck somewhere at that point? i do always get some text generated after the image generation is complete.

**Comment by hartmark** [comment]
This is how I have setup the image-generator model.

Can you try out if you get the same behaviour?

System prompt:```

You should never respond with that you cannot generate images or anything like that.

Generates an image of the prompt if it is something that could be thought as a concept to generate an image.
```
![image](https://github.com/user-attachments/assets/d22ab17e-6246-4eff-9f7b-31725851f705)

**Comment by JohnTheNerd** [comment]
I'm increasingly starting to think it's to do with ollama during the response, because I don't need a system prompt at all to generate images. simply having the respective tool enabled works like a charm. do you have debug logs from ollama by any chance?

it's difficult for me to test with ollama instead of vllm as my GPUs are all occupied and I'm not the only person who uses my open-webui instance, so the extended downtime to set up ollama would be disruptive.

an easy way to rule out ollama entirely could be to just use the OpenAI API for a few API calls. gpt-4o supports function calling at a very low price point.

another point of consideration is that you're using Gemma which isn't trained for function calling (ollama implements it in a different way afaik). llama 3.1 is. it might be worth trying that instead, if the OpenAI API is infeasible? once you know the problem, it'll probably be way easier to find a working solution.

if you'd like to test using my exact setup, I can share my Frankenstein vllm fork, but keep in mind that I use the 70b AWQ meaning you'll need about 48GB of VRAM (or lots of patience, if you're offloading to RAM) if you want to replicate my exact setup. Meta warns that the 8b version of llama 3.1 has trouble keeping up with conversations when tools are enabled, and they only recommend the 8b for zero-shot tool calling, so the 70b might actually be necessary.

**Comment by tjbck** [comment]
I'll start a major refac on this, and most of the codebase here will be rewritten. Any bugs here will be resolved after the refac, appreciate your patience!

**Comment by hartmark** [comment]
> I'm increasingly starting to think it's to do with ollama during the response, because I don't need a system prompt at all to generate images. simply having the respective tool enabled works like a charm. do you have debug logs from ollama by any chance?
> 
> it's difficult for me to test with ollama instead of vllm as my GPUs are all occupied and I'm not the only person who uses my open-webui instance, so the extended downtime to set up ollama would be disruptive.
> 
> an easy way to rule out ollama entirely could be to just use the OpenAI API for a few API calls. gpt-4o supports function calling at a very low price point.
> 
> another point of consideration is that you're using Gemma which isn't trained for function calling (ollama implements it in a different way afaik). llama 3.1 is. it might be worth trying that instead, if the OpenAI API is infeasible? once you know the problem, it'll probably be way easier to find a working solution.
> 
> if you'd like to test using my exact setup, I can share my Frankenstein vllm fork, but keep in mind that I use the 70b AWQ meaning you'll need about 48GB of VRAM (or lots of patience, if you're offloading to RAM) if you want to replicate my exact setup. Meta warns that the 8b version of llama 3.1 has trouble keeping up with conversations when tools are enabled, and they only recommend the 8b for zero-shot tool calling, so the 70b might actually be necessary.

I tried using llama 3.1 8B and it seems to be working better.

I only have 16GB vram and 32GB system ram so running your Frankenstein's monster wont be an option for me *grin*

I had some issues of running out of vram so I switched to use ollama in cpu-only. I get just a few extra seconds to response because I have a AMD Ryzen 9 5900X 12-Core so it utilizes my cores quite well.

**Comment by hartmark** [comment]
nevermind, llama 3.1 8B happens to get stuck sometimes aswell,

**Comment by JohnTheNerd** [comment]
don't mind the force push, just rebased off dev for the sake of my own servers (in a really hacky way since we're not merging anyway lol)

**Comment by tjbck** [comment]
Closing in favour of 063e006446082c899488f8f5ecc68aa29b3c278a, let me know if you encounter any issues!

**Comment by hartmark** [comment]
Cool, when is ghcr.io/open-webui/open-webui:main updated with that commit?

**Comment by justinh-rahb** [comment]
> Cool, when is ghcr.io/open-webui/open-webui:main updated with that commit?

https://github.com/open-webui/open-webui/releases/tag/v0.3.14

**Comment by meetzuber** [comment]
> Closing in favour of [063e006](https://github.com/open-webui/open-webui/commit/063e006446082c899488f8f5ecc68aa29b3c278a), let me know if you encounter any issues!
> 
> image

Please also add option to randomize seed, seed is not updating and same image is generated for same prompt.

**Comment by JohnTheNerd** [comment]
I briefly looked at the commit and see the problem. the Flux workflows use `noise_seed` instead of `seed` because it uses the RandomNoise node, which is not handled since the refactor.

**Comment by tjbck** [comment]
@JohnTheNerd you should be able to edit the key value like such:

image

Hope this helps!

**Comment by chaoqunxie** [comment]
"10": {
    "inputs": {
      "vae_name": "ae.sft"
    },
    "class_type": "VAELoader",
    "_meta": {
      "title": "VAE加载器"
    }
  },  
  "11": {
    "inputs": {
      "clip_name1": "t5xxl_fp8_e4m3fn.safetensors",
      "clip_name2": "clip_l.safetensors",
      "type": "flux"
    },
    "class_type": "DualCLIPLoader",
    "_meta": {
      "title": "双CLIP加载器"
    }
  },
  "12": {
    "inputs": {
      "unet_name": "flux1-schnell-fp8.safetensors",
      "weight_dtype": "fp8_e4m3fn"
    },
    "class_type": "UNETLoader",
    "_meta": {
      "title": "UNET加载器"
    }
  },  how to config   "vae_name" "clip_name1" "clip_name2"

**Comment by Gee1111** [comment]
i have a similar problem: when i try to configurate my image gen under the admin image settings i get the error ""GET /images/api/v1/models HTTP/1.1" 400 Bad Request" in the logs and "Something went wrong :/ Expecting value: line 1 column 1 (char 0)" in the web ui. My comfyui workflow works perfect

my api json:
`{
  "3": {
    "inputs": {
      "text": "",
      "clip": [
        "34",
        1
      ]
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "CLIP Text Encode (Prompt) Pos"
    }
  },
  "4": {
    "inputs": {
      "seed": 558740513626235,
      "steps": 20,
      "cfg": 1,
      "sampler_name": "euler",
      "scheduler": "simple",
      "denoise": 1,
      "model": [
        "34",
        0
      ],
      "positive": [
        "8",
        0
      ],
      "negative": [
        "29",
        0
      ],
      "latent_image": [
        "16",
        0
      ]
    },
    "class_type": "KSampler",
    "_meta": {
      "title": "KSampler"
    }
  },
  "8": {
    "inputs": {
      "guidance": 3.5,
      "conditioning": [
        "3",
        0
      ]
    },
    "class_type": "FluxGuidance",
    "_meta": {
      "title": "FluxGuidance"
    }
  },
  "9": {
    "inputs": {
      "samples": [
        "4",
        0
      ],
      "vae": [
        "21",
        0
      ]
    },
    "class_type": "VAEDecode",
    "_meta": {
      "title": "VAE Decode"
    }
  },
  "16": {
    "inputs": {
      "width": 512,
      "height": 512,
      "batch_size": 1
    },
    "class_type": "EmptySD3LatentImage",
    "_meta": {
      "title": "EmptySD3LatentImage"
    }
  },
  "19": {
    "inputs": {
      "unet_name": "flux1-dev-Q8_0.gguf"
    },
    "class_type": "UnetLoaderGGUF",
    "_meta": {
      "title": "Unet Loader (GGUF)"
    }
  },
  "21": {
    "inputs": {
      "vae_name": "ae.safetensors"
    },
    "class_type": "VAELoader",
    "_meta": {
      "title": "Load VAE"
    }
  },
  "27": {
    "inputs": {
      "clip_name1": "t5-v1_1-xxl-encoder-Q8_0.gguf",
      "clip_name2": "clip_l.safetensors",
      "type": "flux"
    },
    "class_type": "DualCLIPLoaderGGUF",
    "_meta": {
      "title": "DualCLIPLoader (GGUF)"
    }
  },
  "28": {
    "inputs": {
      "filename_prefix": "ComfyUI",
      "images": [
        "9",
        0
      ]
    },
    "class_type": "SaveImage",
    "_meta": {
      "title": "Save Image"
    }
  },
  "29": {
    "inputs": {
      "text": "",
      "clip": [
        "34",
        1
      ]
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "CLIP Text Encode (Prompt) Neg"
    }
  },
  "34": {
    "inputs": {
      "lora_name": "photorealism.safetensors",
      "strength_model": 1,
      "strength_clip": 1,
      "model": [
        "19",
        0
      ],
      "clip": [
        "27",
        0
      ]
    },
    "class_type": "LoraLoader",
    "_meta": {
      "title": "Load LoRA"
    }
  }
}`

**Pull request closed without merging**
