### PR TITLE
Improve Session Security

### PR DESCRIPTION
**Pull request by explorigin**
This PR changes a few things around how sessions are handled in order to improve security.

Problem 1: The session secret is hard-coded. Few people will provide their own thus the security of the whole project is a risk for everyone who deploys it.

Solution: One first run, the start script generates a randomly generated session key and stores it to a file. If no secret key is provided, the start script will grab this one. WEBUI_JWT_SECRET_KEY is still accepted. I flagged the line in config.py to be deprecated in the next major release.

Problem 2: JWT signatures were not verified. This makes session stealing easy.

Solution: Remove the option turning off jwt signature verification.

Problem 3: JWTs use email address as the primary method to identify a user. This makes step 2 involve no guesswork at all. If you know someone has session, you can just build the correctly formed JWT and BE them.

Solution: Use database user ids in the JWT instead.

### CODE REVIEW

**Comment by Collected5353** [comment]
These are good changes. It should have a disclaimer in the docs somewhere this shouldn't be public-facing without some waf or proxy in front of it.

**Comment by explorigin** [comment]
> These are good changes. It should have a disclaimer in the docs somewhere this shouldn't be public-facing without some waf or proxy in front of it.

I disagree. I think we should be careful putting too much into the project. We should not have to explain all the tenants of web security in our documentation. It's out of scope.

I already feel like we explain too much how to get docker up and running. It's all out-of-scope (or should be).

**Comment by justinh-rahb** [comment]
> I disagree. I think we should be careful putting too much into the project. We should not have to explain all the tenants of web security in our documentation.
> 
> I already feel like we explain too much how to get docker up and running. It's all out-of-scope (or should be).

I couldn't agree more, I'd much rather we focus on issues pertaining to the project itself, not its methods of deployment or operation in production (if you're doing that, you should know what you're doing).

**Comment by Collected5353** [comment]
We should at least post the current OSSF scorecard so users can make their own decisions. 

Aggregate score: 5.2 / 10

Check scores:
|---------|------------------------|--------------------------------|-----------------------------------------------------------------------------------------------------------------------|
|  SCORE  |          NAME          |             REASON             |                                               DOCUMENTATION/REMEDIATION                                               |
|---------|------------------------|--------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| 10 / 10 | Binary-Artifacts       | no binaries found in the repo  | https://github.com/ossf/scorecard/blob/ba69f1346b6f2bc833b7c8e2e96123a35fb1da4c/docs/checks.md#binary-artifacts       |
|---------|------------------------|--------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| 3 / 10  | Branch-Protection      | branch protection is not       | https://github.com/ossf/scorecard/blob/ba69f1346b6f2bc833b7c8e2e96123a35fb1da4c/docs/checks.md#branch-protection      |
|         |                        | maximal on development and all |                                                                                                                       |
|         |                        | release branches               |                                                                                                                       |
|---------|------------------------|--------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| 9 / 10  | CI-Tests               | 12 out of 13 merged PRs        | https://github.com/ossf/scorecard/blob/ba69f1346b6f2bc833b7c8e2e96123a35fb1da4c/docs/checks.md#ci-tests               |
|         |                        | checked by a CI test -- score  |                                                                                                                       |
|         |                        | normalized to 9                |                                                                                                                       |
|---------|------------------------|--------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| 0 / 10  | CII-Best-Practices     | no effort to earn an OpenSSF   | https://github.com/ossf/scorecard/blob/ba69f1346b6f2bc833b7c8e2e96123a35fb1da4c/docs/checks.md#cii-best-practices     |
|         |                        | best practices badge detected  |                                                                                                                       |
|---------|------------------------|--------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| 3 / 10  | Code-Review            | found 8 unreviewed changesets  | https://github.com/ossf/scorecard/blob/ba69f1346b6f2bc833b7c8e2e96123a35fb1da4c/docs/checks.md#code-review            |
|         |                        | out of 13 -- score normalized  |                                                                                                                       |
|         |                        | to 3                           |                                                                                                                       |
|---------|------------------------|--------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| 10 / 10 | Contributors           | project has 29 contributing    | https://github.com/ossf/scorecard/blob/ba69f1346b6f2bc833b7c8e2e96123a35fb1da4c/docs/checks.md#contributors           |
|         |                        | companies or organizations     |                                                                                                                       |
|---------|------------------------|--------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| 10 / 10 | Dangerous-Workflow     | no dangerous workflow patterns | https://github.com/ossf/scorecard/blob/ba69f1346b6f2bc833b7c8e2e96123a35fb1da4c/docs/checks.md#dangerous-workflow     |
|         |                        | detected                       |                                                                                                                       |
|---------|------------------------|--------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| 0 / 10  | Dependency-Update-Tool | no update tool detected        | https://github.com/ossf/scorecard/blob/ba69f1346b6f2bc833b7c8e2e96123a35fb1da4c/docs/checks.md#dependency-update-tool |
|---------|------------------------|--------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| 0 / 10  | Fuzzing                | project is not fuzzed          | https://github.com/ossf/scorecard/blob/ba69f1346b6f2bc833b7c8e2e96123a35fb1da4c/docs/checks.md#fuzzing                |
|---------|------------------------|--------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| 10 / 10 | License                | license file detected          | https://github.com/ossf/scorecard/blob/ba69f1346b6f2bc833b7c8e2e96123a35fb1da4c/docs/checks.md#license                |
|---------|------------------------|--------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| 10 / 10 | Maintained             | 30 commit(s) and 0 issue       | https://github.com/ossf/scorecard/blob/ba69f1346b6f2bc833b7c8e2e96123a35fb1da4c/docs/checks.md#maintained             |
|         |                        | activity found in the last 90  |                                                                                                                       |
|         |                        | days -- score normalized to 10 |                                                                                                                       |
|---------|------------------------|--------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| 10 / 10 | Packaging              | packaging workflow detected    | https://github.com/ossf/scorecard/blob/ba69f1346b6f2bc833b7c8e2e96123a35fb1da4c/docs/checks.md#packaging              |
|---------|------------------------|--------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| 0 / 10  | Pinned-Dependencies    | dependency not pinned by hash  | https://github.com/ossf/scorecard/blob/ba69f1346b6f2bc833b7c8e2e96123a35fb1da4c/docs/checks.md#pinned-dependencies    |
|         |                        | detected -- score normalized   |                                                                                                                       |
|         |                        | to 0                           |                                                                                                                       |
|---------|------------------------|--------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| 0 / 10  | SAST                   | SAST tool is not run on all    | https://github.com/ossf/scorecard/blob/ba69f1346b6f2bc833b7c8e2e96123a35fb1da4c/docs/checks.md#sast                   |
|         |                        | commits -- score normalized to |                                                                                                                       |
|         |                        | 0                              |                                                                                                                       |
|---------|------------------------|--------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| 4 / 10  | Security-Policy        | security policy file detected  | https://github.com/ossf/scorecard/blob/ba69f1346b6f2bc833b7c8e2e96123a35fb1da4c/docs/checks.md#security-policy        |
|---------|------------------------|--------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| ?       | Signed-Releases        | no releases found              | https://github.com/ossf/scorecard/blob/ba69f1346b6f2bc833b7c8e2e96123a35fb1da4c/docs/checks.md#signed-releases        |
|---------|------------------------|--------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| 0 / 10  | Token-Permissions      | detected GitHub workflow       | https://github.com/ossf/scorecard/blob/ba69f1346b6f2bc833b7c8e2e96123a35fb1da4c/docs/checks.md#token-permissions      |
|         |                        | tokens with excessive          |                                                                                                                       |
|         |                        | permissions                    |                                                                                                                       |
|---------|------------------------|--------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| 9 / 10  | Vulnerabilities        | 1 existing vulnerabilities     | https://github.com/ossf/scorecard/blob/ba69f1346b6f2bc833b7c8e2e96123a35fb1da4c/docs/checks.md#vulnerabilities        |
|         |                        | detected                       |                                                                                                                       |
|---------|------------------------|--------------------------------|-----------------------------------------------------------------------------------------------------------------------|

**Comment by explorigin** [comment]
@Collected5353 I appreciate that you seem very concerned about security. If you feel like the security scorecard would be valuable to add, please create a PR for it. While this current PR would likely change its how the project is scored, it is not relevant to this specific PR and I thus do not wish to include it here.

**Comment by Collected5353** [comment]
Oh yeah I wasn't saying to make it apart of this PR, just a general comment.

**Comment by tjbck** [comment]
LGTM, Thanks for the hard work!

**Pull request merged**
