### PR TITLE
Feature/support auth by api key

### PR DESCRIPTION
**Pull request by vaayne**
## Pull Request Checklist

- [x] **Description:** Briefly describe the changes in this pull request.
- [ ] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation?
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?

---

## Description

Support creation of API keys for authentication purposes, allowing users to utilize them with our API of [LiteLLM OpenAI Proxy Service](https://litellm.vercel.app/docs/proxy/quick_start)

image

### Example Usage
```python
from openai import OpenAI
from rich import print

BASE_URL = "http://localhost:18080/litellm/api/v1"

TOKEN = "sk-89ca1254569345f5b00d3d9b80b2d174"
MODEL = "bedrock-claude-3-haiku"

oai = OpenAI(
    api_key=TOKEN,
    base_url=BASE_URL,
)

resp = oai.chat.completions.create(
    stream=True,
    messages=[{"role": "user", "content": "What is the meaning of life?"}],
    model=MODEL,
)

for message in resp:
    content = message.choices[0].delta.content
    if not content:
        continue
    print(content, end="")
print()
```

---

### Added

- create API Key in frontend
- auth by api key

### Fixed

- [List any fixes or corrections]

### Changed

- [List any changes or updates]

### Removed

- [List any removed features or files]

### CODE REVIEW

**Comment by justinh-rahb** [comment]
Oh I'm loving this idea, thoughts @tjbck?

**Comment by tjbck** [comment]
This is amazing! I'll review in a bit!

**Comment by tjbck** [comment]
LGTM, Thanks!

**Comment by changchiyou** [comment]
> Support creation of API keys for authentication purposes, allowing users to utilize them with our API of [LiteLLM OpenAI Proxy Service](https://litellm.vercel.app/docs/proxy/quick_start)

⬆️ How this works? Can't find any related-info from https://docs.openwebui.com/tutorial/litellm or `README.md`.

**Comment by vaayne** [comment]
> > Support creation of API keys for authentication purposes, allowing users to utilize them with our API of [LiteLLM OpenAI Proxy Service](https://litellm.vercel.app/docs/proxy/quick_start)
> 
> 
> 
> ⬆️ How this works? Can't find any related-info from https://docs.openwebui.com/tutorial/litellm or `README.md`.


Here's an improved version of the writing:

The Litellm system has a master key, but we don't utilize it in this project. Before obtaining an API key, authentication was only available through JWT tokens in the project. In this pull request, I've added a persistent API key. This allows users who want to access the APIs provided by Litellm to use the API key, which will function similarly to the master key within the Litellm.

**Comment by vaayne** [comment]
@changchiyou this PR simply offers an alternative method for authorizing with open-webui

**Pull request merged**
