### PR TITLE
fix : Optimize get_all_models Function by Adding Caching for Improved Performance

### PR DESCRIPTION
**Pull request by ssnnow**
# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [ ] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [x] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [ ] **Testing:** Have you written and run sufficient tests for validating the changes?
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [x] **Prefix:** To cleary categorize this pull request, prefix the pull request title, using one of the following:
  - **BREAKING CHANGE**: Significant changes that may affect compatibility
  - **build**: Changes that affect the build system or external dependencies
  - **ci**: Changes to our continuous integration processes or workflows
  - **chore**: Refactor, cleanup, or other non-functional code changes
  - **docs**: Documentation update or addition
  - **feat**: Introduces a new feature or enhancement to the codebase
  - **fix**: Bug fix or error correction
  - **i18n**: Internationalization or localization changes
  - **perf**: Performance improvement
  - **refactor**: Code restructuring for better maintainability, readability, or scalability
  - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
  - **test**: Adding missing tests or correcting existing tests
  - **WIP**: Work in progress, a temporary label for incomplete or ongoing work

# Changelog Entry

### Description

- Implementing caching within the get_all_models function is expected to reduce processing time for repeated calls, thereby enhancing the responsiveness and scalability of our application.

### Changed

- [List any changes, updates, refactorings, or optimizations]
- optimizations  backend performance

---

### Additional Information

- [Insert any additional context, notes, or explanations for the changes]
  - [Reference any related issues, commits, or other relevant information]

### Screenshots or Videos

- [Attach any relevant screenshots or videos demonstrating the changes]

### CODE REVIEW

**Comment by kaiiiiiiiii** [comment]
Awesome! I'm loosing 6 seconds of my life, every time I open the ui. Would be handy to have the cache time configurable, because I don't need model refreshes every 10 minutes. Once a day is totally fine imho.

**Comment by thiswillbeyourgithub** [comment]
Does that mean that if I'm coding a pipe or pipeline, I won't see it updated for 10 minutes ? Same for ollama (i'm using my own separate container). I support @kaiiiiiiiii 's idea to add an env variable to make the cache duration customizable.

**Review by RahulVadisetty91 — COMMENTED** [review]
Implement more granular exception handling and better logging.

try:
    # Code block
except KeyError as e:
    log.error(f"KeyError occurred: {e}")
    raise
except ValueError as e:
    log.error(f"ValueError occurred: {e}")
    raise
except Exception as e:
    log.error(f"Unexpected error: {e}")
    raise

By the way all are good.

**Comment by tjbck** [comment]
indeed, the default needs to be no cache, config option should be exposed as an env var here!

**Comment by tjbck** [comment]
Closing due to conflicts, feel free to reopen!

**Pull request closed without merging**
