### PR TITLE
Updated Chinese translation

### PR DESCRIPTION
**Pull request by karllee830**
# Pull Request Checklist

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.

# Changelog Entry

### Description

Updated Chinese translation for version 0.2.4.
Fix some translation errors.

### CODE REVIEW

**Comment by KarlLee830** [comment]
I would like to address PR https://github.com/open-webui/open-webui/pull/2744. The Chinese translation within this PR contains numerous basic translation errors. Some of the errors mentioned in PR https://github.com/open-webui/open-webui/pull/2792 regarding Turkish translations have also appeared identically in the Chinese translation. These mistakes are so conspicuous that a single reading of the file would make them apparent. As a native Chinese speaker, why would @Yanyutin753 submit translations that contain such evident errors? Moreover, PR 2744 has overridden many high-quality translations. I urge everyone to refrain from submitting these low-quality translations, or ensure that these PRs are reviewed by actual human reviewers.

**Comment by Yanyutin753** [comment]
Ah, your suggestion is really good, I have found some errors, but all the translations, I only translate the vacant, and wrote a function, calling azure API 3.0 for translation, may indeed have some problems, I feel very sorry for this

**Comment by justinh-rahb** [comment]
> I would like to address PR #2744. The Chinese translation within this PR contains numerous basic translation errors. Some of the errors mentioned in PR #2792 regarding Turkish translations have also appeared identically in the Chinese translation. These mistakes are so conspicuous that a single reading of the file would make them apparent. As a native Chinese speaker, why would @Yanyutin753 submit translations that contain such evident errors? Moreover, PR 2744 has overridden many high-quality translations. I urge everyone to stop submitting these low-quality translations because they make the content even harder to understand compared to the original English version. We should prioritize the quality of translations over speed.

I've given it some thought and I do believe we need a new process/workflow for handling translation submissions, as you're right, at the moment we get far too many instances of perfectly fine previous PRs being overwritten with lesser-quality machine-translation slop. This is not the standard we want.

**Comment by KarlLee830** [comment]
> > I would like to address PR #2744. The Chinese translation within this PR contains numerous basic translation errors. Some of the errors mentioned in PR #2792 regarding Turkish translations have also appeared identically in the Chinese translation. These mistakes are so conspicuous that a single reading of the file would make them apparent. As a native Chinese speaker, why would @Yanyutin753 submit translations that contain such evident errors? Moreover, PR 2744 has overridden many high-quality translations. I urge everyone to stop submitting these low-quality translations because they make the content even harder to understand compared to the original English version. We should prioritize the quality of translations over speed.
> 
> I've given it some thought and I do believe we need a new process/workflow for handling translation submissions, as you're right, at the moment we get far too many instances of perfectly fine previous PRs being overwritten with lesser-quality machine-translation slop. This is not the standard we want.

Perhaps crowdin.com is a good choice. I've translated some fairly large projects on Crowdin, and overall the experience has been quite positive.

**Comment by tjbck** [comment]
Thanks!

**Pull request merged**
