### PR TITLE
Migrate to python logging module with env var control.

### PR DESCRIPTION
**Pull request by ghost**
## Pull Request Checklist

- [X] **Description:** Briefly describe the changes in this pull request.
- [X] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation?
- [X] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?

---

## Description

Introduce Python `logging` and migrate all `print()` statements to it. To mirror current functionality, logging doesn't use a file, only `sys.stdout`. A global var `GLOBAL_LOG_LEVEL` and any of following like `OLLAMA_LOG_LEVEL=DEBUG` can be set: `log_sources = ["AUDIO", "CONFIG", "DB", "IMAGES", "LITELLM", "MAIN", "MODELS", "OLLAMA", "OPENAI", "RAG"]`. Note that this is additionally beneficial as it affects any 3rd party imports that use the Python logging module including LITELLM.

---

### Changelog Entry
First commit

### Added

- Introduce Python `import logging` functionality.

### Fixed

- Sensitive log items like the POST data and password hash now require DEBUG logging. Default is INFO.

### Changed

- Everywhere using `print()`

### Removed

- Replaced `print()` statements with `log.` statements.

### CODE REVIEW

**Comment by tjbck** [comment]
Let's take this PR up a notch and include more logging statements where it's needed, contribution welcome!

**Comment by lainedfles** [comment]
Can you clarify "_where it's needed_"? Did I miss some print statements? How else can I help? Thanks!

**Comment by tjbck** [comment]
> In my own testing I have been able to use the regular chat functionality with text input just fine, but I hit an issue with the document upload / RAG functionality: on attempting to upload a document I experience a 500 status code from the server but am not clear how I would be able to debug this further short of starting to add debug log statements, track trace output in myself. Am I missing a debug facility I should just turn on?

One comment from: https://github.com/open-webui/open-webui/pull/724

They're really optional and nice-to-haves, so we could merge this PR first and then start adding more logging statements.

**Comment by tjbck** [comment]
Merging this for now, let's continue our discussion here: #1282 Thanks!

**Pull request merged**
