### PR TITLE
patches from npm security audit

### PR DESCRIPTION
**Pull request by nightness**
## Description
Security update of packages provided by "npm audit fix"

```
(base) nightness@Mac-mini open-webui % npm i

added 299 packages, and audited 300 packages in 5s

65 packages are looking for funding
  run `npm fund` for details

3 vulnerabilities (2 low, 1 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
(base) nightness@Mac-mini open-webui % npm audit
# npm audit report

undici  <=5.28.2
Undici proxy-authorization header not cleared on cross-origin redirect in fetch - https://github.com/advisories/GHSA-3787-6prv-h9w3
fix available via `npm audit fix`
node_modules/undici
  @sveltejs/kit  1.0.0-next.0 - 1.30.3
  Depends on vulnerable versions of undici
  node_modules/@sveltejs/kit

vite  4.0.0 - 4.5.1
Severity: high
Vite dev server option `server.fs.deny` can be bypassed when hosted on case-insensitive filesystem - https://github.com/advisories/GHSA-c24v-8rfc-w8vw
fix available via `npm audit fix`
node_modules/vite

3 vulnerabilities (2 low, 1 high)

To address all issues, run:
  npm audit fix

(base) nightness@Mac-mini open-webui % npm audit fix

changed 4 packages, and audited 300 packages in 6s

65 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

---

### Changelog Entry
package-lock.json modified

### Changed
package-lock.json modified

### CODE REVIEW

**Comment by nightness** [comment]
The versions updated themselves after `npm i`

**Comment by justinh-rahb** [comment]
It should be noted that the Docker builds shouldn't be affected by this since we do a clean npm install which should get the latest versions.

**Comment by nightness** [comment]
> It should be noted that the Docker builds shouldn't be affected by this since we do a clean npm install which should get the latest versions.

A "clean install" is not what you think it is. It doesn't update versions, it always installs the versions in package-lock.json...

Since the docker image has the same package-lock.json, it will have the same problem... From the Dockerfile...
```
COPY package.json package-lock.json ./
RUN npm ci
```

**Comment by nightness** [comment]
The best solution is not to commit package-lock.json, it is a generated file. Let it be generated.

**Comment by justinh-rahb** [comment]
> The best solution (IMHO) is not to commit package-lock.json, it is a generated file. Let it be generated.

Good idea, may as well add that to the `.gitignore` in your PR to fix this properly.

**Comment by justinh-rahb** [comment]
Ultimately up to maintainer's approval but IMO you're right, this is cleaner.

**Comment by nightness** [comment]
> > The best solution (IMHO) is not to commit package-lock.json, it is a generated file. Let it be generated.
> 
> Good idea, may as well add that to the `.gitignore` in your PR to fix this properly.
> 
> If a change is needed to the `Dockerfile`, I'd suggest commenting on the ongoing PR about optimizing it:
> 
> * [refac: Dockerfile #1165](https://github.com/open-webui/open-webui/pull/1165)

I've removed the lock files package-lock.json and bun.lockb from the repo. I still want to do a Docker build to test, but I need to do that on a my other computer; as I don't run Docker on my 8GB Ram Mac Mini.  I'll have a look at that PR too.

**Comment by tjbck** [comment]
Thanks for the PR but the security audit fix has already been introduce in our dev branch!

**Pull request closed without merging**
