### PR TITLE
feat: show RAG query results as citations

### PR DESCRIPTION
**Pull request by cheahjs**
## Pull Request Checklist

- [x] **Description:** Briefly describe the changes in this pull request.
- [ ] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [ ] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [x] **Testing:** Have you written and run sufficient tests for the changes?
- [ ] **Code Review:** Have you self-reviewed your code and addressed any coding standard issues?

---

## Description

Return RAG query results as citations to show to the user. This is done by injecting a new event/object into the streaming responses in the RAG middleware, and handling this on the frontend. To avoid breaking external clients, this is an opt-in behaviour with `citations: true`.

Some open questions:

1. Right now the file loaders use the full file path as the source for metadata, do we want to sanitize this before returning it?
2. Web loader has more metadata such as a title and description, do we want to use any of these bits of metadata?
3. ~~This is currently not working correctly with collections, as a collection can return multiple documents with different sources in a single query.~~ Code was updated to group by source instead of grouping by collections.

image
image

---

### Added

- **📚 Citations for RAG Responses**: Get source information for responses generated using Retrieval Augmented Generation (RAG). This helps you understand the context and origin of the information provided.

### CODE REVIEW

**Comment by Yanyutin753** [comment]
it is so great

**Comment by jannikstdl** [comment]
Long awaited feature 🚀

Looks good so far, maybe it is possible to make the source path clickable to open the actual file.

**Comment by Yanyutin753** [comment]
Yes, I think so too. Is it possible to open all uploaded pictures and files with a single click? This is also one of the expected features

**Comment by tjbck** [comment]
Amazing work 🙌 LGTM!

**Pull request merged**
