### PR TITLE
Adding Qdrant 

### PR DESCRIPTION
**Pull request by mkhludnev**
## Pull Request Checklist

- [x] **Target branch:** Pull requests should target the `dev` branch. 
- [ ] **Description:** Introducing Qdrant vectorstore
- [ ] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [ ] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [x] **Testing:** Have you written and run sufficient tests for the changes?
- [ ] **Code Review:** Have you self-reviewed your code and addressed any coding standard issues?

---

## Description

It introduces Qdrant as alternative to Chroma. Beforehand it abstract Chroma under VectorStore. 

---

### Added

- Qdrant vector store

### Fixed

- [List any fixes, corrections, or bug fixes]

### Changed

- [List any changes, updates, refactorings, or optimizations]

### Removed

- [List any removed features, files, or deprecated functionalities]

### Security

- [List any new or updated security-related changes, including vulnerability fixes]

### Breaking Changes

- [List any breaking changes affecting compatibility or functionality]

---

### Additional Information

- [Insert any additional context, notes, or explanations for the changes]

- [Reference any related issues, commits, or other relevant information]

### CODE REVIEW

**Comment by mkhludnev** [comment]
Just want to show what I'm up to. 

1. Is introducing Qdrant makes any sense at all?
2. wdyt re approach taken?
3. is there a tests I can use for covering this?

Once again, it's incomplete. What to get some feedback in the beginning.

**Comment by tjbck** [comment]
We might want this to be added as a pipeline instead of adding Qdrant directly to the main webui project. https://github.com/open-webui/pipelines

**Comment by tjbck** [comment]
Closing in favour of https://github.com/open-webui/pipelines/issues/9

**Comment by tjbck** [comment]
@mkhludnev not yet supported but I'll be adding all the custom hooked need to enable such interactions!

**Pull request closed without merging**
