### PR TITLE
feat: ✨ bun support, backend lint, frontend & backend CI

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
- Adds bun support
- Changes default commands to use bun
- Adds formatting and linting for backend
- Moves frontend CI to Bun
- Adds backend CI

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
Disabled CI linting for now due to many lint failures

**Comment by ThatOneCalculator** [comment]
Lint jobs are expected to fail for both FE & BE

**Comment by ThatOneCalculator** [comment]
CI now behaves as expected

**Comment by tjbck** [comment]
Is there a way to disable frontend/backend lint for now? Also facing this issue when building docker image locally:
image

**Comment by ThatOneCalculator** [comment]
Lint disabled. What command are you running for the dockerfile?

**Comment by tjbck** [comment]
Using `docker build -t ollama-webui .`!

**Comment by tjbck** [comment]
Seems like it might be related to: https://github.com/oven-sh/bun/issues/5162

**Comment by ThatOneCalculator** [comment]
Fixed!

**Comment by tjbck** [comment]
image
Another error :/

**Comment by ThatOneCalculator** [comment]
Are you sure you pulled? I can't repro that.

**Comment by tjbck** [comment]
Yep, `bun install --lockfile` replaced with `bun install` no?

**Comment by ThatOneCalculator** [comment]
Yeah, deleted since it was being weird for a second. Working now.

image

**Pull request merged**
