### PR TITLE
feat: Add OAuth Email Claim Variable

### LINKED ISSUE #4435: Add environment variable to specify OAuth Email Claim
**Is your feature request related to a problem? Please describe.**

I'm currently using Microsoft Entra ID as my OAuth provider but Entra does not reliably return user emails in the `email` claim of the OAuth ID token. Some users in my environment do not have the email field set but instead have the email returned in the `preferred_username` or `username` claims.

As a result, when a user who does not have the email claim tries to login, the logs show `OAuth callback failed, email is missing` and the user is redirected to an API page listing `The email or password provided is incorrect. Please check for typos and try logging in again.`

**Describe the solution you'd like**

To more widely support different OAuth configurations, environment variables should be added similar to `OAUTH_USERNAME_CLAIM` allowing users to specify an alternative email claim, such as `OAUTH_EMAIL_CLAIM` and/or `MICROSOFT_EMAIL_CLAIM`.

This should be pretty straightforward, only need to define the variable(s) in [backend/config.py](https://github.com/open-webui/open-webui/tree/99d10d1189452ad49fcace219e9c90ae65906cd1/backend/config.py) and change [line 2161 of main.py](https://github.com/open-webui/open-webui/blob/99d10d1189452ad49fcace219e9c90ae65906cd1/backend/main.py#L2161) to something like this:

```
email_claim = webui_app.state.config.OAUTH_EMAIL_CLAIM
email = user_data.get(email_claim, "")
```

I'm happy to open a PR as well.

**Describe alternatives you've considered**

Alternatively, for the Microsoft auth provider, it could check for the `preferred_username` claim and fall back to that value if the `email` claim doesn't exist.

### PR DESCRIPTION
**Pull request by cdgco**
Add an `OAUTH_EMAIL_CLAIM` variable to override the default "email" claim value.

# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [x] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [x] **Testing:** Have you written and run sufficient tests for validating the changes?
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [x] **Prefix:** To cleary categorize this pull request, prefix the pull request title, using one of the following:
  - **BREAKING CHANGE**: Significant changes that may affect compatibility
  - **build**: Changes that affect the build system or external dependencies
  - **ci**: Changes to our continuous integration processes or workflows
  - **chore**: Refactor, cleanup, or other non-functional code changes
  - **docs**: Documentation update or addition
  - **feat**: Introduces a new feature or enhancement to the codebase
  - **fix**: Bug fix or error correction
  - **i18n**: Internationalization or localization changes
  - **perf**: Performance improvement
  - **refactor**: Code restructuring for better maintainability, readability, or scalability
  - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
  - **test**: Adding missing tests or correcting existing tests
  - **WIP**: Work in progress, a temporary label for incomplete or ongoing work

# Changelog Entry

### Description
- The current OAuth implementation uses `email` as the value for the OAuth email claim, while some providers use alternative claims in their ID tokens. Users can now override this value to specify an alternative claim containing the user's email address.

### Added
- Added `OAUTH_EMAIL_CLAIM` variable to override default claim value.

---

Closes #4435

### CODE REVIEW

**Comment by cdgco** [comment]
PR for documentation update here: https://github.com/open-webui/docs/pull/173

**Review by justinh-rahb — APPROVED** [review]

**Comment by tjbck** [comment]
LGTM, Thanks!

**Comment by luochen1990** [comment]
WARNING:main:OAuth callback failed, email is missing: {'exp': 1724223293, 'iat': 1724222993, 'auth_time': 1724220961, ... , 'acr': '0', 'email_verified': True, 'preferred_username': 'luochen1990@gmail.com', 'email': 'luochen1990@gmail.com'}

**Comment by luochen1990** [comment]
Maybe it will be better to also print the OAUTH_EMAIL_CLAIM variable when error occurs

**Pull request merged**
