### PR TITLE
Refactor docker-compose configuration for modularity

### PR DESCRIPTION
**Pull request by gnscc**
Split the original docker-compose.yml into three separate files for enhanced modularity and ease of use. Created docker-compose.api.yml for API exposure configuration and docker-compose.gpu.yml for GPU support. This change simplifies the management of different deployment environments and configurations, making it easier to enable or disable specific features such as GPU support and API access without modifying the main docker-compose file.

Additionally, this separation ensures that personal or environment-specific configurations do not affect the main docker-compose file, thus avoiding unnecessary changes in Git tracking. This means that switching between different configurations (e.g., with or without GPU support) won't lead to modifications in tracked files, keeping the Git history cleaner and more focused on meaningful changes.

### CODE REVIEW

**Comment by moDal7** [comment]
As a recent user, while trying to do this I also thought it could be better to split the docker .yaml file this way.

**Comment by justinh-rahb** [comment]
mustgofaster
Screenshot 2023-12-23 at 12 50 08 AM

**Comment by tjbck** [comment]
Hi @gnscc, Thanks for your PR! I think we should have a separate section for enabling gpu and another section for exposing api in the doc for better clarity, but otherwise LGTM!

**Comment by gnscc** [comment]
Hey @tjbck, thank you for your feedback. Following your suggestion I have updated the README with a section for each option.

**Comment by tjbck** [comment]
LGTM, Thanks a lot!

**Pull request merged**
