### PR TITLE
feat: Typesafety

### PR DESCRIPTION
**Pull request by Carlos-err406**
addresses issue #944 
---

## Description
added typescript types and interfaces

---

### Added
- lib/types/*

### Fixed

- [List any fixes or corrections]

### Changed

- [List any changes or updates]

### Removed

- [List any removed features or files]

### CODE REVIEW

**Comment by justinh-rahb** [comment]
Doesn't appear as though any work was done in a couple weeks here. Are you still hoping to merge this @Carlos-err406?

**Comment by Carlos-err406** [comment]
> Doesn't appear as though any work was done in a couple weeks here. Are you still hoping to merge this @Carlos-err406?

yes, i've jus been quite busy lately
any help would be appreciated though

**Comment by justinh-rahb** [comment]
No worries, just checking in on all the extant branches, hoping we can get the queue of PRs shortened :)

**Comment by Carlos-err406** [comment]
I regret to inform that Im unable to continue managing the ongoing updates to the repository independently. Therefore, decided to close this PR. If anyone is interested in taking over, would greatly appreciate it. Thanks for understanding.

**Pull request closed without merging**
