### PR TITLE
feat: external db reconnect

### PR DESCRIPTION
**Pull request by perfectra1n**
# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

**Before submitting, make sure you've checked the following:**

- [ ] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [ ] **Description:** Provide a concise description of the changes made in this pull request.
- [ ] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [ ] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [ ] **Testing:** Have you written and run sufficient tests for validating the changes?
- [ ] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [ ] **Prefix:** To cleary categorize this pull request, prefix the pull request title, using one of the following:
  - **BREAKING CHANGE**: Significant changes that may affect compatibility
  - **build**: Changes that affect the build system or external dependencies
  - **ci**: Changes to our continuous integration processes or workflows
  - **chore**: Refactor, cleanup, or other non-functional code changes
  - **docs**: Documentation update or addition
  - **feat**: Introduces a new feature or enhancement to the codebase
  - **fix**: Bug fix or error correction
  - **i18n**: Internationalization or localization changes
  - **perf**: Performance improvement
  - **refactor**: Code restructuring for better maintainability, readability, or scalability
  - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
  - **test**: Adding missing tests or correcting existing tests
  - **WIP**: Work in progress, a temporary label for incomplete or ongoing work

# Changelog Entry

### Description

This builds off of #2666 that refused to cooperate with SQLite. Now the backend should automatically attempt to reconnect with the SQLite or Postgres DBs if the connection is dropped.

### CODE REVIEW

**Comment by RobinBia** [comment]
Not needed because of this: #3228. It's already in development.

**Comment by justinh-rahb** [comment]
> Not needed because of this: #3228. It's already in development.

As of the last time I tested it, that earlier PR did not work properly if you were using the default SQLite database. I'll test this one later today when I have time to see if it addresses that issue.

**Comment by perfectra1n** [comment]
@justinh-rahb, the PR that @RobinBially excellently delivered was open ~5 hours ago (#3228). I believe you might be mistaking it for #2666.

**Comment by justinh-rahb** [comment]
> @justinh-rahb, the PR that @RobinBially excellently delivered was open ~5 hours ago (#3228). I believe you might be mistaking it for #2666.

You're correct. I blame insufficient supply of caffeine

**Comment by perfectra1n** [comment]
> > @justinh-rahb, the PR that @RobinBially excellently delivered was open ~5 hours ago (#3228). I believe you might be mistaking it for #2666.
> 
> You're correct. I blame insufficient supply of caffeine

It's all good! I'm just hoping one of these 3 PRs pan out for open-webui. Good luck caffeinating further :)

**Comment by perfectra1n** [comment]
Should be good to go now, verified it locally for both Postgres and SQLite. Tried on both completely new databases, and previously existing ones. Waited 15 minutes between new queries, repeated 3x times. Seems like it's finally working 🎉

**Review by Peter-De-Ath — APPROVED** [review]
I can't seem to break it.

Running with postgres database, I can now restart postgres and it no long requires to restart open-webui.

Running with SQLite localfile I can remove the database, It will attempt to create a new one, but if i replace it with the original it continues as expected.

Running with SQLite over a network connection i can break the connection and open-webui work once restored.

**Comment by perfectra1n** [comment]
> I can't seem to break it.
> 
> Running with postgres database, I can now restart postgres and it no long requires to restart open-webui.
> 
> Running with SQLite localfile I can remove the database, It will attempt to create a new one, but if i replace it with the original it continues as expected.
> 
> Running with SQLite over a network connection i can break the connection and open-webui work once restored.

That's great to hear! 💪

**Comment by tjbck** [comment]
hell yeah brother

**Comment by tjbck** [comment]
let's gooooo

**Pull request merged**
