### PR TITLE
**feat**: Artifacts

### PR DESCRIPTION
**Pull request by atgehrhardt**
# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.
- I am skipping this as I have contributed to Pipelines and this has been discussed in detail in the Discord :)

# Changelog Entry

### Description

- This makes minor changes to existing components to allow for adding a new modal for the Artifacts feature. The main addition here is the actual Artifacts modal which parses all messages in the currently open chat, extracts code from those messages where possible and renders that code. If you open the modal you can see all renders. 

This does not create actual artifacts or store the code. When the chat is deleted, the code is gone as it is simply live rendering parsed code.

### Added

- New Artifacts feature for rendering HTML, CSS, and JavaScript content from chat messages
      - Added ArtifactsModal.svelte component for displaying rendered content
      - Implemented artifact rendering in full view and preview mode
      - Added support for responsive, mobile, and desktop viewing modes
- New "Artifacts" button in the sidebar for accessing the Artifacts modal
- showArtifacts store for managing the visibility of the Artifacts modal

### Changed

- Updated Chat.svelte to include the new ArtifactsModal component
- Modified Messages.svelte to handle chat actions related to artifacts
- Enhanced Sidebar.svelte with a new Artifacts button and associated SVG icon
- Updated +layout.svelte to incorporate the ArtifactsModal in the app layout

### Deprecated

- N/A

### Removed

- N/A

### Fixed

- N/A

### Security

- Adding the ability to render code in this manner opens up users to malicious code injection via an LLM. The long term goal is to implement a proper sandbox within OWUI and have the iframe simple render that (so the core code shouldn't change much if at all). For now, this should be safe enough for most users, but if they were to use an LLM capable of generating malicious javascript, it WOULD execute said code in the modal.

### Breaking Changes

- N/A

---

### Additional Information

- I'm Unsaidpaper from the Discord
- I would be happy to split this into Atomics, but 90% of this PR is simply a new file. The changes are quite minor mostly imports to the other files save for Sidebar.svelte in which I simply added a new button. I can split this into two if you would prefer. One for the changes and one for the new file.
- This is a brand new implementation of Artifacts and while I also wrote the Artifacts function on the community site, these two implementations actually have very little in common.

### Screenshots or Videos

https://github.com/user-attachments/assets/90afd126-bb3f-44ed-9bfc-8d8744c43118

### CODE REVIEW

**Comment by michaelpoluektov** [comment]
I'm slightly concerned about the security section: with a web search tool, a prompt injection attack, and a model not equipped to handle it, this could lead to bad things. 

There are functions that are much worse (such as the "calculator" tool that just runs `eval` on the backend) but if we're going to build this in by default there should at least be a flag to disable it until it's sandboxed properly.

**Comment by atgehrhardt** [comment]
@tjbck should I split this into atomics?

The feature in its current state is ready for review.

Was just getting an odd CI issue due to missing imports that don't actually conflict with the source files.

**Comment by atgehrhardt** [comment]
Ready for review. Still planning to add global toggle in next version to allow disabling or enabling Artifacts from Settings

**Comment by evolu8** [comment]
Any hold ups still on this. It will be a game changing feature. 

Thanks for your efforts guys.

**Comment by peuportier** [comment]
Yes will be a game changer, Especially if the model via tools can call it automatically and generate like pie chart or else chart. Mermaid is good but can't do this kind of graphic chart that maybe this can show using javascript and html .Super good job

**Comment by tjbck** [comment]
Closing in favour of de59ecf8a33a9eb26a8d75ab2f5c17aa4e04c15d

**Pull request closed without merging**
