### PR TITLE
Increase-Context-Length

### PR DESCRIPTION
**Pull request by notasquid1938**
Changed max context length slider to go up to 256K now that certain models support that.

I originally posted this as a feature request #1837 and then realized it's just changing two numbers.

### CODE REVIEW

**Comment by tjbck** [comment]
Closing this PR but updated the token length limit to 1024000!

**Comment by Silentoplayz** [comment]
> Closing this PR but updated the token length limit to 1024000!

Go big or go home! 🤣

**Comment by notasquid1938** [comment]
> Closing this PR but updated the token length limit to 1024000!

Looks like another model just dropped:
 https://huggingface.co/gradientai/Llama-3-8B-Instruct-Gradient-1048k
 The context limit needs to be increased to 1048576 (Or maybe add an option for the user to set it as high as they want to avoid constantly increasing it?)

**Comment by tjbck** [comment]
Removed the limit for the number input field!

**Pull request closed without merging**
