### PR TITLE
Enhance Docker Build Efficiency

### PR DESCRIPTION
**Pull request by justinh-rahb**
This pull request introduces a significant enhancement to our Dockerfile and associated `start.sh` script by transitioning to `uv`, a cutting-edge Python package manager developed by Astral.sh. `uv` is designed to be a highly efficient drop-in replacement for traditional `pip install` operations, boasting remarkable speed improvements and compatibility with existing `pip` workflows.

#### Key Improvements:
- **Build Performance**: Through local testing, I've observed that adopting `uv` has slashed our Docker build times by an impressive 50%. This enhancement is expected to streamline our development pipeline, reducing wait times for builds and deployments significantly.
- **Image Optimization**: Alongside the performance boost, this change introduces the use of virtual environments, which has the added benefit of reducing our Docker image size by approximately 300MB. This optimization not only speeds up the deployment process but also minimizes resource consumption, aligning with our goals for efficiency and sustainability.

For more details on `uv` and its capabilities, visit [Astral.sh's uv announcement](https://astral.sh/blog/uv).

I believe these changes will significantly improve our workflow and resource usage, and I look forward to any feedback on this change (even if it's "this might be too new").

### CODE REVIEW

**Comment by tjbck** [comment]
Amazing stuff! it works flawlessly on my machine but we might need more comprehensive testing to make sure there won't be any issues, but overall it looks promising!

**Comment by justinh-rahb** [comment]
> Amazing stuff! it works flawlessly on my machine but we might need more comprehensive testing to make sure there won't be any issues, but overall it looks promising!

Agreed, I'll make sure to keep my branch updated.

**Comment by justinh-rahb** [comment]
Yerp, found a bug already, the `uv pip install` for PyTorch fails on Linux x86_64 (but not macOS).

**Comment by justinh-rahb** [comment]
I think they fixed this bug but I need to wait until they push a new release to PyPI. Also found a workaround for global package installation.

**Comment by justinh-rahb** [comment]
Unfortunately, ya I think it may be too early days for this one. I'm hitting a lot of roadblocks trying to get this working smoothly on Linux (which is kinda important for Docker containers)... too many hacks and workarounds for my liking. I flies on my macOS local development environment, but it is definitely not ready for prod CI/CD.

**Comment by tjbck** [comment]
Let's consider again when it's mature enough, keeping my eyes on it!

**Pull request closed without merging**
