### PR TITLE
feat: Add Mem0ai for memory

### PR DESCRIPTION
**Pull request by Dev-Khant**
# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [x] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [ ] **Testing:** Have you written and run sufficient tests for validating the changes?
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [x] **Prefix:** To cleary categorize this pull request, prefix the pull request title, using one of the following:
  - **BREAKING CHANGE**: Significant changes that may affect compatibility
  - **build**: Changes that affect the build system or external dependencies
  - **ci**: Changes to our continuous integration processes or workflows
  - **chore**: Refactor, cleanup, or other non-functional code changes
  - **docs**: Documentation update or addition
  - **feat**: Introduces a new feature or enhancement to the codebase
  - **fix**: Bug fix or error correction
  - **i18n**: Internationalization or localization changes
  - **perf**: Performance improvement
  - **refactor**: Code restructuring for better maintainability, readability, or scalability
  - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
  - **test**: Adding missing tests or correcting existing tests
  - **WIP**: Work in progress, a temporary label for incomplete or ongoing work

# Changelog Entry

### Description

- Integrated https://github.com/mem0ai/mem0 which is a more robust solution to handle memory.

### Added

- Mem0 package  and methods are added.

### Changed

- Change the memory methods used [here](https://github.com/open-webui/open-webui/blob/main/backend/apps/webui/models/memories.py).

### Deprecated

- 

### Removed

- Removed the SQL based approach for handling memory. Also removed the chromadb client that was used for querying relevant memories. Now Mem0 handles everything.

### Fixed

- [List any fixes, corrections, or bug fixes]

### Security

- [List any new or updated security-related changes, including vulnerability fixes]

### Breaking Changes

- **BREAKING CHANGE**: [List any breaking changes affecting compatibility or functionality]

---

### Additional Information

- [Insert any additional context, notes, or explanations for the changes]
  - [Reference any related issues, commits, or other relevant information]

### Screenshots or Videos

- [Attach any relevant screenshots or videos demonstrating the changes]

### CODE REVIEW

**Comment by justinh-rahb** [comment]
This isn't going to be merged if it's not optional.

**Comment by tjbck** [comment]
Core implementation will not be changed and I'd encourage you to make Functions for this!

**Comment by Dev-Khant** [comment]
Hey, @tjbck @justinh-rahb Can you guide me on where can I add this and how can be added as function?

**Comment by Tuxaios** [comment]
@tjbck Everyone really needs this feature, why are you stopping it?

**Pull request closed without merging**
