### PR TITLE
feat: openai tts support

### PR DESCRIPTION
**Pull request by tjbck**

### CODE REVIEW

**Comment by oliverbob** [comment]
I presume that adding an OPENAI key at the settings will activate the tts. Correct? But I notice that it only give me new models to interact with. How do I activate openai tts?

**Comment by oliverbob** [comment]
Found it, I have to click the default voice a second time. Thanks.

**Comment by oliverbob** [comment]
image

For some reason the audio doesn't play.

**Comment by tjbck** [comment]
@oliverbob Hmm, it might be a browser cache issue. Try using it with other browsers or in incognito mode and see if the issue persists.

**Comment by tjbck** [comment]
@oliverbob https://stackoverflow.com/questions/75041580/openai-api-giving-error-429-too-many-requests

**Pull request merged**
