### PR TITLE
feat: download file in document list

### PR DESCRIPTION
**Pull request by jonathan-rohde**
# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [ ] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [x] **Testing:** Have you written and run sufficient tests for validating the changes?
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [x] **Prefix:** To cleary categorize this pull request, prefix the pull request title, using one of the following:
  - **BREAKING CHANGE**: Significant changes that may affect compatibility
  - **build**: Changes that affect the build system or external dependencies
  - **ci**: Changes to our continuous integration processes or workflows
  - **chore**: Refactor, cleanup, or other non-functional code changes
  - **docs**: Documentation update or addition
  - **feat**: Introduces a new feature or enhancement to the codebase
  - **fix**: Bug fix or error correction
  - **i18n**: Internationalization or localization changes
  - **perf**: Performance improvement
  - **refactor**: Code restructuring for better maintainability, readability, or scalability
  - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
  - **test**: Adding missing tests or correcting existing tests
  - **WIP**: Work in progress, a temporary label for incomplete or ongoing work

# Changelog Entry

### Description

- Re-add the download button as link
- Use FileAPI
- Store file-id in meta data of documents
- Only show download button, if file-id is available

### Added

- Download button for documents

---

### Additional Information

- It might make sense to migrate the documents to the files API sooner or later. The files table also contains all the inline uploaded files, which are not available in the documents table
- If backend and frontend running on different hosts/ports than the browser might show a preview instead of downloading the file.

### CODE REVIEW

**Comment by drupol** [comment]
Cool feature, I was looking for something similar.

Do you think you could add a new column in the table with the date the document was added?

**Comment by drupol** [comment]
@jonathan-rohde WDYT ^^

**Comment by jonathan-rohde** [comment]
Sounds good to me to add that info in general to the view.
But I do not see it necessarily part of this PR, could be another one.

Furthermore I am currently not updating the PR as the document view is changing and I first want to await those changes to update my code.

**Comment by drupol** [comment]
Cool ! Thank you for your answer, make sense.

**Pull request closed without merging**
