### PR TITLE
Comment fix config.py ln 412

### PR DESCRIPTION
**Pull request by JanSolo1**
## Pull Request Checklist

- [x] **Description:** Briefly describe the changes in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [x] **Documentation:** Have you updated relevant documentation?

---

## Description

Fixed a spelling mistake in one of the comments.

---

### Fixed

- Spelling mistake

### Changed

- Changed one word in a comment

### CODE REVIEW

**Comment by tjbck** [comment]
Thanks!

**Comment by Silentoplayz** [comment]
It's still misspelled. Lol

**Comment by tjbck** [comment]
lol missed that, @JanSolo1 please review your changes.

**Comment by JanSolo1** [comment]
New PR created.
Sorry about that, I mean it was closer : )

**Pull request merged**
