### PR TITLE
feat: direct litellm integration

### LINKED ISSUE #861: feat: remove ollama dependency
**Is your feature request related to a problem? Please describe.**
Hey :) as I use [litellm](https://github.com/BerriAI/litellm) for loadbalancing, I set its url as connection and removed the ollama api url, as you can see here:  
image
  
The problem is, refreshing the site or logging in states about the impossible ollama api connection, as you can see here:  
image
  
(Error-Messages: "Ollama Version: Not Detected" , "Open WebUI: Server Connection Error").

**Describe the solution you'd like**
If only openai api base url is set, disable the described error messages, disable ollama-api requests that still seem to happen right now. 

**Describe alternatives you've considered**
Another solution could be:
Add a switch which states "only openai" or "disable ollama-api" and therefore disables the requests to the ollama api.

**Additional context**
I really like your project :) thank you!

### PR DESCRIPTION
**Pull request by tjbck**
Resolves #861

TODO:

- [x] Remove Ollama dependency
- [x] LiteLLM Config UI
- [x] Doc/Changelog

### Added

- Open WebUI now has LiteLLM built-in.

### Fixed

N/A

### Changed

- Ollama is no longer required to run Open WebUI.

### Removed

N/A

### CODE REVIEW

**Comment by justinh-rahb** [comment]
Woohoo! So glad to see this coming so soon! I think this could be a huge boon to the project, being able to integrate ANY API.

**Comment by tbendien** [comment]
🙏🙏🙏👏💯

**Comment by spammenotinoz** [comment]
Just a thank-you, this was a huge addition.

**Comment by tjbck** [comment]
FYI, LiteLLM direct integration will be removed at some point.

**Comment by spammenotinoz** [comment]
> FYI, LiteLLM direct integration will be removed at some point.

Hopefully in favour of indirect support.

**Pull request merged**
