### PR TITLE
Feat: Allow All Users Access to Docs Upload and Prompts

### PR DESCRIPTION
**Pull request by davidamacey**
## New Feature Request

Requesting to implement a new feature.

### User Story

I would like to use this webui for a small team to share content for chat conversations.  I am currently not able to upload documents as a user.

Only users with admin are able to upload documents and create prompts.  Thus, requiring all users to have admin access.  This could lead to unintended consequences with a user accidentally deleting or change access that only an admin should have access.

### Bonus Benefits

With a small team of users, this allows users to see and share the types of prompts other users are creating.  Resulting in increase of efficiency in prompt engineering and collaboration.

### Solution

1.  Allow UI to rending Documents and Prompts in sidebar.  Edit side bar svelte.
2. Allow Admin and Users to upload, edit Documents as well as Prompts add/edit. Edit routers accordingly.

Tested locally on my machine, building in docker.  User 'admin' in one browser, and test 'user' in another browser.  Both sessions updated accordingly.  Documents and prompts shared between Admin and User accounts.

## Request Review

Requesting review and feedback as required.  If there is a better implementation or a `user.roles` check that I missed, I am happy to assist with a change.

Thank you for your time and reviewing this update.

### CODE REVIEW

**Comment by tjbck** [comment]
Hi, Thanks for the PR! I'm going to have to close this PR as this breaking change might have unintended consequences for people who have deployed this project already. However, we do plan on adding more granular level of user roles/permissions in the future so stay tuned for updates, Thanks!

**Comment by davidamacey** [comment]
@tjbck Thank you for the prompt response, much appreciated.

Thank you for explaining your reasoning.  Do you have a roadmap or expected upcoming feature list?

In the meantime, I will build locally for my use case. :)

Thanks!

**Comment by tleish** [comment]
I'm interested in this same functionality

**Comment by davidamacey** [comment]
@tleish I have my PR branch up to date with webui-main branch with this feature enabled.  Pull my main branch and build locally.  Good Luck!

**Comment by oliverbob** [comment]
Is this PR available for OI? Love this feature actually for collaborators. Thanks.

**Comment by justinh-rahb** [comment]
> Is this PR available for OI? Love this feature actually for collaborators. Thanks.

Closed without merging. PR is over a month out of date so this would need to be redone if anyone is still interested. Would need to be optional/configurable.

**Pull request closed without merging**
