### PR TITLE
fix: do not try to hit OpenAI when it was disabled

### PR DESCRIPTION
**Pull request by leobenkel**
# Pull Request Checklist

### Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

https://github.com/open-webui/open-webui/discussions/4314

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [x] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [x] **Testing:** Have you written and run sufficient tests for validating the changes?
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [x] **Prefix:** To cleary categorize this pull request, prefix the pull request title, using one of the following:
  - **BREAKING CHANGE**: Significant changes that may affect compatibility
  - **build**: Changes that affect the build system or external dependencies
  - **ci**: Changes to our continuous integration processes or workflows
  - **chore**: Refactor, cleanup, or other non-functional code changes
  - **docs**: Documentation update or addition
  - **feat**: Introduces a new feature or enhancement to the codebase
  - **fix**: Bug fix or error correction
  - **i18n**: Internationalization or localization changes
  - **perf**: Performance improvement
  - **refactor**: Code restructuring for better maintainability, readability, or scalability
  - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
  - **test**: Adding missing tests or correcting existing tests
  - **WIP**: Work in progress, a temporary label for incomplete or ongoing work

# Changelog Entry

### Description

- Do not try to hit OpenAI when it was disabled

### Changed

- Do not try to hit OpenAI when it was disabled

### Fixed

- Do not try to hit OpenAI when it was disabled

### CODE REVIEW

**Comment by leobenkel** [comment]
not sure how to do a retry on the test. looks like something unrelated to this change

**Comment by tjbck** [comment]
`/openai/models` endpoint has been deprecated and is not being used by the webui.

**Comment by leobenkel** [comment]
> `/openai/models` endpoint has been deprecated and is not being used by the webui.

I have seen it being hit in the browser console when you go to admin settings and go to the `connection` tab

**Comment by leobenkel** [comment]
@tjbck here: https://github.com/open-webui/open-webui/blob/6657f28694c3c854182867d670ca0b00169bd616/src/lib/components/admin/Settings/Connections.svelte#L54

**Pull request closed without merging**
