### PR TITLE
changed: auth ollama connection

### PR DESCRIPTION
**Pull request by ymerejeremy**
## Pull Request Checklist

- [x] **Target branch:** Pull requests should target the `dev` branch.
- [x] **Description:** Briefly describe the changes in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [x] **Testing:** Have you written and run sufficient tests for the changes?
- [x] **Code Review:** Have you self-reviewed your code and addressed any coding standard issues?

---

## Description

Add support for ollama connection that require a token access. The token can be set with the environment variable OLLAMA_AUTH_KEY or in the connection settings.

---

### Added

- Optional environment variables OLLAMA_AUTH_KEY and OLLAMA_AUTH_KEYS to set access token
- Option to set access token in connections settings

### Fixed

- In ollama router, improve ollama response checking for  `get_ollama_versions(...)` (route `/api/version`) and `get_all_models()` methods to avoid errors

### Changed

- Use token access for ollama connection

---

### Additional Information

video-haunui-ok

Issue : #2305

### CODE REVIEW

**Comment by timoa** [comment]
If you use another solution like Cloudflare Zero Trust to protect Ollama from outside (in a private subnet in AWS for ex.), you need to add two HTTP headers (`CF-Access-Client-Id` & `CF-Access-Client-Secret`). Is there a way to add multiple headers instead of static? Sorry if it's too late for this PR. I'm pretty sure that it will be useful for multiple authentication. Cheers!

**Comment by justinh-rahb** [comment]
Hello @Haunui! I appreciate and support the work you've contributed here. We've had 2 major releases in the last two weeks, I just wanted to check in to see if you're still willing to get this PR brought up to current dev branch base and finish it. If it's easier to close and open a new one, that's ok too.

**Comment by Kavan72** [comment]
I can help on this PR if you want. 
cc. @Haunui @justinh-rahb

**Comment by Haunui** [comment]
@timoa I think thats a good idea. But I don't have the time and ressources to work on this features.

**Comment by Haunui** [comment]
Hello @justinh-rahb, sorry for the late answer.
The PR is ready and can now be pushed to the current dev branch.

**Comment by Haunui** [comment]
Currently, I don't have time to work on it. I think I'll rework it to allow custom HTTP headers, it'll be more complete. 
The documentation part is missing too.

**Comment by visagansanthanam-unisys** [comment]
@Haunui this is a important feature to have in openwebui. Thanks for working on it, any idea when this will be available as part of a release?

**Comment by Haunui** [comment]
> @Haunui this is a important feature to have in openwebui. Thanks for working on it, any idea when this will be available as part of a release?

no date at the moment

**Comment by jrespeto** [comment]
Is there any update on this request? Adding auth token headers to proxy-fronted ollama servers would be great.

**Comment by tjbck** [comment]
Closing in favour of 99446c4b7615bc072fcbaf1ce0bcd5fd7c843132, thanks!

**Pull request closed without merging**
