### PR TITLE
Switch `pip3` to `uv` in GitHub Action workflow

### PR DESCRIPTION
**Pull request by justinh-rahb**
## Description

This PR introduces [`uv`](https://github.com/astral-sh/uv), a new package manager, as a partial replacement for `pip3` in the Docker build process for the "Open WebUI" project. `Uv` is a mostly drop-in compatible substitute for `pip3` with significant performance improvements. In our testing, `uv` has shown to notably reduce build times — by nearly 50% on GitHub Action runners and by approximately 25-30% when building locally across various platforms. While the resultant build sizes have varied, showing both increases and decreases depending on the build environment, this change aims to leverage `uv`'s efficiency gains to enhance the development workflow and process efficiency. It's important to note that `pip3` has not been completely removed; it remains necessary for installing PyTorch and its dependencies, as `uv` has not yet reliably resolved them across all build environments. As this is an evolving integration, more opinions and testing are highly encouraged to ensure a smooth transition. For further details on `uv`, please refer to the [uv documentation](https://github.com/astral-sh/uv) and [this introductory blog post](https://astral.sh/blog/uv).

---

#### Added
- Introduced [`uv`](https://github.com/astral-sh/uv) as the new package manager in the Docker build process for certain dependencies, aiming to improve build times and efficiency.

#### Fixed
- N/A

#### Changed
- Partially replaced `pip3` with [`uv`](https://github.com/astral-sh/uv) in the Docker build

#### Using `pip3`:

Screenshot_2024-04-05_at_10 19 46_PM

---

#### Using `uv`:

Screenshot_2024-04-05_at_10 19 23_PM

---

#### Added
- Introduced `uv` as the new package manager in the Docker build process for certain dependencies, aiming to improve build times and efficiency.

#### Fixed
- N/A

#### Changed
- Partially replaced `pip3` with `uv` in the Docker build process. This does not yet cover PyTorch and its dependencies, which still rely on `pip3` due to resolution issues in some environments.

#### Removed
- N/A

---

## Pull Request Checklist

- [x] **Description:** This PR partially introduces `uv` as a replacement for `pip3` in the Docker build process, aimed at improving build times and efficiency for certain dependencies. `Pip3` remains in use for installing PyTorch and its dependencies, due to current limitations with `uv`.
- [x] **Changelog:** A detailed changelog entry has been added, highlighting the introduction of `uv`, the partial replacement of `pip3`, and noting the continued use of `pip3` for specific dependencies.

### CODE REVIEW

**Comment by buroa** [comment]
Not sure if this helps you but I maintain a version of this: https://github.com/buroa/containers/blob/master/apps/open-webui/Dockerfile

**Comment by justinh-rahb** [comment]
In between originally creating my changes and now, @jannikstdl has made significant updates to the Dockerfile, got myself a bit turned around but it's building now:
https://github.com/justinh-rahb/open-webui/actions/runs/8617954237/job/23619179757

**Comment by jannikstdl** [comment]
Nice! I was searching for something like that because now with the Rust improvements going on there is bun for npm but about 2-3 months ago there was no such alternative for pip. Was a matter of time and I see uv released its first version in mid February.

**Comment by justinh-rahb** [comment]
> Nice! I was searching for something like that because now with the Rust improvements going on there is bun for npm but about 2-3 months ago there was no such alternative for pip. Was a matter of time and I see uv released its first version in mid February.

I actually tried switching npm for bun and it had negligible build-time impact, so felt it better left alone.

**Comment by jannikstdl** [comment]
@justinh-rahb would it be faster to switch `npm ci` to `bun install --frozen-lockfile`?

**Comment by justinh-rahb** [comment]
> @justinh-rahb would it be faster to switch `npm ci` to `bun install --frozen-lockfile`?

I originally tested this before on the pre-refac Dockerfile and it had zero impact. I haven't tested it on this one, but I don't expect it would be much, if even measurable.

**Comment by lainedfles** [comment]
@justinh-rahb Very nice! Builds using `--no-cache -t open-webui --build-arg="USE_CUDA=true" --build-arg="USE_EMBEDDING_MODEL=mixedbread-ai/mxbai-embed-large-v1"` yield savings of 58.272s (26.653% reduction)!

I attempted to get it working with the torch installation but ran into issue astral-sh/uv#2541. We may be able to pull the latest version identifier using another method and use it to build a compatible `uv pip install` command for it. It would be nice to it working there too.

My only suggestion would be to replace the `curl` dependency with `pip3` installation. I've submitted justinh-rahb/open-webui#18 for your consideration. 🥂

**Comment by justinh-rahb** [comment]
> My only suggestion would be to replace the `curl` dependency with `pip3` installation. I've submitted [justinh-rahb#18](https://github.com/justinh-rahb/open-webui/pull/18) for your consideration. 🥂

Ya I wasn't sure which to use but I suppose if we're not entirely ditching pip3 as it is anyway, why not? I'll merge that later, thanks!

**Pull request closed without merging**
