### PR TITLE
Always open links in chat in a new tab

### PR DESCRIPTION
**Pull request by austenadler**
## Pull Request Checklist

- [x] **Target branch:** Pull requests should target the `dev` branch.
- [x] **Description:** Briefly describe the changes in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [x] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [x] **Testing:** Have you written and run sufficient tests for the changes? -> I did not see any tests
- [x] **Code Review:** Have you self-reviewed your code and addressed any coding standard issues?

---

## Description

Add `target="_blank" rel="nofollow"` to all links in the chat history window. It is annoying to click a link in a chat and have it unload Open-Webui, so I added this feature. (This)[https://github.com/markedjs/marked/issues/655#issuecomment-383226346] issue in the `marked` repo describes how to do this properly.

This only applies to links within chat messages. For example, asking a model `what is the URL of https://google.com?` and clicking the link in your message or the one it produces.

---

### Changed

- Links in chat open in a new tab instead of the same tab

---

### CODE REVIEW

**Comment by austenadler** [comment]
I believe the issue here is this line:

https://github.com/open-webui/open-webui/blob/90503be2edef1a1f7ce2074286b6316d5cb8868a/src/lib/components/chat/Messages/ResponseMessage.svelte#L72

Which calls this function:

https://github.com/open-webui/open-webui/blob/90503be2edef1a1f7ce2074286b6316d5cb8868a/src/lib/utils/index.ts#L32-L40

This transforms `<https://www.google.com>` into `&lt;https://www.google.com>`, and then this is passed in to `marked` here: https://github.com/open-webui/open-webui/blob/90503be2edef1a1f7ce2074286b6316d5cb8868a/src/lib/components/chat/Messages/ResponseMessage.svelte#L440-L445 which correctly parses it

`marked` knows how to parse `<https://example.com>` in the latest version as well as 9.1.6, so if we fix that `&lt;` replacement, it will work. 

I don't know what the impact of adding `.replaceAll('>', '&gt;')` is to `sanitizeResponseContent`. Another option is to not replace `<` with `&lt;`.

**Comment by austenadler** [comment]
I tried two ways to fix sanitization

1. Method 1: Replace `>` with `&gt;` as well (included in this PR)

<details><summary>Patch</summary>
<p>

```patch
diff --git a/src/lib/utils/index.ts b/src/lib/utils/index.ts
index 03cbc626..2f9b1dc2 100644
--- a/src/lib/utils/index.ts
+++ b/src/lib/utils/index.ts
@@ -36,11 +36,14 @@ export const sanitizeResponseContent = (content: string) => {
 		.replace(/<$/, '')
 		.replaceAll(/<\|[a-z]+\|>/g, ' ')
 		.replaceAll('<', '&lt;')
+		.replaceAll('>', '&gt;')
 		.trim();
 };
 
 export const revertSanitizedResponseContent = (content: string) => {
-	return content.replaceAll('&lt;', '<');
+	return content
+		.replaceAll('&lt;', '<')
+		.replaceAll('&gt;', '>');
 };
 
 export const capitalizeFirstLetter = (string) => {
```

</p>
</details> 

2. Method 2: Use dompurify after markup parsing (as suggested [here](https://github.com/markedjs/marked/discussions/1232))

<details><summary>Patch</summary>
<p>

```patch
commit 9c48a1568d00029bef65b9b653d02fd013f52eef
Author: Austen Adler <agadler@austenadler.com>
Date:   Thu May 16 16:28:10 2024 -0400

    Use dompurify instead of manual sanitization

diff --git a/package-lock.json b/package-lock.json
index be7ae0dc..80477544 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -12,6 +12,7 @@
 				"async": "^3.2.5",
 				"bits-ui": "^0.19.7",
 				"dayjs": "^1.11.10",
+				"dompurify": "^3.1.3",
 				"eventsource-parser": "^1.1.2",
 				"file-saver": "^2.0.5",
 				"highlight.js": "^11.9.0",
@@ -2730,6 +2731,11 @@
 				"url": "https://github.com/fb55/domhandler?sponsor=1"
 			}
 		},
+		"node_modules/dompurify": {
+			"version": "3.1.3",
+			"resolved": "https://registry.npmjs.org/dompurify/-/dompurify-3.1.3.tgz",
+			"integrity": "sha512-5sOWYSNPaxz6o2MUPvtyxTTqR4D3L77pr5rUQoWgD5ROQtVIZQgJkXbo1DLlK3vj11YGw5+LnF4SYti4gZmwng=="
+		},
 		"node_modules/domutils": {
 			"version": "3.1.0",
 			"resolved": "https://registry.npmjs.org/domutils/-/domutils-3.1.0.tgz",
diff --git a/package.json b/package.json
index f8096269..ea7de885 100644
--- a/package.json
+++ b/package.json
@@ -49,6 +49,7 @@
 		"async": "^3.2.5",
 		"bits-ui": "^0.19.7",
 		"dayjs": "^1.11.10",
+		"dompurify": "^3.1.3",
 		"eventsource-parser": "^1.1.2",
 		"file-saver": "^2.0.5",
 		"highlight.js": "^11.9.0",
diff --git a/src/lib/components/chat/Messages/ResponseMessage.svelte b/src/lib/components/chat/Messages/ResponseMessage.svelte
index 1ad252f6..b067aac1 100644
--- a/src/lib/components/chat/Messages/ResponseMessage.svelte
+++ b/src/lib/components/chat/Messages/ResponseMessage.svelte
@@ -1,5 +1,6 @@
 <script lang="ts">
 	import { toast } from 'svelte-sonner';
+	import DOMPurify from 'dompurify';
 	import dayjs from 'dayjs';
 	import { marked } from 'marked';
 	import tippy from 'tippy.js';
@@ -441,15 +442,15 @@
 									{#if token.type === 'code'}
 										<CodeBlock
 											lang={token.lang}
-											code={revertSanitizedResponseContent(token.text)}
+											code={token.text}
 										/>
 									{:else}
-										{@html marked.parse(token.raw, {
+										{@html DOMPurify.sanitize(marked.parse(token.raw, {
 											...defaults,
 											gfm: true,
 											breaks: true,
 											renderer
-										})}
+										}))}
 									{/if}
 								{/each}
 							{/if}
diff --git a/src/lib/utils/index.ts b/src/lib/utils/index.ts
index 03cbc626..20c68d84 100644
--- a/src/lib/utils/index.ts
+++ b/src/lib/utils/index.ts
@@ -35,14 +35,9 @@ export const sanitizeResponseContent = (content: string) => {
 		.replace(/<\|[a-z]+\|$/, '')
 		.replace(/<$/, '')
 		.replaceAll(/<\|[a-z]+\|>/g, ' ')
-		.replaceAll('<', '&lt;')
 		.trim();
 };
 
-export const revertSanitizedResponseContent = (content: string) => {
-	return content.replaceAll('&lt;', '<');
-};
-
 export const capitalizeFirstLetter = (string) => {
 	return string.charAt(0).toUpperCase() + string.slice(1);
 };
```

</p>
</details> 

Which one would you prefer? I have already tested both and they're about the same. I think dompurify is better long-term, but it's a larger change.

**Comment by tjbck** [comment]
1st option would be preferable for now!

**Comment by austenadler** [comment]
Okay, I pushed patch 1

**Comment by anuraagdjain** [comment]
Couldn't check this earlier. The change seems to be working thank you 🙏

**Review by anuraagdjain — APPROVED** [review]
LGTM 🚀

**Comment by tjbck** [comment]
Thanks everyone!

**Pull request merged**
