### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by Collected5353**
Hello Team,

As the continued popularity of this project increases we should be taking our projects goals in mind with concerns to privacy and security. In the near future I would like to at least start testing the codebase with SAST(semgrep) and Synk.io (Software Composition Analysys) To highlight any potential weaknesses in the security of the product. 

I am happy to start contributing from the security side.

### CODE REVIEW

**Comment by tjbck** [comment]
We might want to move to this to '/docs' folder!

**Comment by justinh-rahb** [comment]
> We might want to move to this to '/docs' folder!

I think it needs to be in the repo root to be recognized by GitHub.

**Comment by justinh-rahb** [comment]
TIL that the security policy can be in **either* the root, `/docs`, or `.github` directories. Got some repositories to reorganize 😂

**Comment by Collected5353** [comment]
Yeah this repo is pretty big so I agree it should be in /docs. Updated the PR.

**Comment by tjbck** [comment]
LGTM, Thanks!

**Pull request merged**
