### PR TITLE
Feat/custom default user permissions chat deletion

### PR DESCRIPTION
**Pull request by changchiyou**
## Pull Request Checklist

- [x] **Description:** Briefly describe the changes in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation?

  > No relevant documentation exists.
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?

---

## Description

> This is a workaround for #988, which is mentioned at https://github.com/open-webui/open-webui/issues/1022#issuecomment-1992061479.

Users can now customize the initial value of `USER_PERMISSIONS` for `Allow Chat Deletion` by setting `USER_PERMISSIONS_CHAT_DELETION` to `False`.

---

### Added

- Allow user custom default user permission, specifically `Allow Chat Deletion`.

### CODE REVIEW

**Comment by justinh-rahb** [comment]
@changchiyou Thanks for the PR! Can I ask if this has been thoroughly tested and doesn't introduce any difficulties for anyone that _wouldn't_ be using it?

**Comment by changchiyou** [comment]
> ... Can I ask if this has been thoroughly tested and doesn't introduce any difficulties for anyone that wouldn't be using it?

@justinh-rahb Yes! I've tested with and without the inclusion of the following environment variable in the `docker-compose.yaml`, after rebuilding the image using `docker-compose up --build`:

```
    environment:
      - "USER_PERMISSIONS_CHAT_DELETION=${USER_PERMISSIONS_CHAT_DELETION}"
```

- When `USER_PERMISSIONS_CHAT_DELETION` is set to `False`, the behavior is as expected:
`Allow Chat Deletion` is set to `Don't Allow` upon container startup.
- Conversely, when `USER_PERMISSIONS_CHAT_DELETION` is set to `True` or not specified in the `docker-compose.yaml`, the default behavior remains unchanged, `Allow Chat Deletion` is set to `Allow` upon container startup.
- Additionally, error messages are appropriately generated in cases of incorrect user settings.

**Comment by justinh-rahb** [comment]
Thanks for the additional testing information @changchiyou!

**Comment by tjbck** [comment]
I'll also merge this for now but using `config.json` will be the official supported method to configure settings starting from our next release! Thanks!

**Pull request merged**
