### PR TITLE
feat: show prompt token/s in perf info

### LINKED ISSUE #634: feat: prompt token/s
**Is your feature request related to a problem? Please describe.**
Perf info under chat response shows response speed in tokens/sec, but prompt processing speed is only shown as token count and total time.

**Describe the solution you'd like**
Show tokens/sec for prompt processing too.

### PR DESCRIPTION
**Pull request by dannyl1u**
Resolves #634

image

### CODE REVIEW

**Comment by tjbck** [comment]
LGTM, Thanks!

**Comment by RodriMora** [comment]
How can I enable that perf info icon? I doesn't how on my chats by default and I can't find any toggle in the setting about it

**Comment by dannyl1u** [comment]
> How can I enable that perf info icon? I doesn't how on my chats by default and I can't find any toggle in the setting about it

@RodriMora 
image

It should show when you hover over the "Generation Info" tooltip under each resopnse

**Comment by RodriMora** [comment]
> > How can I enable that perf info icon? I doesn't how on my chats by default and I can't find any toggle in the setting about it
> 
> @RodriMora image
> 
> It should show when you hover over the "Generation Info" tooltip under each resopnse

I'm using vLLM as a backend. Someone on discord told me to enable in the model setting "usage":
image


It shows some stats but not all:
image

**Comment by wilsonnkwan** [comment]
I still can't find the button. I'm using LM Studio as the backend.

**Comment by Classic298** [comment]
@wilsonnkwan enable "Usage" in the model settings

**Pull request merged**
