### PR TITLE
feat: add ability to configure a HTTP ChromaDB client

### PR DESCRIPTION
**Pull request by cheahjs**
## Pull Request Checklist

- [x] **Description:** Briefly describe the changes in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation?
- [ ] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?

---

## Description

Addresses the vector DB portion of https://github.com/open-webui/open-webui/issues/1397

Adds the following environment variables to configure a HTTP client for ChromaDB to connect to a ChromaDB Server instead of a local client:

1. `CHROMA_HTTP_HOST` - Hostname to connect to
2. `CHROMA_HTTP_PORT` - Port to connect to, defaults to 8000
3. `CHROMA_HTTP_HEADERS` - Any headers to add to requests
4. `CHROMA_HTTP_SSL` - Use TLS for connections

These additional env vars also apply to local ChromaDB:

1. `CHROMA_TENANT`
2. `CHROMA_DATABASE`

To test this locally,

1. Start a ChromaDB server instance: `docker run -p 8000:8000 --rm chromadb/chroma`
2. Configure the backend env vars: `CHROMA_HTTP_HOST=localhost CHROMA_HTTP_PORT=8000 GLOBAL_LOG_LEVEL=DEBUG ./start.sh`

---

### Added

- 🌐 **Remote ChromaDB Support**: Add the ability to connect to a remote ChromaDB server

### CODE REVIEW

**Comment by tjbck** [comment]
LGTM 🚀

**Comment by alessandervs** [comment]
I tray to connect to server ChromaDB with this comman:

**Comment by alessandervs** [comment]
I tray to connect to server ChromaDB with command below:
docker run -d --network=host --gpus all -v ~/projetos/ollama/open-webui:/app/backend/data -e OLLAMA_BASE_URL=http://127.0.0.1:11434 -e CHROMA_HTTP_HOST=http://127.0.0.1 -e CHROMA_HTTP_PORT=8082 --name open-webui --restart always ghcr.io/open-webui/open-webui:cuda

But not working.
Log of container:

    CHROMA_CLIENT = chromadb.HttpClient(
                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chromadb/__init__.py", line 197, in HttpClient
    return ClientCreator(tenant=tenant, database=database, settings=settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chromadb/api/client.py", line 144, in __init__
    self._validate_tenant_database(tenant=tenant, database=database)
  File "/usr/local/lib/python3.11/site-packages/chromadb/api/client.py", line 447, in _validate_tenant_database
    raise ValueError(
ValueError: Could not connect to tenant default_tenant. Are you sure it exists?


ChromaDb server Running:

image

**Comment by tjbck** [comment]
Are you sure it exists?

**Pull request merged**
