### PR TITLE
enh: citations show relevance score - compact citation view 

### PR DESCRIPTION
**Pull request by jannikstdl**
### Description

This PR includes the following key changes:

- **Relevance Score for Citations:** Citations now display a relevance score in both percentage and float distance formats.
~~**Sorted Citations:** Citations under the message are now sorted by relevance (e.g., source 1, source 2...).~~ -> Already implemented in the backend
- **Compact Source Display:** For more than 3 sources, a cleaner source display is shown under the message.

**Relevance Score for Citations:**
image

**Compact Source Display:**
https://github.com/user-attachments/assets/848300f3-edef-4074-b2d5-d5ba9c680714

**Testing**
- [x] Milvus DB
- [x] If error / distances are not available 
- [x] Other Embedding Engines than Ollama: OpenAI Embedding, Dafault integrated ones
- [x] If only one distance is in cosine similarity range -1 to 1

### CODE REVIEW

**Comment by Mushy-Snugglebites-badonkadonk** [comment]
@jannikstdl This is pretty rad. I’m digging it. 

Speaking of “Cleaner Source Display”, what are your thoughts on compressing whitespace for website retrievals through _web search_?

**Comment by jannikstdl** [comment]
> @jannikstdl This is pretty rad. I’m digging it. 
> 
> 
> 
> Speaking of “Cleaner Source Display”, what are your thoughts on compressing whitespace for website retrievals through _web search_?

Hi, what whitespace exactly are you talking about?

**Comment by jannikstdl** [comment]
If someone uses different vector stores than Chroma or can try some other scenarios, testing appreciated here! 🙂

**Comment by jannikstdl** [comment]
@tjbck Testing was successful.

**FYI**
- The Milvus similarity search appears to be malfunctioning, as I am receiving random results instead of the expected full distance range (-1, 0, 1). I consistently get values around 0.7, suggesting an issue with the Milvus integration.

**Relevance Scores**
- The percentage score is displayed only for newly created collections with ChromaDB, as it requires cosine similarity.
image

- Relevance scores are **not** displayed if one or more files in a collection use different distance functions. Therefore, when adding new files to old collections that use Chroma L2 similarity, no relevance (distance or percentage) is shown, as only one file is retrieved with cosine similarity while the older ones still use the L2 distance function. This could confuse users since the distances of one or more files differ completely. However, retrieval works with mixed collections.
image

- For older collections in which all files use non-cosine similarity, only the distance is shown.
image

**Compact Source Display**
- The threshold for displaying compact citations is triggered when more than three sources are received.
- By default, it shows two citations plus "and x more," unless the citation names are too long for one line, in which case it displays one plus "and x more."
- It is responsive.

**Other Changes**
- Adjustments were made to the Collapsible component to prevent it from being triggered when clicking on sources and to fix a bug where it wouldn't open fully.
_wich fixed_
- **Hanging Animation**: The animation now extends all the way down.
  image

- **Open Collapsible on Citation Click**: The collapsible now opens when clicking on citation buttons.
  image

**Comment by tjbck** [comment]
Thanks! More testing wanted after the merge!

**Pull request merged**
