### PR TITLE
Fix Open WebUI would request some unsupported bodies

### LINKED ISSUE #2455: [BUG] Open WebUI would request some unsupported bodies
# [BUG]

### Such as `abab6.5s-chat` and `gemini-1.5-flash-latest`
737b7c53c3a6417cc59759a8a19bcfb
8baa0ed5d04b67b89f67fdf8a69f0a2

### Normal 
8baa0ed5d04b67b89f67fdf8a69f0a2
977af435bb33d263530e9319eea3fd6

### PR DESCRIPTION
**Pull request by Yanyutin753**
# Pull Request Checklist

### fix #2455

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [x] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [x] **Testing:** Have you written and run sufficient tests for validating the changes?
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [x] **Label:** To cleary categorize this pull request, assign a relevant label to the pull request title, using one of the following:
  - **BREAKING CHANGE**: Significant changes that may affect compatibility
  - **build**: Changes that affect the build system or external dependencies
  - **ci**: Changes to our continuous integration processes or workflows
  - **chore**: Refactor, cleanup, or other non-functional code changes
  - **docs**: Documentation update or addition
  - **feat**: Introduces a new feature or enhancement to the codebase
  - **fix**: Bug fix or error correction
  - **i18n**: Internationalization or localization changes
  - **perf**: Performance improvement
  - **refactor**: Code restructuring for better maintainability, readability, or scalability
  - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
  - **test**: Adding missing tests or correcting existing tests
  - **WIP**: Work in progress, a temporary label for incomplete or ongoing work

### CODE REVIEW

**Comment by Yanyutin753** [comment]
@justinh-rahb @akx Just filtered the message. Nothing else. Everything's back to normal

**Comment by AlyMobarak** [comment]
Umm... didn't I already fix it using my PR?

**Comment by Yanyutin753** [comment]
@AlyMobarak hhh, you should make a new pr, it feels a bit messy, I will turn this off later, you can see if you can solve the other issue

**Comment by Yanyutin753** [comment]
@AlyMobarak #2460 Have you encountered this problem? You can try to solve it， Let's make this project even better

**Pull request closed without merging**
