### PR TITLE
feat: support mysql.

### PR DESCRIPTION
**Pull request by zy526**
# Pull Request Checklist
- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [x] **Testing:** Have you written and run sufficient tests for validating the changes? Yes, the testing was performed for postgres, sqlite and mysql successfully.
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [x] **Prefix:** The pull request title is prefixed with "FEAT" to indicate a new feature.

# Changelog Entry

### Description
This pull request enhances to support mysql database besides sqlite and postgres. It'll solve the problem or feedback of the below discussions
[How to use MySQL as database not noly sqlite.](https://github.com/open-webui/open-webui/discussions/4544)
[Failed to start with mysql](https://github.com/open-webui/open-webui/discussions/3903)
[Is possible to customize the OpenWebUI application database and Chrom](https://github.com/open-webui/open-webui/discussions/4288)
[May I ask if I can use an external MySQL to store data?](https://github.com/open-webui/open-webui/discussions/2529)

### Changed
- relevant migration scripts under backend/apps/webui/internal/migrations, so that to support sqlite, postgres and mysql during db schema creation and migration.
    - 007_add_user_last_active_at.py added database_type check, when that type is mysql, use `, while postgres or sqlite, use ".
    - for 009_add_models.py, 012_add_tools.py, 014_add_files.py, 015_add_functions.py, all the id = pw.TextField(unique=True) is changed to be pw.CharField(max_length=255, unique=True) so that it wouldn't hit limitation in mysql.
    - 017_add_user_oauth_sub.py the oauth_sub is changed to be pw.CharField(max_length=255, null=True, unique=True), so that it wouldn't hit limitation in mysql.
- regarding backend/apps/webui/internal/wrappers.py, import MySQLDatabase, added reconnecting logic for it also.
- There is new dependency added in backend/requirements.txt, which is mysqlclient==2.2.4. because sqlalchemy relies on it and it's more stable.

### Additional Information
To use mysql database, just like using postgres, specify the DATABASE_URL as mysql://username:passwd@host:port/database

### Screenshots or Videos
Please refer testing screenshots:

For sqlite:
SQLite1
SQLite2

For postgresql:
Postgresql1
Postgresql2
Postgresql3

For mysql:
MySQL1
MySQL2
MySQL3

### CODE REVIEW

**Comment by justinh-rahb** [comment]
As with all PRs involving database interaction, we will need to see demonstrated extensive regression testing before this can be merged.

**Comment by zy526** [comment]
what kind of demo needed? can a sample be referred?

**Comment by zy526** [comment]
Please refer the screenshots.
SQLite1
SQLite2
Postgresql1
Postgresql2
Postgresql3
MySQL1
MySQL2
MySQL3

**Comment by zy526** [comment]
what else is needed? @justinh-rahb @tjbck

**Comment by justinh-rahb** [comment]
@zy526 there was a PR to migrate `config.json` settings to database #4899 so we'll definitely want to be sure you're rebased as needed and that migration is working as expected in line with SQLite and PGSQL.

**Comment by zy526** [comment]
> @zy526 there was a PR to migrate `config.json` settings to database #4899 so we'll definitely want to be sure you're rebased as needed and that migration is working as expected in line with SQLite and PGSQL.

rebased and retested, updated testing result as above. please have a look.

**Comment by tjbck** [comment]
I don't feel confident about adding mysql support, feel free to maintain a forked repo!

**Comment by zy526** [comment]
That's embarrassed! I tried to contribute, and provided what's asked for. then turned out to close without merging. tell me what made you feeling not confident? what's the bias? @tjbck @justinh-rahb

**Comment by justinh-rahb** [comment]
I only tried to make your PR as mergeable as possible but I don't get to decide what is or is not merged. If Tim doesn't wish to maintain MySQL support that's his decision and I respect it.

**Pull request closed without merging**
