### PR TITLE
Release Notes Modal

### LINKED ISSUE #799: feat: show popup "whats new" on pageload to summarize updates
**Describe the solution you'd like**
Since the developement of this repo is really fast it would be nice to have (with every release change) a little popup on start to show the "average consumer" new functionalities.

This should be a modal with texts reffering to `constants.ts` in my mind.

**Additional context**
Something like this but with "what's new" (or such tooltips like the blue one)
Screenshot 2024-02-19 125305

### PR DESCRIPTION
**Pull request by jannikstdl**
fix #799 

**Changes**

- Added the Modal (See first video)
- Added little animation (See second video)
- Disabled close Modals on background clicks because this was causing the modal to close ff you mark text sometimes (video 3) -> Maybe a "close only if the origin click was outside the modal" logic would also help.
- Notes changeable in `constants.ts`
- You can disable the modal in settings - interface

https://github.com/open-webui/open-webui/assets/69747628/66d2a771-4d33-4b4c-85d3-1d0a4cabcd48

https://github.com/open-webui/open-webui/assets/69747628/e4f014f4-bf74-4b3a-adeb-1c1faf512772

https://github.com/open-webui/open-webui/assets/69747628/aad71f66-9e2b-49b4-a54d-fd20a344e894

If no notes or invalid array:
image

### CODE REVIEW

**Comment by jannikstdl** [comment]
Maybe we should replate the `enableWhatsChanged `localstorage setting with a persistant db state since this is also volatile.

**Comment by justinh-rahb** [comment]
This looks amazing @jannikstdl I think this will help a lot with getting our new features in front of users. I follow every thread on this repo and even I find myself lost in the progress that's happened while I've been sleeping 🤣

**Comment by jannikstdl** [comment]
Thank you! Haha i feel you, its hard to be updated.. our codemachine @tjbck is just pushing updates one by one. But basically we're never sleeping since we are in different timezones. 😁

**Comment by tjbck** [comment]
Thanks for getting the ball rolling for this much needed feature!

**Pull request merged**
