### PR TITLE
feat: stable diffusion integration

### LINKED ISSUE #696: feat: image generation integration
**Feature request Summary**
Analogous to ChatGPT's integration of mixed models, I would like to have a single place for AI requests.
1, connect ollama webui via openAI api to dall-e 3 image generation
2, be able to connect ollama webui to other image generation models which run locally

Example of how dall-e image generation is presented in chatGPT interface:
dall-e

### PR DESCRIPTION
**Pull request by tjbck**
Resolves #696

> [!important]
> AUTOMATIC1111/stable-diffusion-webui should be run using `sh webui.sh --api` command with `--api` flag.

image

image

### Changes
image
- Advanced section has been removed and relocated to General.
- Ollama API URL Settings and OpenAI External Setting have been moved to Connections section.

### CODE REVIEW

**Comment by justinh-rahb** [comment]
This is amazing, I need to take a deeper dive to see just how you pulled this off, and get the documenting process going 😝 Same for the `config.json` feature.

**Comment by justinh-rahb** [comment]
So it took me a minute to figure out this flow: first you need to have a text model (doesn't matter which one) generate you a prompt, and then you can turn _that_ response into an image:

Screenshot 2024-02-22 at 1 17 29 PM

**Comment by SurvivaLlama** [comment]
What is a good way to generate the prompt?

**Comment by spammenotinoz** [comment]
Thank-you this is really good.

**Pull request merged**
