### PR TITLE
Better ollama load balancing

### PR DESCRIPTION
**Pull request by asedmammad**
## Pull Request Checklist

- [X] **Description:** Briefly describe the changes in this pull request.
- [X] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation?
- [ ] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?

---

## Description

This introduces a load balancer scheme in ollama app of the backend, resolving issue #1081. The implementation allows setting different strategies in the `.env` file, with support for RoundRobin and WeightedRoundRobin currently available.

---

### Added

- Implemented load balancer scheme for ollama backend

- Added RoundRobin and WeightedRoundRobin strategies

- Configured strategies in `.env.example` file for easy customization

### CODE REVIEW

**Comment by asedmammad** [comment]
We might consider adding the ability to change the strategy, weight values and other parameters directly through the UI. This would allow users to easily configure the load balancer settings without needing to modify the `.env` file.

**Comment by hchasens** [comment]
Does this take into account task affinity (model affinity) for model types? 

Ollama requires time to load in new models, so it makes sense to send requests of the same model to the same server. In this way you can create and manage task affinity. For example, if you have two requests going to phi3 and two going to llama3, you're going to want to sort them by type so that both phi3 requests end up at the same server. If a server has to regularly switch between models that'll create a lot of unnecessary overhead (especially if you have limited VRAM or a large model library). You might be able to reduce a bit of overhead by using a session persistence (would only work for low user counts), but you ideally want a model aware load balancer that can dynamically address a set of model requests of q types to a bank of n servers (even better if you can sort the models by size and group smaller models together on a single server). 

Apologies if you've already solved this. I haven't looked over the whole PR, but the problem is an interesting one. I'm busy for the next two weeks but if this hasn't been address yet (or by then) I'd be happy to look into creating an algorithm with you to address this.

**Comment by asedmammad** [comment]
@hchasens 
I was not available in the past few weeks. Your suggestion seems a great idea, and could be a valuable addition to the load balancer. The PR in it's current state does not implement that. We could definitely add it as another load balancing algorithm alongside the ones currently available in the PR.
If you're still available and willing, I'd be happy to collaborate with you on implementing this feature.

**Comment by hchasens** [comment]
@asedmammad I've also been unavailable the last few weeks. I'm still interested in working on this though.

**Pull request closed without merging**
