### PR TITLE
Add default voice setting and apply to chat

### PR DESCRIPTION
**Pull request by yeahdongcn**
A new tab is added to settings and the end-user can select one's favorite voice now.

Please see the screenshot.
Screenshot 2024-01-25 at 15 09 01

Testing done:
1. Select `Default` in voice settings -> click the speaker icon -> ✔
2. Select `Rocko (English (United States))` in voice settings -> click the speaker icon -> ✔

### CODE REVIEW

**Comment by yeahdongcn** [comment]
BTW, I reuse the speaker icon on the tab. It would be good if one could help to create a new icon.

**Comment by tjbck** [comment]
Amazing stuff, Thanks for the PR! I fixed and refactored some code, please try it out and let me know if it works as intended on your end!

**Comment by yeahdongcn** [comment]
> Amazing stuff, Thanks for the PR! I fixed and refactored some code, please try it out and let me know if it works as intended on your end!

Thanks for the review and refactoring! Everything works as expected.

**Comment by tjbck** [comment]
Good to hear! everything LGTM, Thanks!

**Pull request merged**
