### PR TITLE
feat: Supports making requests to the Automatic1111 backend when running with the --api-auth parameter

### PR DESCRIPTION
**Pull request by FuturePrayer**
# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [x] **Testing:** Have you written and run sufficient tests for validating the changes?
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [x] **Prefix:** To cleary categorize this pull request, prefix the pull request title, using one of the following:
  - **BREAKING CHANGE**: Significant changes that may affect compatibility
  - **build**: Changes that affect the build system or external dependencies
  - **ci**: Changes to our continuous integration processes or workflows
  - **chore**: Refactor, cleanup, or other non-functional code changes
  - **docs**: Documentation update or addition
  - **feat**: Introduces a new feature or enhancement to the codebase
  - **fix**: Bug fix or error correction
  - **i18n**: Internationalization or localization changes
  - **perf**: Performance improvement
  - **refactor**: Code restructuring for better maintainability, readability, or scalability
  - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
  - **test**: Adding missing tests or correcting existing tests
  - **WIP**: Work in progress, a temporary label for incomplete or ongoing work

# Changelog Entry

### Description

- Possibility to mark requests to the AUTOMATIC1111 backend which running with `--api-auth` parameter.

### Added

- Add an optional configuration item AUTOMATIC1111_API_AUTH in Admin Panel and the .env file.

---

### Additional Information

- [Reference any related issues, commits, or other relevant information]](https://github.com/open-webui/open-webui/discussions/3310)

### Screenshots or Videos

image
image
image
image

### CODE REVIEW

**Comment by tjbck** [comment]
LGTM, Thanks!

**Comment by xiaoxiongweihu** [comment]
Why can't I save it and keep loading
image

**Comment by FuturePrayer** [comment]
> Why can't I save it and keep loading image

没有复现出你所说的问题，是否可以提供更多信息？如是否有报错日志、stable diffusion webui配置信息等

**Comment by xiaoxiongweihu** [comment]
我使用的是Docker安装的Open WebUI，然后SD使用的是秋叶的一键安装包，我开启了API功能，并设置了API账号密码，但是在Open WebUI里按照你图片的尝试保存，就是一直转圈，保存不了，也没有出现SD绘画模型的选项

**Comment by FuturePrayer** [comment]
尝试使用ip地址而不是localhost看看，尝试前先修改下防火墙设置，放行7680端口-------- 原始邮件 --------发件人： xiaoxiongweihu ***@***.***>日期： 2024年6月30日周日 19:24收件人： open-webui/open-webui ***@***.***>抄送： FuturePrayer ***@***.***>, Author ***@***.***>主    题： Re: [open-webui/open-webui] feat: Supports making requests to the Automatic1111 backend when running with the --api-auth parameter (PR #3328)
我使用的是Docker安装的Open WebUI，然后SD使用的是秋叶的一键安装包，我开启了API功能，并设置了API账号密码，但是在Open WebUI里按照你图片的尝试保存，就是一直转圈，保存不了，也没有出现SD绘画模型的选项

**Comment by xiaoxiongweihu** [comment]
image
comfuui 和sd都试了，还是转圈，如果愿意的话，可以帮我看看吗？十分感谢

**Pull request merged**
