### PR TITLE
feat: Add support for routing LLM backend api requests to the same instance among multiple replicas

### PR DESCRIPTION
**Pull request by asrinivasanTT**
# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [ ] **Testing:** Have you written and run sufficient tests for validating the changes?
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [x] **Prefix:** To cleary categorize this pull request, prefix the pull request title, using one of the following:
  - **BREAKING CHANGE**: Significant changes that may affect compatibility
  - **build**: Changes that affect the build system or external dependencies
  - **ci**: Changes to our continuous integration processes or workflows
  - **chore**: Refactor, cleanup, or other non-functional code changes
  - **docs**: Documentation update or addition
  - **feat**: Introduces a new feature or enhancement to the codebase
  - **fix**: Bug fix or error correction
  - **i18n**: Internationalization or localization changes
  - **perf**: Performance improvement
  - **refactor**: Code restructuring for better maintainability, readability, or scalability
  - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
  - **test**: Adding missing tests or correcting existing tests
  - **WIP**: Work in progress, a temporary label for incomplete or ongoing work

# Changelog Entry

### Description

When multiple instances of vLLM/OLLAMA are deployed behind a loadbalancer, sticky sessions are enabled in the load balancer to route requests from a client to the backend it originally hit to ensure KV-Cache reuse. One way to implement sticky sessions is via a cookie that the loadbalancer sends to the client.

This adds support for setting an env var named PASSTHROUGH_SESSION_COOKIES that stores a comma separated list of cookie names. Open-Webui already sends back any cookies it receives from the LM backend to the browser. If this var is set, any cookies matching this names in this list that it receives from the browser in subsequent requests will be forwarded on to the LM backend

### Added

- Adds an env var `PASSTHROUGH_SESSION_COOKIES` that is set at runtime. This contains a list of cookie names to passthrough to the LLM backend 

### Breaking Changes

---

### Additional Information
- Implements https://github.com/open-webui/open-webui/discussions/6857
- Tested both OpenAI backend(using vLLM) and Ollama backend and observed that all requests go to the same replica when this feature is enabled
- Made sure that the following tests defined within github actions passed - `format_backend.yaml`, `format-build-frontend-yaml`. `ingegration-test.yaml` failed [here](https://github.com/asrinivasanTT/open-webui/actions/runs/11733096285) but it looks like that was due to the website responding slowly and not related to this commit
- Not sure what extra tests to add for this as it's difficult to test without a multi replica LLM api backend setup and a loadbalancer
- Do I need to add anything to the docs repo as well, documenting this env var?

### CODE REVIEW

**Comment by asrinivasanTT** [comment]
@tjbck Any reason you marked the PR as draft? It is ready for review and your comments are appreciated.

I rebased on top of the latest changes to dev and pushed it right now

**Comment by asrinivasanTT** [comment]
@tjbck Any reason you closed this PR? If something been pushed recently to support this kind of a feature, please let me know.

**Comment by rreece** [comment]
@tjbck can we please re-open this PR and discuss what it would take to get it merged?

I am working with @asrinivasanTT, and his changes are important for us to use "sticky sessions" so that a load balancer sends requests from the same session to the same pod, to efficiently re-use kv-cache.

**Comment by tjbck** [comment]
See here: https://github.com/open-webui/open-webui/discussions/6857#discussioncomment-11323807

**Comment by asrinivasanTT** [comment]
To accomplish this, we need to do the following:
1. Retrieve a header/cookie with a particular name from the incoming request from the user's web browser
2. Add this cookie to the headers of the outgoing request to the LLM backend
3. If the response contains an updated version of this cookie, send it back to the user's browser

Using Pipes, we can accomplish step 2. Pipes do not have the ability to read the headers from the incoming request (1). They also do not have the ability to send back custom headers to the user (3). 

openwebui already seems to do step 3 on it's own. However, if we use a custom pipe, then I think that the logic that handles sending a request to LLM backend is overriden with the logic in the pipe, so we lose out on the "sending headers back to the user" functionality that is already present.

Filters have the ability to run code before and after processing a request, but only affect the body of the request.

This cookie we need to send back to the user is a specific cookie generated by the loadbalancer. We know the name of the cookie, but its' value is a random hash of some state that the loadbalancer tracks. One option I was thinking of was to add this to the state of the chat/session that openwebui stores, but this would require a lot more work. Another option is to use the seesion_id that openwebui stores and configure the loadbalancer to use that as the session cookie somehow.. I will look into whether that is possible.

I appreciate your comments on this issue so far @tjbck. I was wondering if you could review what I've written up here and share any thoughts you have. It seems to me like what I want to accomplish isn't possible using Functions alone.

**Pull request closed without merging**
