### PR TITLE
💄 Limit the size and number of uploaded files on the front-end to opt…

### PR DESCRIPTION
**Pull request by Yanyutin753**
# Pull Request Checklist

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [x] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [x] **Testing:** Have you written and run sufficient tests for validating the changes?
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?

# Changelog Entry

### 1. During the file upload process, initialize the file first, so that the response is faster during the upload process. 

https://github.com/user-attachments/assets/3fb18878-1453-4920-8cad-4cbda5cb272c

### 2. Environment variables `RAG_MAX_FILE_COUNT` and `RAG_MAX_FILE_SIZE` are also set to limit the maximum size and number of files that users can upload per session, while allowing administrators to freely adjust these values. 

image

### 3. By adjusting the front end, we can make the front end upload files, display the size of each file, and adapt to previous files, which do not display the size of the file

image

image

#### Warning

image

image

### CODE REVIEW

**Comment by tjbck** [comment]
I appreciate the PRs, but there's too many changes in this one PR, I'd greatly appreciate if you could make atomic PRs! Thanks!

**Comment by Yanyutin753** [comment]
Ok ， I'll upload them one by one, and then post the next one after you' ve reviewed it!

**Comment by atgehrhardt** [comment]
Heads up, I know you are working on chunking this up a bit into more manageable PRs, but one thing we noticed was that there are duplicate implementations of the file ingestion process in onDrop and the on:change of the file input.

This is a result of the original implementation, however, it would be best to merge these into a single function that both events are able to call. This will avoid duplicate implementation logic.

**Comment by Yanyutin753** [comment]
> Heads up, I know you are working on chunking this up a bit into more manageable PRs, but one thing we noticed was that there are duplicate implementations of the file ingestion process in onDrop and the on:change of the file input.
> 
> 
> 
> This is a result of the original implementation, however, it would be best to merge these into a single function that both events are able to call. This will avoid duplicate implementation logic.

Thank you very much. I'll take note of that later

**Pull request closed without merging**
