### PR TITLE
feat: db migration

### PR DESCRIPTION
**Pull request by tjbck**
Extension of #3327

### CODE REVIEW

**Comment by tjbck** [comment]
@jonathan-rohde Encountering this issue:
image

**Comment by tjbck** [comment]
@jonathan-rohde One thing we should test before merging this to dev/main is verifying update to 0.3.8 work without any problem from other version like 0.2.0 when we didn't have supports for functions. I'd greatly appreciate if you could verify this!

**Comment by jonathan-rohde** [comment]
@tjbck This will be most likely not working. The initial database migration of alembic is not throwing any errors during migration, if a table already exists. The existing table will just be ignored.

However if between the older version (e.g. 0.2.0) a peewee-migration was adding new columns to existing tables, this change is not reflected in the alembic migration. One feature I have in mind which will cause such a conflict: oauth login.

That was the reason why I flagged it as "breaking change"
In theory it should be possible to not create just one initial migration but recreate all the steps that peewee migration had. But it will be very tedious.

**Comment by tjbck** [comment]
If restoring peewee migrations to alembic is all we need, that's what we'll have to do 😅

**Comment by tjbck** [comment]
Perhaps we could add back in the old peewee migration code, and conditionally execute the peewee migration code only if `migratehistory` table is detected then bring the database up to the latest version, then remove (or rename) the`migratehistory` table to indicate the database has been successfully migrated?

**Comment by Peter-De-Ath** [comment]
I have been trying this out on an existing install from latest dev branch using postgres database.

Generally it seems okay, but I am experiencing "random"  lockups, I haven't pinpointed taking any particular action to trigger this behavior yet

Error Message on backend.
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)

This doesn't seem to recover without a restart of owui

**Review by tjbck — COMMENTED** [review]
@jonathan-rohde https://github.com/open-webui/open-webui/pull/3595#issuecomment-2207168583 seems like it might be related to [this change](https://github.com/open-webui/open-webui/pull/3595/commits/da403f3e3cf9ce700da2fdb477e0bdfc4794d37d), I'm curious to know what the reason was behind this decision for opting-in for session factory instead of context manager. Just want to make sure that I won't be breaking anything if I were to update the code to use:

```py
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
```

I appreciate the help as always!

**Comment by jonathan-rohde** [comment]
The session factory has the advantage, that within one common context, for example a thread, you get the same session and you are able to chain the operations within one transaction.
You will have more trouble doing it with a context manager. Although at the moment there are hardly any combined actions within one transaction in the peewee implementation.

**Pull request merged**
