### PR TITLE
feat: added ability to set user name for federated auth

### PR DESCRIPTION
**Pull request by JohnTheNerd**
# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [x] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [x] **Testing:** Have you written and run sufficient tests for validating the changes?
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [x] **Prefix:** To cleary categorize this pull request, prefix the pull request title, using one of the following:
  - **BREAKING CHANGE**: Significant changes that may affect compatibility
  - **build**: Changes that affect the build system or external dependencies
  - **ci**: Changes to our continuous integration processes or workflows
  - **chore**: Refactor, cleanup, or other non-functional code changes
  - **docs**: Documentation update or addition
  - **feat**: Introduces a new feature or enhancement to the codebase
  - **fix**: Bug fix or error correction
  - **i18n**: Internationalization or localization changes
  - **perf**: Performance improvement
  - **refactor**: Code restructuring for better maintainability, readability, or scalability
  - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
  - **test**: Adding missing tests or correcting existing tests
  - **WIP**: Work in progress, a temporary label for incomplete or ongoing work

# Changelog Entry

### Description

this PR adds an optional environment variable named `WEBUI_AUTH_TRUSTED_NAME_HEADER`, which sets the user's name to the contents of that header. this only happens if the user is just being created, just like how the trusted e-mail header works.

if the environment variable or header is not present, we fall back to the original behavior which is to re-use the user e-mail address.

### Added

- Adds a new optional environment variable

### Changed

None

### Deprecated

None

### Removed

None

### Fixed

N/A

### Security

N/A

### Breaking Changes

N/A, it will fall back to original behavior if the header or environment variable does not exist.

---

### Additional Information

The GitHub actions are failing due to uppercase characters in my username, so to test, I first fixed that (#3204), merged both changes in a separate branch, and merely ran the actions. The images are available in the images containing `ci-cd-test` in [the Packages section of my fork](https://github.com/JohnTheNerd/open-webui/pkgs/container/open-webui/versions). I deployed the resulting image to my homelab and it's working fine so far.

Documentation changes are at https://github.com/open-webui/docs/pull/117 and the discussion post is #3201 .

### Screenshots or Videos

N/A

### CODE REVIEW

**Comment by tjbck** [comment]
#2706 seems related. I just won't merge PRs that I can't really test so if you could help out with this that'd be great!

**Comment by JohnTheNerd** [comment]
Happy to test it for you, but I will first wait for #3204 to be merged because it's quite difficult for me to build custom images including commits from different repositories to deploy to my homelab. The images I built for testing are merely cherry-picked and I run the GitHub actions as-is.

**Comment by JohnTheNerd** [comment]
Alternatively, I can simply include a screen recording of me running the branch from this PR in a comment right here and showing that the functionality works. Whichever works better for you, really.

**Comment by JohnTheNerd** [comment]
now that the respective PR is merged, I can (much more easily) build stuff. would you prefer I demonstrate that this PR or #2706 functions properly? is a screen recording okay, or would you prefer something else?

**Comment by tjbck** [comment]
Screenrecording works for me! Let's add @sample as a coauthor as well!

**Comment by JohnTheNerd** [comment]
rebased it off dev, and added @sample as a co-author. just waiting for the image build before I demonstrate

**Comment by JohnTheNerd** [comment]
after lots of screaming at ffmpeg, i finally got the screen record small enough to fit in a comment lol
[output2.webm](https://github.com/open-webui/open-webui/assets/9657143/2030c936-9059-4655-a4ec-b93c30345eaa)

**Comment by tjbck** [comment]
LGTM, Thanks!

**Pull request merged**
