### PR TITLE
General logistic improvements

### PR DESCRIPTION
**Pull request by dnviti**
- Fixed .gitignore which was too generic.
- Separated docker-compose-yaml in 3 parts, main is docker-compose.yaml, added 2 more: docker-compose.gpu.yaml and docker-compose.api.yaml to be able to override and better configure the compose.
- Added a complete script to allow user to control composes configuration "run-compose.sh"

Note: the script "run-compose.sh" contains a function (for linux) to automatically detect the GPU installed on the host system, i'm not be able to test it on AMD and Intel GPUs cause i do not have any. On Nvidia works flawlessly.

### CODE REVIEW

**Comment by dnviti** [comment]
Closing this i made a little mistake, correcting it and recreating a pr

**Comment by tjbck** [comment]
Hi, Thanks for the PR! This is amazing, I'll first merge the two previous PRs and merge this one. Thanks a lot!

**Comment by dnviti** [comment]
> Hi, Thanks for the PR! This is amazing, I'll first merge the two previous PRs and merge this one. Thanks a lot!

I made a little mistake on the script, i'm going to quickly correct it and repost

**Comment by tjbck** [comment]
No worries, in the meantime, I'll merge the other PRs!

**Pull request closed without merging**
