### PR TITLE
feat: Add netcat to Dockerfile for healthcheck

### PR DESCRIPTION
**Pull request by Trimutex**
Adds the netcat-openbsd package while building the image to allow creating a healthcheck.

I couldn't find anything related to Docker's healthcheck implemented. Ollama has commits to use curl and I'm not sure if there's any advantage to use it for healthcheck instead.

### CODE REVIEW

**Comment by tjbck** [comment]
Not sure why/how this is useful, could you elaborate a bit more on its use cases? Thanks!

**Comment by Trimutex** [comment]
This would mainly be for monitoring purposes for the container. The healthcheck would be for if the container was up, but the application was not working or having issues and did not successfully open the port for connections. 

Perhaps adding the healthcheck as a part of the image by default would make more sense?

Also any monitoring services would also be able to match the criteria of utilizing the healthcheck on the container.

**Comment by tjbck** [comment]
Ideally I'd want to keep the image size as small as possible, so I'm a bit hesitant to merge this. Could you also check the container size for us? Thanks!

**Comment by Trimutex** [comment]
I definitely understand that! This is why I chose netcat-openbsd over netcat-traditional or curl as it seemed like the smallest addition.

As for the container size, I'm not exactly sure which part about the container that you want so I will post the image and size of an active container (non-virtual amount) below.

Without netcat-openbsd:
active container size | image size
-- | -- 
655kB | 2.09GB

With netcat-openbsd:
active container size | image size
-- | --
655kB | 2.09GB

Pulled from ghcrio (main):
active container size | image size
-- | --
650kB | 1.91GB

I'm not too clear as to why my locally created image differs so much from the main image though as I haven't changed anything else. The container without netcat that I built from my own image was confirmed to not have netcat internally.

**Comment by tjbck** [comment]
Doesn't seem all that much an increase. LGTM, Thanks!

**Pull request merged**
