### PR TITLE
changed: packaging for publishing

### PR DESCRIPTION
**Pull request by tcztzy**
…d relative.

## Pull Request Checklist

- [x] **Target branch:** Pull requests should target the `dev` branch.
- [x] **Description:** Briefly describe the changes in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [x] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [x] **Testing:** Have you written and run sufficient tests for the changes?
- [x] **Code Review:** Have you self-reviewed your code and addressed any coding standard issues?

---

## Description

Packaging `open-webui` as a Python package with minimum modification. It is not [rye](https://github.com/astral-sh/rye)-only, any package support PEP 517 can build and package at the root of this project.

I also noticed that `openwebui` is currently not token in pypi.org, maybe it is a better choice?

after packaging and publishing to pypi, we can declare namespace package as plugin system, then langchain agent support could be easily implemented.

---

### Added

- Python packaging

### Changed

- Use file relative (relative path to `backend/config.py`) instead of pwd relative path in `backend/config.py`, so it can start backend at the root directory of this project.

---

### Additional Information

- now we can produce the wheel file and sdist for publishing
```console
$ rye build   # file will place at dist/
$ rye publish  # after you config pypi account, you can upload the backend file to Pypi.org
```
- `backend/requirements.txt`, `backend/dev.sh`, `backend/start.sh` and `backend/start_windows.bat` now can be removed, but weather delete them or not is depend on you.

### CODE REVIEW

**Comment by tcztzy** [comment]
related to #1885

**Comment by tjbck** [comment]
@tcztzy Are you on our discord server? I'd prefer to setup a high bandwidth communication channel to configure this.

**Comment by tcztzy** [comment]
> @tcztzy Are you on our discord server? I'd prefer to setup a high bandwidth communication channel to configure this.

OK, now I login in discord as `tcztzy`

**Comment by tcztzy** [comment]
Now I realize following features:

1. `pip install open-webui && open-webui serve`
2. Add a `ci.yml` github workflow, every time main branch has pull event, it will release to pypi.org.

**Comment by mak448a** [comment]
You may want to claim both `open-webui` and `openwebui` just in case someone decides to post malware to the package.

**Pull request merged**
