### PR TITLE
Support multiple OpenAI Compatible APIs

### PR DESCRIPTION
**Pull request by NinjaPerson24119**
Adds support for hitting OpenAI compatible UIs.

The backend uses the ENV as a simple key:value store, so to store an array of compatible APIs, I stored them as a `;` separated list like: `localhost1;localhost2;localhost3`

The backend/frontend implementations for OpenAI Compat are mostly copy pastes of the original OpenAI implemenation, with the changes:
- Compat needs model labels because we don't have a provider to query them from
- Removed anything that looks specific/proprietary to OpenAI (e.g. sound/vision)

I decided to add a 3rd pathway for `OPENAI_COMPAT` instead of augmenting `OPENAI` because we probably want to allow the original `OPENAI` pathway to be easily extended for any changes to the proprietary API / features.

There's probably other ways this could have been built, but this was what came to me as I was reading the code for the first time + have never touched Svelte before.

# Check
image
image
image
backend logs
```
INFO:     127.0.0.1:42702 - "GET /api/v1/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:42718 - "GET /themes/rosepine-dawn.css HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:42674 - "GET /themes/rosepine.css HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:42702 - "GET /api/v1/auths/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:42702 - "GET /api/v1/modelfiles/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:42702 - "GET /api/v1/prompts/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:42702 - "GET /api/v1/documents/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:42702 - "GET /api/v1/chats/tags/all HTTP/1.1" 200 OK
INFO:     127.0.0.1:42674 - "GET /ollama/api/version HTTP/1.1" 200 OK
INFO:     127.0.0.1:42702 - "GET /ollama/api/tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:42702 - "GET /user.png HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:42702 - "GET /api/v1/chats/e20e5d8f-321a-4134-b75f-0dcc29ad5303 HTTP/1.1" 200 OK
INFO:     127.0.0.1:42674 - "GET /api/v1/chats/ HTTP/1.1" 200 OK
https://api.openai.com/v1/models <KEY_REDACTED>
Error loading request body into a dictionary: Expecting value: line 1 column 1 (char 0)
INFO:     127.0.0.1:42718 - "GET /openai/api/models HTTP/1.1" 200 OK
INFO:     127.0.0.1:42702 - "GET /assets/fonts/Arimo-Variable.ttf HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:42674 - "GET /api/v1/chats/e20e5d8f-321a-4134-b75f-0dcc29ad5303/tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:42702 - "GET /openai_compat/api/label HTTP/1.1" 200 OK
Getting model from JSON body:  llama.cpp
Found model at index:  0
URL List:  ['http://localhost:8000/v1', 'http://localhost:8001/v1']
Hitting OpenAI compat URL:  http://localhost:8000/v1/chat/completions
INFO:     127.0.0.1:60694 - "POST /openai_compat/api/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:60694 - "POST /api/v1/chats/e20e5d8f-321a-4134-b75f-0dcc29ad5303 HTTP/1.1" 200 OK
INFO:     127.0.0.1:60694 - "GET /api/v1/chats/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:60694 - "GET /api/v1/chats/ HTTP/1.1" 200 OK

```

### CODE REVIEW

**Comment by NinjaPerson24119** [comment]
@tjbck @justinh-rahb

**Comment by displague** [comment]
Relates to https://github.com/ollama-webui/ollama-webui/issues/278

**Comment by explorigin** [comment]
This is a start. Here are some issues I see with this:

- Can you delete entries in the UI?
- Using environment variables is not a good permanent store. Other things are stored in memory where there should be a setting store (like the disable registration flag). I'd like for that situation to get better rather than worse.
- The visual style does not complement the existing dialog.
- What is the 3rd "None" column for (API token?). Probably don't need to list that in the list of endpoints.
- With OpenAI, you can query models. Does this also query models? What happens if a model is listed on 2 endpoints? Which one wins?

**Comment by NinjaPerson24119** [comment]
- you cannot, I didn't add a remove button
- you're right, but the odds of getting an approval on a PR that redoes the entire state management is 0 without prior communication 
- yes it's barebones
- yes that's the API key which some endpoints might require. it could be different for different APIs
- it does not query endpoints to enumerate models

The goal was just to get a barebones implementation and see if the maintainer actually looks at the PR, otherwise it's not worth my time.

**Comment by tjbck** [comment]
Thanks for the PR! I didn't have the time to review this PR yet but it seems promising! Also, it seems like there are quite a bit of conflicts so it's probably best to cherry-pick some code and open up a new PR, I'll actively start taking a look in a few days!

**Comment by NinjaPerson24119** [comment]
It might take me a bit to get back to this, so feel free to take over the code if you want.

**Comment by tjbck** [comment]
Implemented this feature with #1070 based on this PR + refactoring, Thanks for the effort!

**Comment by Bebo0** [comment]
This worked for me, I'm able to run openai models and a local llama.cpp server (through LM Studio).

Now I have gpt models thru OpenAI's api AND llama3 70B running side by side.

Note: if you're running open-webui through docker, make sure to use your LAN ip address in the admin panel to access the llama.cpp server! Add http:// and /v1 and it'll work

image

image

**Pull request closed without merging**
