### PR TITLE
build: Adding ability to install requirements from frontmatter for tools and functions

### PR DESCRIPTION
**Pull request by JTHesse**
# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [x] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [x] **Testing:** Have you written and run sufficient tests for validating the changes?
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [x] **Prefix:** To cleary categorize this pull request, prefix the pull request title, using one of the following:
  - **BREAKING CHANGE**: Significant changes that may affect compatibility
  - **build**: Changes that affect the build system or external dependencies
  - **ci**: Changes to our continuous integration processes or workflows
  - **chore**: Refactor, cleanup, or other non-functional code changes
  - **docs**: Documentation update or addition
  - **feat**: Introduces a new feature or enhancement to the codebase
  - **fix**: Bug fix or error correction
  - **i18n**: Internationalization or localization changes
  - **perf**: Performance improvement
  - **refactor**: Code restructuring for better maintainability, readability, or scalability
  - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
  - **test**: Adding missing tests or correcting existing tests
  - **WIP**: Work in progress, a temporary label for incomplete or ongoing work

# Changelog Entry

### Description

This PR adds the ability to install extra Python modules at runtime. When EXTRA_MODULES is set, this script will load and install the specified modules using pip.
**Example Use Case:**
To use this feature, simply set the `EXTRA_MODULES` environment variable. For example:
```bash
EXTRA_MODULES="module1 module2"
```

### Added

- EXTRA_MODULES argument for tool/function dependencies

### Changed

- [List any changes, updates, refactorings, or optimizations]

### Deprecated

- [List any deprecated functionality or features that have been removed]

### Removed

- [List any removed features, files, or functionalities]

### Fixed

- [List any fixes, corrections, or bug fixes]

### Security

- [List any new or updated security-related changes, including vulnerability fixes]

### Breaking Changes

- **BREAKING CHANGE**: [List any breaking changes affecting compatibility or functionality]

---

### Additional Information

- #4051

### Screenshots or Videos

- [Attach any relevant screenshots or videos demonstrating the changes]

### CODE REVIEW

**Comment by michaelpoluektov** [comment]
I like this. Then we can delete all of the unused stuff from requirements.txt and have an even slimmer image.

I might be wrong but I don't think `langfuse`, `anthropic` or `google-generativeai` are used anywhere in the backend without functions.

Another option might be the ability to allow functions to install modules on import, but this would need to be done with a lot of caution just in case someone pushes a function installing a malicious module, because people would likely not check for that. Maybe have a list of allowed "safe" modules that can be imported?

**Comment by michaelpoluektov** [comment]
I would say "just use pipelines" but since so much of the functionality in functions is currently not supported by pipelines (`__event_emitter__`, `__event_call__`) I think this is a good option.

**Comment by JTHesse** [comment]
Yes, good idea! 
I just wanted to make sure that I don't have to install the same modules after every new release 😄

**Comment by tjbck** [comment]
I'm wondering if we could have something similar to https://github.com/open-webui/pipelines/pull/192 here?

**Comment by JTHesse** [comment]
This should do it ;)

**Comment by tjbck** [comment]
@JTHesse is this PR tested?

**Comment by tjbck** [comment]
Great to hear, merging to dev now but I'd greatly appreciate if you could provide some video demos as well, Thanks in advance!

**Pull request merged**
