### PR TITLE
feat: New admin setting to display or hide citations in chat messages

### PR DESCRIPTION
**Pull request by DiegoRodriguez83**
# Pull Request Checklist

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [x] **Testing:** Have you written and run sufficient tests for validating the changes?
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [x] **Prefix:** To cleary categorize this pull request, prefix the pull request title, using one of the following:
  - **BREAKING CHANGE**: Significant changes that may affect compatibility
  - **build**: Changes that affect the build system or external dependencies
  - **ci**: Changes to our continuous integration processes or workflows
  - **chore**: Refactor, cleanup, or other non-functional code changes
  - **docs**: Documentation update or addition
  - **feat**: Introduces a new feature or enhancement to the codebase
  - **fix**: Bug fix or error correction
  - **i18n**: Internationalization or localization changes
  - **perf**: Performance improvement
  - **refactor**: Code restructuring for better maintainability, readability, or scalability
  - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
  - **test**: Adding missing tests or correcting existing tests
  - **WIP**: Work in progress, a temporary label for incomplete or ongoing work

# Changelog Entry

### Description

- Some users may need to use the Open WebUI exclusively for private knowledge. In this case, with only one model configured, they might prefer not to display citations in yours chat responses.

### Added

- New admin setting to display or hide citations in chat messages: Show citations in messagens

### Changed

- Added new admin config

### Fixed

- Small i18n pt-BR adjustments

### Screenshots or Videos
https://github.com/user-attachments/assets/5742d9cd-8567-4180-8047-9d70f6c5a500

### CODE REVIEW

**Comment by flefevre** [comment]
Quick question, should be located the button in the admin panel in the general tab or in the user interface tab?

**Comment by DiegoRodriguez83** [comment]
> Quick question, should be located the button in the admin panel in the general tab or in the user interface tab?

Initially I thought about a global display or not, but it would also be interesting just for the user.

**Comment by tjbck** [comment]
We'd want this applied to models individually, I'll keep this PR open for reference but I'll personally take a look at this.

**Comment by tjbck** [comment]
Closing in favour of 09c6e4b92fb744631cfbb250ea47d643d5b70595, Thanks!

**Pull request closed without merging**
