### PR TITLE
feat: Allow user groups to be managed by oauth

### PR DESCRIPTION
**Pull request by tarmst**
# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

Associated discussion post: https://github.com/open-webui/open-webui/issues/7102

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
  - I can add the environment variables to the docs once you guys have taken a look at this and are good with it
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
  - No new dependencies
- [ ] **Testing:** Have you written and run sufficient tests for validating the changes?
  - Tested locally, but did not write tests as I did not see other tests for oauth currently.
- [ ] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
  - I did not see any formatter specified anywhere, but will run one if you have one.
- [x] **Prefix:** To cleary categorize this pull request, prefix the pull request title, using one of the following:
  - **feat**: Introduces a new feature or enhancement to the codebase

# Changelog Entry

### Description

Added the ability to match user oauth groups to OpenWebUI groups with exactly the same names upon user login. This will also remove users from OpenWebUI groups if they are removed from an oauth group. 

This can be enabled by using: `'ENABLE_OAUTH_GROUP_MANAGEMENT=true'` in the docker compose file.
You can also change the name of the groups claim using `OAUTH_GROUPS_CLAIM=groups_name`.

### Added

- Added the ability to add users to OpenWebUI groups based on their oauth groups. This also works for groups that do not yet have saved permissions.

### CODE REVIEW

**Comment by tjbck** [comment]
Merging but more testing wanted here in general!

**Comment by sir3mat** [comment]
Ok, thank you for the tips!! 💯  I also created the groups in openwebui but it does not still working

**Comment by tarmst** [comment]
Alright I'll look into adding some logging for oauth that you can use. Will link PR when ready

**Comment by tarmst** [comment]
PR here: https://github.com/open-webui/open-webui/pull/9620

**Pull request merged**
