### PR TITLE
feat: Replace default UI font, Arimo to Inter

### PR DESCRIPTION
**Pull request by robertpiosik**
# Pull Request Checklist

# Changelog Entry

### Description

This PR replaces outdated "Arimo" font with modern "Inter".

### Added

- [List any new features, functionalities, or additions]

### Changed

- added ttf file of Inter
- removed ttf file of Arimo
- replaced references in CSS

Current font:
image

Inter:
image

### CODE REVIEW

**Comment by tjbck** [comment]
LGTM, Thanks!

**Comment by drupol** [comment]
Hi!

I'm genuinely interested to know motivation behind this PR.

**Comment by jackgraddon** [comment]
Could we add support for changing our own fonts? I need to use Noto for Japanese language support. Inter, nor the previous fonts, support Kana.

**Comment by rgaricano** [comment]
This font is under [SIL Open Font License 1.1](https://raw.githubusercontent.com/rsms/inter/v4.1/LICENSE.txt) 
https://rsms.me/inter/

> 2. Original or Modified Versions of the Font Software may be bundled, redistributed and/or sold with any software, provided that each copy contains the above copyright notice and this license. These can be included either as stand-alone text files, human-readable headers or in the appropriate machine-readable metadata fields within text or binary files as long as those fields can be easily viewed by the user

(arimo was [Apache License, Version 2.0](http://www.apache.org/licenses/LICENSE-2.0.html)  )

Is license notice updated?

**Pull request merged**
