### PR TITLE
fix: sort and fix backend imports

### PR DESCRIPTION
**Pull request by pascallim**
# Pull Request Checklist

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [x] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [x] **Testing:** Have you written and run sufficient tests for validating the changes?
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [x] **Prefix:** To cleary categorize this pull request, prefix the pull request title, using one of the following:

# Changelog Entry

### Description

- Fix imports by referencing to correct files. Sometimes imports are from different files and unused imports permit to make the whole application works but this is may break sometimes.

### Changed

- Refacto by sorting and removing unused imports
- Light refacto on some files

### Fixed

- Points import to correct python files to avoid weird behaviors in the future.

### CODE REVIEW

**Comment by pascallim** [comment]
@tjbck Do you think we can merge this soon? We will have a better base for backend python imports that will benefit all the other PRs ^^

**Comment by tjbck** [comment]
Is this PR tested?

**Comment by pascallim** [comment]
> Is this PR tested?

Just rebased and tested again !

**Comment by tjbck** [comment]
Merging this to dev but testing wanted again just in case! Thanks!

**Pull request merged**
