### PR TITLE
feat: configurable model name, description and vision capability

### PR DESCRIPTION
**Pull request by cheahjs**
## Pull Request Checklist

- [x] **Target branch:** Pull requests should target the `dev` branch.
- [x] **Description:** Briefly describe the changes in this pull request.
- [ ] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [ ] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [x] **Testing:** Have you written and run sufficient tests for the changes?
- [ ] **Code Review:** Have you self-reviewed your code and addressed any coding standard issues?

---

## Description

Adds the ability to set a custom display name, description, and the vision capability of a model via the web UI, which is then persisted into the database. 

image
image
image
image
image

A new field `custom_info` is injected into each model list API. An alternative implementation would be to override the model's `name` field, but would require additional mapping inside of the proxy endpoints.

If a model is marked as not vision capable,
1. Image uploads are disabled.
2. Any existing images that are in the current input are removed - but not any images that are already in the chat
3. If multiple models are selected, and not all of them are vision capable:
   1. A warning icon is added to image input warning about this
   2. An error toast is shown if a user still sends the prompt.

I've tested locally with Ollama and OpenAI endpoints, have not tested LiteLLM endpoints yet.

### Added

* **Model Customization:** Configure custom display names, descriptions, and vision capabilities for models. 
* **Image Input Validation:** Models marked as not vision-capable will reject or warn about image uploads.

### CODE REVIEW

**Comment by justinh-rahb** [comment]
rogan

LEGENDARY.

**Comment by tjbck** [comment]
About time we make `config.json` persistent as well, I'll investigate this.

**Comment by tjbck** [comment]
Also, it would be perfect if we could rename the fields like such:

```
{
  "id": "llama3:latest",
  "name": "Meta: Llama3 8B (Instruct, Q3, K, S)",
  "description": "Llama3 is a large language model trained on a diverse range of internet text.\nIt is capable of generating human-like text and answering a wide range of questions.",
  "vision_capable": false
},
```

**Comment by Yanyutin753** [comment]
It is so unbelievable. I've been waiting for a long time! @cheahjs i admire you so much!!!🤩🤩🤩

**Comment by arsaboo** [comment]
This is epic. I am assuming we can extend this (in a separate PR) to configure per-model context window, output tokens, etc.

**Comment by tjbck** [comment]
On second thought, we might want to save the model configs to our database to cover #665 as well. I'll keep this open in case I change my mind. I appreciate the effort as always 🙌

**Comment by tajchert** [comment]
Was this removed or finally not merged to master? It is a very useful feature but I don't see this functionality in the latest releases.

**Comment by justinh-rahb** [comment]
> Was this removed or finally not merged to master? It is a very useful feature but I don't see this functionality in the latest releases.

Merged a while back:

Screenshot 2024-07-09 at 6 24 21 PM

**Comment by tajchert** [comment]
Thanks! So it is in "Workspace" I was looking in "Settings" (I think original MR put it there but it has moved since then). Thanks :)

**Pull request merged**
