### PR TITLE
fix:Fixed layout issues in pwa mode

### PR DESCRIPTION
**Pull request by erickgodev**
# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [x] **Testing:** Have you written and run sufficient tests for validating the changes?
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [x] **Prefix:** To cleary categorize this pull request, prefix the pull request title, using one of the following:
  - **BREAKING CHANGE**: Significant changes that may affect compatibility
  - **build**: Changes that affect the build system or external dependencies
  - **ci**: Changes to our continuous integration processes or workflows
  - **chore**: Refactor, cleanup, or other non-functional code changes
  - **docs**: Documentation update or addition
  - **feat**: Introduces a new feature or enhancement to the codebase
  - **fix**: Bug fix or error correction
  - **i18n**: Internationalization or localization changes
  - **perf**: Performance improvement
  - **refactor**: Code restructuring for better maintainability, readability, or scalability
  - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
  - **test**: Adding missing tests or correcting existing tests
  - **WIP**: Work in progress, a temporary label for incomplete or ongoing work

# Changelog Entry

### Description

- Fixed vertical scrolling in PWA mode on iOS and Android. which was a usability issue when opening the settings
- Applied a temporary fix for the white background color in the app in PWA mode.

### Changed

- Fixed `app.html` so that the `body` is locked when in PWA mode, not affecting the refresh scroll on mobile and desktop.
- Partially fixed the problem with the app background in PWA mode that is completely white, even in dark mode.

---

### Additional Information

- The PWA background is gray, making it look better to the eye, but I will later implement a solution so that it changes dynamically with the theme.
- `position: fixed;` on `body `and `html `is not a problem since the layout is locked within the visible area. I have tested it on several devices and it does not cause any problems.

#### Before

353695673-9314fbb0-9ea6-4430-a0f6-1c63476cd58d

353695675-19056742-fa02-4bbf-85f9-74cf091eced9

#### after

353695991-98a1fec6-19c0-4023-90bd-55f8d5e44bfc

### CODE REVIEW

**Comment by thearyadev** [comment]
it may be better to set the colours and theme settings using the `manifest.json` (also needs to be linked in the html)
also i'd probably make the background `#121212`. i think that's the default chat background colour, i'd double check on that. 

i dont remember how openwebui is built and served, so i'm not sure if the manifest.json should go in `/backend/static` or `/static`. in the dev environment, `/static` works. 

i was going to open a pr for this last week, but decided not to bc i didnt want to fill the icons portion of this. 

`manifest.json`:
```json
{
  "name": "Open WebUI",
  "short_name": "Open WebUI",
  "icons": [],
  "start_url": ".",
  "background_color": "#121212",
  "theme_color": "#121212",
  "display": "standalone",
  "orientation": "portrait",
}
```

**Comment by erickgamer787** [comment]
I tried this on Android and it works but not on iOS, which is why I forced the background to be the default chat color.

**Comment by thearyadev** [comment]
> I tried this on Android but it doesn't work on iOS, that's why I forced the background to be the default chat color. now I saw it's a little off color but I think this was an old photo

thats so strange. i just tested it, and it works in some browsers, didn't work in chrome.

**Comment by erickgamer787** [comment]
where chrome desktop?

**Comment by thearyadev** [comment]
> where chrome desktop?

chrome android. just made a normal shortcut.

**Comment by erickgamer787** [comment]
wait are you with https or http

**Comment by erickgamer787** [comment]
PWA can only create app when it is in https

**Comment by tjbck** [comment]
Closing as I cannot reproduce any of the issues described here on my end. Feel free to advocate for this PR!

**Comment by erickgamer787** [comment]
Hi, what devices did you test it on? Vertical scrolling only happens in PWA mode on the iPhone, and you can only test it if the site is in https

**Comment by erickgamer787** [comment]
The Problem Happening
https://github.com/user-attachments/assets/2fd24d6e-0a9d-4f75-9cbe-29332d5686fc

**Comment by Yanyutin753** [comment]
> The Problem Happening
> 
> https://github.com/user-attachments/assets/2fd24d6e-0a9d-4f75-9cbe-29332d5686fc
> 
> the background is ultra white and the vertical scrolling is coming out of the viewport

“the background is ultra white” I have met

**Comment by thearyadev** [comment]
> Closing as I cannot reproduce any of the issues described here on my end. Feel free to advocate for this PR!

in my testing of pwa applications on ios both issues occur, body is scrollable causing the no-scroll-spring effect and top bar colour, as the above video shows.

**Comment by erickgamer787** [comment]
I've already noticed that this seems to be common in PWA on iOS, that's why I locked the body with fixed, and I already had a code to change the background colors depending on the time, but it was unstable, that's why I sent this temporary solution.

**Comment by erickgamer787** [comment]
strange I recompiled the app and my correction for the background is only working for safari strange but the spring effect works

**Comment by erickgodev** [comment]
here it is with the correction applied
ps: I was moving my finger up and down but I can't see it now since the iPhone doesn't have a pointer

https://github.com/user-attachments/assets/dad95d71-a6b2-4265-b7e9-2968379ebc48

and a preview of some remade animations

**Pull request closed without merging**
