### PR TITLE
[fix] for issue #2447 (OpenAI-like API fails when a redundant, empty assistant message is sent over)

### PR DESCRIPTION
**Pull request by AlyMobarak**
# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

**Before submitting, make sure you've checked the following:**

- [✅] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [✅] **Description:** 
- [✅] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [NO NEED] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [NO NEED] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [NO NEED] **Testing:** Have you written and run sufficient tests for validating the changes?
- [✅] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [✅] **Label:** fix

# Changelog Entry

### Description

I've noticed an issue with the UI described at issue https://github.com/open-webui/open-webui/issues/2447. After fiddling around for some time, I've come up with a really simple solution that doesn't require any major code refactoring or even a change in testing methods. I simply added a rule to filter messages before getting sent to OpenAI API and remove empty ones. I have no idea if the actual OpenAI API accepts this or not as I'm broke enough to not be able to buy the API and test on it, but it should work fine based on my ChatGPT free usage network monitoring.

I've tested it on my LM Studio OpenAI like server and it works like a charm now.. I'll be using my local image for the docker container (which was built successfully btw) until this change is hopefully upstream.

### Added

- N/A

### Changed

- N/A

### Deprecated

- N/A

### Removed

- N/A

### Fixed

- Filtered messages before getting sent to an OpenAI API or similar based on whether they have actual contents or not. This should not have any effects on what was previously working, but would make OpenAI APIs like LM Studio's work.

### Security

- N/A

### Breaking Changes

- N/A

---

### Additional Information

- Issue #2447 

### Screenshots or Videos

BEFORE:
Before Bug Fix, OpenWebUI Interface

AFTER:
Screenshot 2024-05-21 at 1 47 20 PM

### CODE REVIEW

**Comment by justinh-rahb** [comment]
This should already be fixed in `main` branch.

**Comment by AlyMobarak** [comment]
Oh..? But I really just checked right before writing my fix.. I don't know I'm just grateful it now works.... but can you honestly take a moment and review it? I don't want to be stuck with the current version for this small thing. Or as you said I could just workaround using the memory which I don't really want but hey it might fix it so yeah. Thank you!

**Comment by justinh-rahb** [comment]
I'm somewhat certain this is the same issue I'm thinking of, if enabling memory causes things to work normally again with unmodified code then that would probably be the case. It was _supposed_ to have been fixed already but I suppose it's also possible we missed something. Let us know if you can test a re-pulled `main` or `dev` unmodified with and without memory enabled.

**Comment by AlyMobarak** [comment]
Yup. I have tested it and the images are provided in the issue. I've also references the two lines of code I changed. Literally two lines fixes this, its simple just like you said.. so simple that you may've missed it 😊! Here they are just in case,
332342901-88747ca3-fe11-4f2c-8aeb-b6284ec5610d-2
332343357-b406c42c-ed90-4673-9ad3-84d7677ea6ff
332353907-65fae7d1-24ec-4261-98c1-3a58e3c7ecc5

**Comment by AlyMobarak** [comment]
Screenshot 2024-05-21 at 2 28 24 PM

Also here's the server logs output after filtering.

**Comment by nwtgck** [comment]
Hi,

I have the same issue at the current main (3355577bac260d5f4ffb0d84a78bacd7be236c20) where memory is both ON and OFF.
image

This PR fixes the issue 👍 :
image

**Comment by tjbck** [comment]
LGTM, thanks!

**Pull request merged**
