### PR TITLE
chore: Fix some PEP issues in the backend

### PR DESCRIPTION
**Pull request by franciscovelez**
# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [ ] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [ ] **Testing:** Have you written and run sufficient tests for validating the changes?
- [ ] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [x] **Label:** To cleary categorize this pull request, assign a relevant label to the pull request title, using one of the following:
  - **BREAKING CHANGE**: Significant changes that may affect compatibility
  - **build**: Changes that affect the build system or external dependencies
  - **ci**: Changes to our continuous integration processes or workflows
  - **chore**: Refactor, cleanup, or other non-functional code changes
  - **docs**: Documentation update or addition
  - **feat**: Introduces a new feature or enhancement to the codebase
  - **fix**: Bug fix or error correction
  - **i18n**: Internationalization or localization changes
  - **perf**: Performance improvement
  - **refactor**: Code restructuring for better maintainability, readability, or scalability
  - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
  - **test**: Adding missing tests or correcting existing tests
  - **WIP**: Work in progress, a temporary label for incomplete or ongoing work

# Changelog Entry

### Description

I have been checking some PEP style issues in the backend code finding a lot of unused imports & vars and other more severe things like duplicated function names in the same file. This changes does not affect to the performance or application behaviour however, I think will provide a cleaner code.

### Removed
- 130 imported but unused modules

### Changed
- 29 occurrences of None comparisons with `==` or `!=` instead of `is` or `is not`
- Multiple imports on one line to several lines

### Fixed
- Duplicated function names (`get_image_size`, `update_image_size` , `get_user_chats` and `get_app_config`) on some files
- f-strings without any placeholders

### CODE REVIEW

**Comment by justinh-rahb** [comment]
Thanks for the cleanup work, always appreciated 👏 We are going to need to put this under a microscope though, since there's a significant number of affected files. If you could share with us some more information on your testing process this could help to secure our confidence some. Thanks!

**Comment by franciscovelez** [comment]
Well, I've just installed the `ruff` package in my environment and applied most of all suggested fixes from `ruff` command. I know there is an open PR related https://github.com/open-webui/open-webui/pull/2041 but the difference here is that I didn't enable the linting CI task and I didn't applied some rules that can modify the behaviour.

I can provide you the list of applied rules and the configuration used with the `ruff` command for creating this PR. If you want it, let me know.

**Comment by franciscovelez** [comment]
Hi! In order to apply the style fixes, I created a `pyproyect.toml` file in the `/backend` folder and run the `ruff check .` command. As I said earlier, I skipped some rules because I wasn't sure they were 100% safe. 

This is the configuration I've used:
```toml
[tool.ruff]
line-length = 120
lint.ignore = [ "E722", "F405", "E731", "E402", "F841", "F403", "E712"]

[tool.ruff.lint.per-file-ignores]
'apps/webui/internal/migrations/*.py' = ['F401']
```

And these are the stats of the applied rules:
```
130     F401    Imported but unused
 29     E711    Comparison to `None` should be `cond is None`
  5     F811    Redefinition of unused name
  4     F821    Undefined name `REQUEST_POOL`
  2     F541    f-string without any placeholders
  1     E401    Multiple imports on one line
```

**Comment by tjbck** [comment]
Thanks for the PR! I think it would be great to break this down into separate PRs so that it's easy for us to manually test all the different features and we know for a fact that we're not breaking anything. 😅 I'll close this for now, feel free to create a new one!

**Pull request closed without merging**
