### PR TITLE
Add AMD Docker Compose config file

### PR DESCRIPTION
**Pull request by justinh-rahb**
This Docker Compose will setup Ollama to run with AMD GPU support using the `:rocm` tagged image. Some GPUs seem to require this environment variable: `HSA_OVERRIDE_GFX_VERSION`

Which could require different values:
https://github.com/ollama/ollama/issues/2637

---

- **For AMD GPU Support:** Some AMD GPUs require setting an environment variable for proper functionality:

  ```bash
  HSA_OVERRIDE_GFX_VERSION=11.0.0 docker compose -f docker-compose.yaml -f docker-compose.amdgpu.yaml up -d --build
  ```

  <details>
  <summary>AMD GPU Support with HSA_OVERRIDE_GFX_VERSION</summary>

  For AMD GPU users encountering compatibility issues, setting the `HSA_OVERRIDE_GFX_VERSION` environment variable is crucial. This variable instructs the ROCm platform to emulate a specific GPU architecture, ensuring compatibility with various AMD GPUs not officially supported. Depending on your GPU model, adjust the `HSA_OVERRIDE_GFX_VERSION` as follows:

  - **For RDNA1 & RDNA2 GPUs** (e.g., RX 6700, RX 680M): Use `HSA_OVERRIDE_GFX_VERSION=10.3.0`.
  - **For RDNA3 GPUs**: Set `HSA_OVERRIDE_GFX_VERSION=11.0.0`.
  - **For older GCN (Graphics Core Next) GPUs**: The version to use varies. GCN 4th gen and earlier might require different settings, such as `ROC_ENABLE_PRE_VEGA=1` for GCN4, or `HSA_OVERRIDE_GFX_VERSION=9.0.0` for Vega (GCN5.0) emulation.

  Ensure to replace `<version>` with the appropriate version number based on your GPU model and the guidelines above. For a detailed list of compatible versions and more in-depth instructions, refer to the [ROCm documentation](https://rocm.docs.amd.com) and the [openSUSE Wiki on AMD GPGPU](https://en.opensuse.org/SDB:AMD_GPGPU).

  Example command for RDNA1 & RDNA2 GPUs:
  ```bash
  HSA_OVERRIDE_GFX_VERSION=10.3.0 docker compose -f docker-compose.yaml -f docker-compose.amdgpu.yaml up -d --build
  ```

  </details>

## Pull Request Checklist

- [x] **Description:** This pull request adds an AMD GPU Docker Compose file to the project. The file is configured to run the `ollama/ollama:rocm` Docker container, which should improve performance on systems with AMD GPUs.

- [x] **Changelog:**

  ### Added

  - AMD Docker Compose file for Ollama on AMD GPUs

  ### Changed

  - Updated documentation to include instructions for using the AMD Docker Compose file

---

Please review the changes and let me know if you have any questions or suggestions. Thank you!

### CODE REVIEW

**Comment by justinh-rahb** [comment]
Huge credit to @slash-proc and Tristan from Discord in their help in getting this figured out, it was a journey for the ages 😬

**Comment by justinh-rahb** [comment]
One more note: I am fairly certain that this will probably only work on Linux Docker hosts. Our very patient test subject was running Ubuntu, and I do not have an AMD GPU of my own to test this on Windows with unfortunately.

**Comment by justinh-rahb** [comment]
Would love that actually, we probably shouldn't just YOLO merge this _yet_.

**Comment by slash-proc** [comment]
hmm... I don't see any harm in giving people the option/example for amdgpu's. I think this is a stable basis going forward. 

Also I think it would be helpful to get input from other amd gpu owners, no? I'm very curious what Windows + WSL AMD owners would report. Leaving a disclaimer comment in the `docker-compose.amdgpu.yaml` regarding this only being tested in Linux, etc. would be fitting of course.

**Comment by tjbck** [comment]
LGTM, Thanks!

**Comment by turkiet** [comment]
I tried the code you gave in CMD and Docker Terminal but it doesn't accept it. Where should I enter this code? It takes 1 minute to respond even though I have 8GB VRAM. My gpu is RX 6600.

**Pull request merged**
