### PR TITLE
fix: Fix KaTeX Rendering

### PR DESCRIPTION
**Pull request by sp301415**
# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [ ] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [x] **Testing:** Have you written and run sufficient tests for validating the changes?
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [x] **Prefix:** To cleary categorize this pull request, prefix the pull request title, using one of the following:
  - **BREAKING CHANGE**: Significant changes that may affect compatibility
  - **build**: Changes that affect the build system or external dependencies
  - **ci**: Changes to our continuous integration processes or workflows
  - **chore**: Refactor, cleanup, or other non-functional code changes
  - **docs**: Documentation update or addition
  - **feat**: Introduces a new feature or enhancement to the codebase
  - **fix**: Bug fix or error correction
  - **i18n**: Internationalization or localization changes
  - **perf**: Performance improvement
  - **refactor**: Code restructuring for better maintainability, readability, or scalability
  - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
  - **test**: Adding missing tests or correcting existing tests
  - **WIP**: Work in progress, a temporary label for incomplete or ongoing work

# Changelog Entry

### Description

This PR attempts to fix some issues in KaTex rendering, including:
- Inline KaTeX not rendering when using delimiters other than `$...$`
- Block KaTeX rendering as inline KaTeX

### Changed

- `$$...$$` is now correctly registered as displaymath
- Add start token computation for every math delimiter
- Correctly mark block KaTeX

---

### Screenshots or Videos

Here is the screenshot of previous version. The model is Qwen 2.5, which notably uses `\(...\)` and `\[...\]` as math delimiters.
katex_old
Notice that block math equation is rendered as inline math equations, and some inline equations are not rendered.

In comparison, here is the screenshot after this PR:
katex_new

### CODE REVIEW

**Comment by tjbck** [comment]
Thanks for the PR! I'd appreciate if you could provide a thorough testing with screenshots here to ensure we're not introducing new issues!

**Comment by sp301415** [comment]
@tjbck Thanks, I've added screenshot to the PR! Could you please guide me on testing the new renderer? I think this part was not tested before, so I'm not sure how to test it.

**Comment by tjbck** [comment]
https://github.com/open-webui/open-webui/discussions/3581 https://github.com/open-webui/open-webui/issues/3872 https://github.com/open-webui/open-webui/issues/3577 https://github.com/open-webui/open-webui/discussions/3127 https://github.com/open-webui/open-webui/issues/2615 https://github.com/open-webui/open-webui/discussions/2365 Here is the list of issue reports!

**Comment by sp301415** [comment]
@tjbck Thank you! I've tested issues that you mentioned, and it seems like this PR passes all of them. Some screenshots:
katex_fix_1
katex_fix_2
katex_fix_3

The only exception was #3577, but I believe the prompt is wrong in this case, because:
- `[\n ... \n]` does not render, because it is not a valid block math delimiter, only `[ ... ]` is.
- `其中，$A$, $B$, $C$` does not render, because math rendering does not work when there are a character exists immediately before starting math delimiter. This is a conscious choice to prevent accidental trigger.

**Comment by sp301415** [comment]
@tjbck I think it should, because `\[ ... \]` is a block math delimiter. For outputs like the screenshot, you should use inline math delimiters such as `$...$` or $\( ... \)$.

**Comment by tjbck** [comment]
image


Here's how ChatGPT renders it for reference.

**Comment by sp301415** [comment]
@tjbck Ah, I played around ChatGPT, and I get it. It seems like ChatGPT uses different math delimiter: It considers `$$...$$` and `\[...\]` as inline math delimiters, and only considers `$$\n...\n$$` and `\[\n...\n\]` as block delimiters. I'll fix it to match ChatGPT's outputs.

**Comment by tjbck** [comment]
The rest looks good, let's try to have this merged for 0.3.27!

**Comment by sp301415** [comment]
Seems like it's fixed now:
katex_delimiter_fix

**Comment by tjbck** [comment]
Looks great, Thanks!

**Comment by sp301415** [comment]
Wait, I was about to push last minute change for something lol. Can you cherry-pick it?

**Pull request merged**
