### PR TITLE
✨ Feature:  Self-Aware Document Monitoring 📄

### PR DESCRIPTION
**Pull request by excho0**
### **Implement Self-Aware Document Monitoring System with API Integration and UI Controls**

inspired by the idea detailed in issue #2439

---

**Description:**

This pull request introduces a comprehensive Self-Aware Document Monitoring system, integrating multiple components to deliver a robust solution for file monitoring and management. The updates include frontend and backend changes to ensure seamless user experience and effective system functionality.

---

### TODO Checklist

1 **Backend Monitoring System:**
   - [x] Develop a file monitoring system using `watchdog` to track events such as creation, modification, deletion, and movement.

2. **State Management:**
   - [x] Use local storage (the config.json) to persist and retrieve the SADM monitoring state across application startups.

3. **Logging and Error Handling:**
   - [x] Set up detailed logging and robust error handling for both monitoring operations and API interactions.

4. **API Integration with FastAPI:**
   - [x] Create and test endpoints for enabling (`/enable`), disabling (`/disable`), and checking the monitoring system status (`/status`).

5. **Frontend Integration:**
   - [x] Implement `sadmToggler` and `sadmRetrieveStatus` functions for API interaction.
  
   - [x] Update the UI to manage and display the Self-Aware Document Monitoring state, including toast notifications for user feedback.

6. **Quality Assurance (QA)**
   - [x] **Developed and validated** a multi-threaded Python script to simulate and test concurrent file operations in a production-like environment.
image
image
   
7. **Additional Tasks**
   - [x] Add upon initialization the function to scan the docs folder
image
   - [x] Split The Self-Aware Document Monitoring into two files: one for models and one for the API Router 
image
   - [x] Remove the `.monitoring_state` file and use the main config.json instead
image
   - [x] Introduce a new method `remove_missing_files_from_db` to ensure database consistency by removing entries for files that no longer exist in the filesystem.
image
   - [x] Introduce a new method `ensure_location_column_exists` to add the 'location' column to the 'document' table, and update each document location row ensuring all documents have accurate location data for better management.
image
and if already exist it will simply write that to the config and skip it
image
   - [x] Modify `delete_doc_by_name` function to handle also document removal from the filesystem itself and not only from the SQL Database

   - [x] Add Self-Aware Document Monitoring strings to all the translation files
   - [x] translate my entire language (hebrew)
   - [x] Commit The New Updates

---

#### **Frontend Changes:**

- Implemented `sadmToggler` and `sadmRetrieveStatus` functions to interact with the monitoring API.
- Integrated these functions into the UI for toggling/Retrieving the monitoring state/status.

image
image

---

#### **Backend Changes:**

- **Document Monitoring:**
  - Developed a `watchdog`-based system to monitor file system events and handle real-time updates.
  - Implemented a monitoring thread to interact with the document database and maintain monitoring state across restarts.

---
- **API Integration:**
  - Added FastAPI endpoints for enabling (`/enable`), disabling (`/disable`), and checking status (`/status`) of the monitoring system. (and also Make sure they are protected using `user=Depends(get_admin_user)` )
 
image
image

---

- **Logging and Error Handling:**
  - Configured detailed logging for monitoring operations and integrated comprehensive error handling to ensure system reliability.
 
Example 1: Application Startup
image

 
 
 Example 2: Application Shutdown 
image

---

**Summary:**

This pull request consolidates frontend and backend changes to deliver a functional and user-friendly document monitoring system. The integration between UI controls and backend processing ensures both seamless user interaction and robust system performance.

---

Feel free to review the changes and provide feedback. Thank you!

### CODE REVIEW

**Comment by excho0** [comment]
I've noticed an issue with the current logic for deleting files. Specifically, the code is not actually removing the file from the filesystem due to a lack of proper logic handling this operation. We need to ensure that when a document is deleted from the database, the corresponding file in the filesystem is also deleted to maintain consistency and avoid orphaned files.

I'm marking this PR as a Work In Progress (WIP) until I can provide the necessary fixes. I'll update the logic to include proper file deletion and will notify everyone once it's ready for review.

**Comment by excho0** [comment]
Hi everyone,

I’m thrilled to share that I’m making great progress! I’m putting the finishing touches on the updates and plan to commit the changes and mark this as ready for review once I verify that everything works correctly and performs at a high level.
expect for an update in just a couple of days!

**Comment by excho0** [comment]
Hi everyone! 👋

Just a quick update on the feature. I’m super close to committing the changes, but during testing, I noticed a few more tweaks are needed to make everything work flawlessly. 🔧✨ I’ll need a bit more time to wrap up these final details.

Expect more updates and possible commits over the next week! 🚀🔜 Thanks for your patience 🙏

**Comment by excho0** [comment]
Hi everyone! 👋

I’m excited to let you know that I’ve committed the changes to the feature! 🎉 The final tweaks are in place, and everything seems to work and ready for review. I’d greatly appreciate if you could take a look and provide any feedback or suggestions. 🙌🚀

**Review by Tavernari — APPROVED** [review]

**Comment by tjbck** [comment]
In case anyone comes across this in the future, you can now implement this feature externally: https://github.com/open-webui/cookbook/blob/main/knowledge/add-to-knowledge.ipynb

**Pull request closed without merging**
