### PR TITLE
perf: Improve Speed of Document Insertion in Knowledge Bases

### PR DESCRIPTION
**Pull request by RobinBially**
reopening #6122 

- added support for chroma and milvus
- refactoring
- rebased on dev

### CODE REVIEW

**Comment by RobinBially** [comment]
rebased again.

Is there anything else preventing this from being merged? @tjbck

**Comment by tjbck** [comment]
Generally unsure if I'd want to merge at this point, later down the line I might add more configurable embedding options for knowledge collections (e.g. different chunking approaches for different collections).

**Comment by RobinBially** [comment]
This is what I'm also doing right now. I'm planning to integrate collections with multimodal content. You can still have that functionality. Additionally, this is not a small performance gain. When using larger embedding models or if you want to use the reindexing feature that I'm planning to submit, this would be the difference between, for example, 1 hour and 2 hours of embedding time.

**Comment by tjbck** [comment]
PR generally looks good, I just need to work on other stuff first 🙌

**Pull request closed without merging**
