### PR TITLE
feat: added support for Stable Diffusion 3 alongside more extensive ComfyUI configuration

### LINKED ISSUE #1459: feat: Image generation api call is missing cfg scale parameter
**Is your feature request related to a problem? Please describe.**
Integration with automatic1111 and comfy ui is good, but the settings configuration ui is lack of the key parameter "CFG Scale" value, which impacts the image generation result significantly, with the default stable diffusion value being 7, some sdxl lighting models' generation result is barely usable.

**Describe the solution you'd like**
Add the the "CFG Scale" param in image generation configuration page and take it into API calls properly.

**Describe alternatives you've considered**
No good way to change the default value in automatic1111 stable diffusion side.

**Additional context**
Even more customization approaches in image generation UI can be considered in future roadmap, for example, real time input dialogue for this CFG scale value before clicking generation button in chat view.

### LINKED ISSUE #1958: feat: Stable Diffusion 3.0
**Is your feature request related to a problem? Please describe.**
Not a problem. :slightly_smiling_face: 

**Describe the solution you'd like**
An implementation of the new SD 3.0 API in the experimental image generator.

**Describe alternatives you've considered**
Waiting until weights are downloadable?

**Additional context**
- [api reference](https://platform.stability.ai/docs/api-reference#tag/Generate/paths/~1v2beta~1stable-image~1generate~1sd3/post)

### PR DESCRIPTION
**Pull request by JohnTheNerd**
# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [x] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [x] **Testing:** Have you written and run sufficient tests for validating the changes?
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [x] **Prefix:** To cleary categorize this pull request, prefix the pull request title, using one of the following:
  - **BREAKING CHANGE**: Significant changes that may affect compatibility
  - **build**: Changes that affect the build system or external dependencies
  - **ci**: Changes to our continuous integration processes or workflows
  - **chore**: Refactor, cleanup, or other non-functional code changes
  - **docs**: Documentation update or addition
  - **feat**: Introduces a new feature or enhancement to the codebase
  - **fix**: Bug fix or error correction
  - **i18n**: Internationalization or localization changes
  - **perf**: Performance improvement
  - **refactor**: Code restructuring for better maintainability, readability, or scalability
  - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
  - **test**: Adding missing tests or correcting existing tests
  - **WIP**: Work in progress, a temporary label for incomplete or ongoing work

# Changelog Entry

### Description

added Stable Diffusion 3 support alongside ComfyUI configuration.
    
this commit adds four environment variables:
    
- COMFYUI_CFG_SCALE
- COMFYUI_SAMPLER
- COMFYUI_SCHEDULER
- COMFYUI_SD3

### Added

The above mentioned environment variables, alongside Stable Diffusion 3 support.

### Changed

N/A

### Deprecated

N/A

### Removed

N/A

### Fixed

closes #1459 alongside addressing the top comment (for ComfyUI only, as I do not have an AUTOMATIC1111 setup to test with). also closes #1958 (again, for ComfyUI only, since afaik AUTOMATIC1111 doesn't even support SD3).

### Security

N/A

### Breaking Changes

No breaking changes, because if the environment variable does not exist, we fall back to the original behavior.

---

### Additional Information

All three of the changes I wrote in the past few hours are built together in the Docker image `ghcr.io/johnthenerd/open-webui:comfyui-test3` and I am currently running them in my homelab without any issues. Tested with and without the new environment variables.

Docs at https://github.com/open-webui/docs/pull/119

### Screenshots or Videos

SD3 with everything set to what is recommended in the documentation:

image

### CODE REVIEW

**Comment by tjbck** [comment]
LGTM but not sure why my refac is also part of this PR, closing this but feel free to reopen!

**Comment by JohnTheNerd** [comment]
Your refactors are part of this PR likely because I selected the "allow maintainers to edit" option - which grants you write access to that specific branch. I can check out the earlier commit, force push, and re-open, but your changes will be lost.

**Comment by tjbck** [comment]
Not sure if I understand, If you rebase to the current latest dev you'll only add your changes without overwriting 😅

**Comment by JohnTheNerd** [comment]
I do not see your changes in `dev`:



I do, however, see them in my branch:



My guess is that you accidentally committed them to my fork. If I remove them, you will likely lose your changes.

**Comment by tjbck** [comment]
https://github.com/open-webui/open-webui/commit/bdd2ac0015354a8b9827923bd79880c59f7071b7

**Comment by JohnTheNerd** [comment]
Interesting, especially so that the timestamps don't match. Maybe it's because of the git shenanigans I had to go through to get a working image (I can't build anything without incorporating #3204 into my branches, and therefore can't test anything until I cherry-pick a bunch of stuff together into a separate branch).

Anyhow, I will simply rebase off dev, force a push, and see if the problem magically goes away. I won't do the cherry-picking stuff this time, meaning I won't be able to test the resulting code.

I'll re-open after I'm done.

**Pull request closed without merging**
