### PR TITLE
Feat/base path relocatable

### PR DESCRIPTION
**Pull request by lmorin-inria**
## Pull Request Checklist

- [X] **Target branch:** Pull requests should target the `dev` branch.
- [X] **Description:** Briefly describe the changes in this pull request.
- [ ] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [ ] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [ ] **Testing:** Have you written and run sufficient tests for the changes?
- [ ] **Code Review:** Have you self-reviewed your code and addressed any coding standard issues?

---

## Description

This pull request implements the dynamic relocation, as requested in issue #1162 .

The core implementation principle has been deployed over ~200 account using a cloud orchestration system on a previous version. The current implementation has been tested on a few nodes.
Three major drawbacks : 
 - no way to test on Windows (no machine, no time),
 -  the implementation does not use properly the svelte infrastructure (lack of expertise),
 - some files had to be moved.

If the merge is accepted, I will add the documentation.

---

### Added

- Add dynamic relocation support.

### Fixed

- [List any fixes, corrections, or bug fixes]

### Changed

- [List any changes, updates, refactorings, or optimizations]

### Removed

- [List any removed features, files, or deprecated functionalities]

### Security

- [List any new or updated security-related changes, including vulnerability fixes]

### Breaking Changes

- [List any breaking changes affecting compatibility or functionality]

---

### Additional Information

- [Insert any additional context, notes, or explanations for the changes]

- [Reference any related issues, commits, or other relevant information]

### CODE REVIEW

**Comment by tjbck** [comment]
Closing due to too many unrelated changes, I appreciate the effort 🙌

**Comment by lmorin-inria** [comment]
Ok that you do not accept the MR, however, all the changes  - except the UID/GID in the Dockerfile - are strictly related, and required by the feature.

What can I do to make that merge request accepted ?

**Comment by TomlDev** [comment]
@tjbck Why wouldn't you want to merge such a feature?

**Comment by jupiterbjy** [comment]
https://github.com/open-webui/open-webui/issues/1162#issuecomment-1998113814

> If not officially supported, but I can see that being useful for a lot of people. Feel free to make a PR!

<br>

https://github.com/open-webui/open-webui/pull/2148#issuecomment-2103065833

> Closing due to too many unrelated changes, I appreciate the effort 🙌

Not explaining why it's too many 'unrelated' changes on this person's hard work doesn't look too 'appreciating' with emoji almost feels like taunting, I seriously want to know exact reason behind this useful feature.

---

@TomlDev This seems to hint the reason:

https://github.com/open-webui/open-webui/issues/1162#issuecomment-2432766164

> The changes required to accept the feature would also require a strong update of all svelte developers : they put absolute paths in the source code... Not something I would let one of my student do. But I also appreciate all the work shared by this great project. I cannot complain.

**Comment by tjbck** [comment]
Relative path support is not something we intend to officially support at this time. The primary reasons are straightforward: I do not have the capacity to introduce additional complexities to the project right now, and no one has bothered to submit an atomic pull request that aligns with the contribution guidelines. On top of this, there are more pressing bug fixes and priority tasks that require attention, so I won’t be dedicating time to this feature for the foreseeable future. 

While I acknowledge that relative path support might be helpful for a subset of users, it’s simply not a current priority. If this feature is important to you, I strongly encourage you to fork the project and maintain your own version. This is the beauty of open source—nothing is stopping you from taking ownership of the changes you care about.

**Pull request closed without merging**
