### PR TITLE
💄 Limit the size and number of uploaded files on the front-end to optimize the upload speed

### PR DESCRIPTION
**Pull request by Yanyutin753**
# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [x] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [x] **Testing:** Have you written and run sufficient tests for validating the changes?
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?

# Changelog Entry

#### 1. During the file upload process, initialize the file first, so that the response is faster during the upload process. 

https://github.com/user-attachments/assets/3fb18878-1453-4920-8cad-4cbda5cb272c

#### 2. Environment variables `RAG_MAX_FILE_COUNT` and `RAG_MAX_FILE_SIZE` are also set to limit the maximum size and number of files that users can upload per session, while allowing administrators to freely adjust these values. 

image

#### 3. By adjusting the front end, we can make the front end upload files, display the size of each file, and adapt to previous files, which do not display the size of the file

image

image

##### Warning

image

image

### CODE REVIEW

**Comment by tjbck** [comment]
Let's do atomic PRs please!

**Comment by Yanyutin753** [comment]
> Let's do atomic PRs please!

However, I think this is very necessary. For the file upload restrictions, sometimes students who do not know how to upload a large file, but have to wait for a long time may not upload successfully. This limitation can effectively reduce the probability of system errors, but also reduce some malicious requests and save system memory

**Comment by Yanyutin753** [comment]
And it's not going to conflict with anything else, right? The administrator can customize the parameters, and it's not going to affect anything else, right！

**Comment by justinh-rahb** [comment]
It was closed because there are changes that aren't specifically related to the topic of the PR such as updated dependency versions which could introduce unknown issues with testing whether _your_ changes have had any regressive effects. Please try to keep PRs limited to only a single change, otherwise discuss proposed changes before committing a lot of work that may ultimately be rejected.

**Comment by Yanyutin753** [comment]
I didn't change this version. I just pulled it off. What I want to consider now is whether I need this function. If I really need it, I can continue to follow up🥹

**Pull request closed without merging**
