### PR TITLE
feat: Support Tika for document text extraction

### PR DESCRIPTION
**Pull request by nickovs**
See discussion #3475 for background.

- [X] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [X] **Description:** Provide a concise description of the changes made in this pull request.
- [X] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [X] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources? *Documentation will be added to the [relevant tutorial](https://docs.openwebui.com/tutorial/rag) via a separate PR once this PR is accepted.*
- [X] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [X] **Testing:** Have you written and run sufficient tests for validating the changes?
- [X] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [X] **Prefix:** To cleary categorize this pull request, prefix the pull request title, using one of the following:
  - **BREAKING CHANGE**: Significant changes that may affect compatibility
  - **build**: Changes that affect the build system or external dependencies
  - **ci**: Changes to our continuous integration processes or workflows
  - **chore**: Refactor, cleanup, or other non-functional code changes
  - **docs**: Documentation update or addition
  - **feat**: Introduces a new feature or enhancement to the codebase
  - **fix**: Bug fix or error correction
  - **i18n**: Internationalization or localization changes
  - **perf**: Performance improvement
  - **refactor**: Code restructuring for better maintainability, readability, or scalability
  - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
  - **test**: Adding missing tests or correcting existing tests
  - **WIP**: Work in progress, a temporary label for incomplete or ongoing work

# Changelog Entry

### Description

Before any non-image files attached to chats can be used by LLMs, their content text must be extracted. This PR adds support to use [Apache Tika](https://tika.apache.org) for this rather than using the Langchain community document loaders.

### Added

- Code in `backend/apps/rag/main.py` and supporting files to conditionally make calls out to an Apache Tika server to extract document text rather than using the community-supported loaders from Langchain.
- Additions to the stored configuration schema to support text extraction engine selection and configuration.
- UI components for the Admin Panel->Settings->Documents page to allow engine selection and configuration.

### Changed

- Minor (incidental) tweak to `.dockerignore` to prevent local virtual environments in `venv` directory from being copied into Docker images. 

### Deprecated

*None*

### Removed

*None*

### Fixed

*None*

### Security

- Note that the use of a new service to which user content will be sent opens up a new attack surface. Apache Tika is a mature product and will typically be deployed in a sidecar container, so the risk is very small.

### Breaking Changes

*None*

---

### Additional Information

[Apache Tika](https://tika.apache.org) is a mature tool for extracting text and metadata from files. It supports hundreds of different document types, is under active development and is well-supported. Features include fully integrated OCR of embedded images in hierarchical documents and output of both plain and structured text.

The Tika server is available as a pre-packaged Docker image for multiple platforms. While this code supports communicating with a server in any network-accessible location, the suggested configuration is to deploy it as a sidecar container along side the Open WebUI server. This can be done by adding the following to the `docker-compose.yaml` file:
```yaml
  tika:
    image: apache/tika:latest-full
```
and updating the configuration for the Open WebUI container with an additional environment variable:
```yaml
  open-webui:
    ...
    environment:
      ...
      - 'TEXT_EXTRACTION_ENGINE=tika'
```

### CODE REVIEW

**Comment by tjbck** [comment]
Excellent addition to our webui, I love it! I'll be updating the variable names to be more generalisable but the rest LGTM, Thanks!

**Comment by drupol** [comment]
Hey hi!

I really wish I could get this feature to work, I definitely think that Tika is a very good tool for that.

Tika is correctly setup and working well (tested with `curl -T <file> <tika-url>`)... but when I submit a PNG file:

image

Or a PDF containing that same picture:

image

Here's my config:

image

Can you please advise on what could be done?

**Comment by nickovs** [comment]
@drupol How are you setting up the communication between Open WebUI and Tika? Can you post your Docker compose file?

**Comment by drupol** [comment]
There's no docker involved, I'm using Nix, it's easier since there's no container involved.

In the log I posted under the screenshot in my first comment, you can see that open-webui is communicating with Tika correctly.

**Comment by drupol** [comment]
That said, this feature works extremely well for regular documents, but doesn't work for images.

Example:

image

And sending the picture to Tika works:

image

**Comment by nickovs** [comment]
@drupol You can probably check in the Tika logs, but I believe that Open WebUI handles images separately from "documents", and so my code will never get called when you pass an image file. For the large, multi-modal LLMs this is just fine since the image support in the models will usually be fine at extracting the text (see the image below for an example with Claude 3 Haiku). If you're running a smaller, local model that isn't multi-modal, or hasn't been trained on OCR tasks, then local text extraction would be a good thing, but it's a different thing to what this PR supports.

image

**Comment by drupol** [comment]
Thanks for the clear explanation. It's a bit weird that things are done as such, but OK, now I know it.

**Comment by nickovs** [comment]
I think that it does deserve a switch to determine the behaviour as part of the model profile, since the correct processing path depends both on the capabilities of the model and what the use case is; the UI doesn't really know what they picture is of. For any model with multi-modal input and training on OCR tasks the right answer is usually to give it single images as they are. If the picture is a whole page of text then a proper OCR engine that can return structured text might be better, but you don't know until you've tried. Even is you decided to try Tika and if it finds text then you pass the text rather than the image, maybe the picture contains a bunch of things and just happens to have text in some logo or a part of the background. There's no single right answer. I think that the default at the moment is probably the right default, but it would be helpful to be able to override that.

**Pull request merged**
