### PR TITLE
fix: boolean values don't need to be accessed by .value

### LINKED ISSUE #6384: OIDC login fails - Boolean variables are not accessed correctly
# Bug Report

## Installation Method

Docker (AWS ECS)

## Environment

- **Open WebUI Version:** v0.3.33

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Login via OIDC EntraID works

## Actual Behavior:

Internal Server Error happens.

## Description

**Bug Summary:**
Boolean variables are not accessed correctly

## Reproduction Details

**Steps to Reproduce:**
Set the needed OIDC variables in the ECS Task Definition e.g.
```json
    { name = "ENABLE_OAUTH_SIGNUP", value = "true" },           # Boolean value as string
    { name = "OAUTH_MERGE_ACCOUNTS_BY_EMAIL", value = "true" }, # Boolean value as string
```

## Logs and Screenshots

```text
...
 File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/main.py", line 2372, in oauth_callback
    return await oauth_manager.handle_callback(provider, request, response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/utils/oauth.py", line 165, in handle_callback
    if auth_manager_config.OAUTH_MERGE_ACCOUNTS_BY_EMAIL.value:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...

```

## Additional Information

The boolean values seem to be accessible without ".value" and hence the call fails.

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

### PR DESCRIPTION
**Pull request by nodomain**
# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [x] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [x] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [ ] **Testing:** Have you written and run sufficient tests for validating the changes?
- [ ] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [x] **Prefix:** To cleary categorize this pull request, prefix the pull request title, using one of the following:
  - **BREAKING CHANGE**: Significant changes that may affect compatibility
  - **build**: Changes that affect the build system or external dependencies
  - **ci**: Changes to our continuous integration processes or workflows
  - **chore**: Refactor, cleanup, or other non-functional code changes
  - **docs**: Documentation update or addition
  - **feat**: Introduces a new feature or enhancement to the codebase
  - **fix**: Bug fix or error correction
  - **i18n**: Internationalization or localization changes
  - **perf**: Performance improvement
  - **refactor**: Code restructuring for better maintainability, readability, or scalability
  - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
  - **test**: Adding missing tests or correcting existing tests
  - **WIP**: Work in progress, a temporary label for incomplete or ongoing work

# Changelog Entry

### Description

Removed the `.value` access for OIDC related settings.

### Fixed

- Boolean environment variables `OAUTH_MERGE_ACCOUNTS_BY_EMAIL` and `ENABLE_OAUTH_SIGNUP` were falsely accessed by `.value` and hence OIDC auth failed.

---

### Additional Information

- fixes #6384 

### Screenshots or Videos

- [Attach any relevant screenshots or videos demonstrating the changes]

### CODE REVIEW

**Comment by tjbck** [comment]
Is this PR tested?

**Comment by abiari** [comment]
I can confirm removing the .value fixes the OIDC auth issue on my side. Thanks @nodomain !

**Comment by nodomain** [comment]
Tested by building the docker container and working with it in my ECS service right now :)

**Comment by tjbck** [comment]
Thanks!

**Comment by Itsanewday** [comment]
> I can confirm removing the .value fixes the OIDC auth issue on my side. Thanks @nodomain !

Dear abiari,
      I am having some trouble with the configuration of OIDC.  The logs is like:
INFO:   *****  - "GET /oauth/oidc/login HTTP/1.1" 302 Found
INFO:     connection closed
INFO:   **** - "GET /oauth/oidc/callback? 500 Internal Server Error. .......
 authlib.integrations.base_client.errors.UnsupportedTokenTypeError: unsupported_token_type: Unsupported token_type: 'access_token'.
 How can I solve it?

**Pull request merged**
