### PR TITLE
Idiot-Proof level HTTPS doc for apache

### PR DESCRIPTION
**Pull request by oliverbob**
Addressed the community request for idiot-proof documentation for HTTPS configuration.

Added it on /docs/apache.md
Step by step guide is proven and tested to work on linux.

The reason for this PR is I'd like to see others doing the same for:

Caddy, Nginx and other web servers.

Thanks.

### CODE REVIEW

**Comment by justinh-rahb** [comment]
Very thorough documentation @oliverbob, excellent work.

**Comment by oliverbob** [comment]
> Very thorough documentation @oliverbob, excellent work.

Thanks @justinh-rahb. Tested it  on the latest virtualmin on ubuntu 22.04 jammy standard lxc (linux container) on the latest proxmox ve/debian 12 Ceph cluster for redundancy, and with migration in mind. Also work essentially the same with digital ocean and other cloud providers. Can work with standalone setup too.

Hope others will find it useful.

**Comment by tjbck** [comment]
Amazing stuff! Thank you for your hard work!

**Comment by oliverbob** [comment]
> Amazing stuff! Thank you for your hard work!

You're welcome Timothy. Happy to serve this community. :heart:

**Pull request merged**
