### PR TITLE
feat: Add control for how message content is split for TTS generation requests

### LINKED ISSUE #4834: enh: advanced options for TTS integrations
**Is your feature request related to a problem? Please describe.**
The main issue I've faced with the current TTS integration is later reqs failing for long responses due to how content's split up by sentence. Long enough responses are split into enough reqs that they exceed OAI's ratelimits & fail.

**Describe the solution you'd like**
Since OAI's voice models are limited by RPM (e.g., `tts-1-hd`'s limited to 5 RPM @ tier 2), it'd be great to see some more advanced options surfaced in the Admin Panel UI for controlling how responses are split up / sent out to the selected TTS API.

### PR DESCRIPTION
**Pull request by kiosion**
# Pull Request Checklist

**Before submitting, make sure you've checked the following:**

- [x] Target branch: Please verify that the pull request targets the `dev` branch.
- [x] Description: Provide a concise description of the changes made in this pull request.
- [x] Changelog: Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] Documentation: Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [x] Dependencies: Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [ ] Testing: Have you written and run sufficient tests for validating the changes?
- [x] Code review: Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?

# Changelog Entry

### Description

- Add control for how message content is split up for TTS generation requests. This enables use of OAI's TTS API for larger responses without hitting their RPM limits (especially with `tts-1-hd`'s RPM being just 5). Options are 'punctuation' (current behaviour and default value), 'paragraphs' (split by newlines), and 'none' (send message content as single string).

- Tidy up `Audio` admin settings page and `ResponseMessage` component:
  - Fix some TypeErrors
  - Remove unused vars/imports
  - Use early returns in `toggleSpeakMessage` to avoid deep cond nesting
  - Properly type usage of `i18n` from GetContext as `Writable<i18next>`

- Add error handling around loading settings from LocalStorage in `+layout.svelte` to prevent app hanging if key exists but the content can't be parsed (might crop up if running front-end locally, and another project has set the `settings` key in LocalStorage for `localhost` previously).

### Added

- Control under Audio settings page for changing how message content is split for TTS generation requests.

### Fixed

- App crash when `settings` LocalStorage key can't be parsed by `JSON.parse` on load.

---

### Additional Information

- Resolves #4834

### Screenshots or Videos

image

### CODE REVIEW

**Comment by thiswillbeyourgithub** [comment]
Hi. Regarding punctuation can you consider enforcing a character limit and word limit ?  I noticed things like "we are talking about C. Difficile."  where a punctuation is used for a single word because of abbreviation and the tts switches language for just this word. Maybe other examples would be "e.g. blabla".

My idea is just that a split should not be less than 3 words long nor 5 characters for example

**Comment by kiosion** [comment]
> Hi. Regarding punctuation can you consider enforcing a character limit and word limit ?

This should already be present - `extractSentencesForAudio` iterates over the split sentences and merges them into one string if the word count is less than 2. Could probably benefit from being raised to 4 or so instead.

https://github.com/open-webui/open-webui/blob/b2ec201e059eec7218fcce2fabf996b771692a6b/src/lib/utils/index.ts#L597-L613

**Comment by kiosion** [comment]
cc @tjbck, rebased, should be good to go unless you want a test to cover these changes

**Comment by thiswillbeyourgithub** [comment]
Hi @kiosion.

As you've added a better sentence splitter for the tts (thabks!). Would you know by any chance how hard it would be to pull off starting the tts generation as soon as we get the first split as requested in #3345 ?

I'm thinking that a quick and simple way would be just adding a caching to the tts api call, then by continuously calling the splitter function every few chunk and sending each new **finished** splits (so the penultimate split) to the tts to start caching this would already be a tremendous improvement.

Sure the audio would still not start until the generation is finished but at least we would get audio as soon as we make the tts call, which might be good enough in a lot of cases.

For reference to how simple adding caching could be here's an example of a recent PR with caching: #5212

Unfortunately I only know python and no svelte nor typescript so I'm unsure as to if I could pull this off myself.

**Pull request merged**
