### PR TITLE
feat(kubernetes)!: Major Helm Chart refactor

### PR DESCRIPTION
**Pull request by duhow**
A major refactor of the Helm Chart, allowing for proper install customization.
~Still WIP, need some additional testing for validation.~

### CODE REVIEW

**Comment by duhow** [comment]
@jannikstdl @tjbck have a look 🙏🏻

**Comment by jannikstdl** [comment]
Looks good, thanks. But am not able to test this in prod today. 

But did you try to install this chart? Works as expected?

**Comment by jannikstdl** [comment]
Maybe add a value for the two PVCs. They both are hardcoded as `data`.

**Comment by duhow** [comment]
@jannikstdl I've tried on a new cluster and worked. You can even create a GitHub E2E action if needed to deploy.

The PVCs are not "named" `data` .The `volume` internal name is. PVC name is `data-ollama-0` (as per Statefulset name) and `open-webui`.

**Comment by duhow** [comment]
Forgot 9ee64d8 , the PVC name is already configurable in template.

**Comment by tjbck** [comment]
Let me know if this PR is ready to me merged!

**Comment by jannikstdl** [comment]
@tjbck should be. If you want we can wait until next week when I can try this on our cluster.

**Comment by braveokafor** [comment]
Thanks for the PR @duhow , nice work.

You forgot to add a port name to `open-webui` service, this is causing the ingress translation to fail since the ingress can't find the `http` port.
Adding a port name (http) should fix this.

Apart from the ingress issue everything else looks fine.

Error:
```
Translation failed: invalid ingress spec: could not find port "&ServiceBackendPort{Name:http,Number:0,}" in service "ollama/open-webui"
```

Fix:  
```sh
--- a/kubernetes/helm/templates/webui-service.yaml
+++ b/kubernetes/helm/templates/webui-service.yaml
@@ -11,6 +11,7 @@ spec:
   type: {{ .type }}
   ports:
   - protocol: TCP
+    name: http
     port: {{ .port }}
     targetPort: http
     {{- if .nodePort }}
```

**Comment by duhow** [comment]
Thanks for the check! Somehow still it was working for me 😮

**Comment by tjbck** [comment]
Ready to be merged?

**Comment by tjbck** [comment]
Thanks everyone!

**Pull request merged**
