### PR TITLE
Feat: Support custom redirect url in OAuth

### PR DESCRIPTION
**Pull request by flexchar**
# Changelog Entry

### Added
- Ability to override default redirect urls when using OAuth with environment variables. You may use `OAUTH_REDIRECT_URL`, `MICROSOFT_REDIRECT_URL`, or `GOOGLE_REDIRECT_URL` to set custom redirect URLs.

### Description

This is both a feature and fix to the issues causes therefore by lack of it.

- Professional deployments will often leverage a reverse proxy to protect web resources or introduce TLS encryption at REST, as described in Open WebUI docs. 
- This will break the redirect urls generated by Fast API for OAuth callbacks.
- This PR adds ability to provide custom callback URLs without dwelling into complex solutions using environment variables.

### Added

- `OAUTH_REDIRECT_URL`, `MICROSOFT_REDIRECT_URL`, or `GOOGLE_REDIRECT_URL` to set custom redirect URLs.

### Related issues

https://github.com/open-webui/open-webui/issues/3727
https://github.com/open-webui/open-webui/issues/3945

I would like someone to test it works as expected before merging. Thank you!

### CODE REVIEW

**Comment by flexchar** [comment]
Although now that I was in the middle of updating docs, I began doubting... People may end up setting wrong URLs and thus cause burden. 

What I initially tried was providing an explicit host in `WEBUI_URL` variable helping it would tell FastAPI to stop playing smart and provide correct url. That is, setting `WEBUI_URL=https://open.webui.chat` and expecting redirect url be `https://open.webui.chat/oauth/google/callback`. However - no.

Any thoughts? 
My expertise is unfortunately extremely humble in the Python world.

**Comment by flexchar** [comment]
Sorry guys. It was just a reckless change. Maybe it's not what I had to do. I will take a stab at this hopefully next weekend and will keep you posted. :)

**Comment by justinjja** [comment]
I found a pretty simple workaround for this with my Kemp loadbalancer doing SSL offloading.
(This is for Microsoft, header might be different for other providers?)

Append the following Request Header:

Rule Type - Add Header 
Header - X-Forwarded-Proto
value - https

**Comment by phpia** [comment]
IMPORTANT I think that there are a typo error. The name of variable is
[MICROSOFT_REDIRECT_URI] not URL

**Comment by flexchar** [comment]
Yes, good catch @phpia. I have no idea how I let such silly mistake slip through. Will you be as kind to submit a PR to fix it? ✌️

**Comment by yyoussef11** [comment]
@flexchar  @phpia  any updates on this ? 

i was correctly redirected to https from my Microsoft authentication, to https://<host_url>/oauth/microsoft/callback. 
However this url was redirecting me again to an HTTP url: http://<host_url>/auth

might be something that was missed somewehre in this commit ?

**Comment by yyoussef11** [comment]
@phpia @flexchar 

i was correctly redirected to https from my Microsoft authentication, to https://<host_url>/oauth/microsoft/callback.
However this url was redirecting me again to an HTTP url: http://<host_url>/auth

might be something that was missed somewehre in this commit ?

OpenWebUI version: v0.5.16 deployed with docker

**Comment by phpia** [comment]
mmm bouble check the microsof conf. Also take a look to my script for launch
sudo docker run -d -p 3000:8080 -e ENABLE_SIGNUP=false -e ENABLE_ADMIN_CHAT_ACCESS=true -e ENABLE_LOGIN_FORM=true -e DEFAULT_USER_ROLE=user -e OAUTH_MERGE_ACCOUNTS_BY_EMAIL=true -e WEBUI_URL="https://your_url" -e MICROSOFT_REDIRECT_URI="https://uour_url/oauth/microsoft/callback" -e ENABLE_OAUTH_SIGNUP=true -e MICROSOFT_CLIENT_ID=XXXX -e MICROSOFT_CLIENT_SECRET=xxxx -e MICROSOFT_CLIENT_TENANT_ID=xxx   -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main

**Comment by yyoussef11** [comment]
@phpia  Microsoft config seems alright. Redirect URI on Microsoft is the same one i have specified in my docker run env variable.
Anyway Microsoft won't allow me to add an HTTP url. 

Since i am using Kemp as load balancer, i had to add the header options suggested by @justinjja 
Thanks for quick reply  😄

**Pull request merged**
