### PR TITLE
feat: possibility to move RAG to pipeline

### PR DESCRIPTION
**Pull request by jonathan-rohde**
# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [ ] **Documentation:** Have you updated relevant documentation [Open WebUI Docs](https://github.com/open-webui/docs), or other documentation sources?
- [ ] **Dependencies:** Are there any new dependencies? Have you updated the dependency versions in the documentation?
- [ ] **Testing:** Have you written and run sufficient tests for validating the changes?
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?
- [x] **Prefix:** To cleary categorize this pull request, prefix the pull request title, using one of the following:
  - **BREAKING CHANGE**: Significant changes that may affect compatibility
  - **build**: Changes that affect the build system or external dependencies
  - **ci**: Changes to our continuous integration processes or workflows
  - **chore**: Refactor, cleanup, or other non-functional code changes
  - **docs**: Documentation update or addition
  - **feat**: Introduces a new feature or enhancement to the codebase
  - **fix**: Bug fix or error correction
  - **i18n**: Internationalization or localization changes
  - **perf**: Performance improvement
  - **refactor**: Code restructuring for better maintainability, readability, or scalability
  - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)
  - **test**: Adding missing tests or correcting existing tests
  - **WIP**: Work in progress, a temporary label for incomplete or ongoing work

# Changelog Entry

### Description

- Possibility to move the whole retrieval logic into a pipeline by marking a pipeline in its meta data
- Open webui backend skips the retrieval logic and instead just forwards the data about selected files/collections to pipeline

### Changed

- RAG Middleware: Skip retrieval for pipelines with own retrieval

---

### Additional Information

- Example in related PR in pipeline project: https://github.com/open-webui/pipelines/pull/79

### CODE REVIEW

**Comment by tjbck** [comment]
This is great! I'll take a look in a bit!

**Comment by tjbck** [comment]
This will be closed in favour of `filter` function method which be used to hijack the payload to retrieve uploaded files and send them off to respective RAG pipelines, but I appreciate the effort you put in 🙌

**Comment by jonathan-rohde** [comment]
> filter

Can you please point me into the direction, how to configure that filter?

The ChatCompletionMiddleware always deletes the "files" attribute from request body, even if the skip_files attribute is prevent the context extraction.
I am not able to get the files list in a pipeline.

**Comment by jonathan-rohde** [comment]
Am I right that you mean the pipelines of type "filter"?

Those are not 100% what my pull request is trying to solve. The advantage of not using filter pipeline is, that a user can select a pipeline, but not a filter.

Imagine: You implement different pipelines with different kind of retrieval, maybe with different parameters or even different vector storages. The user should be able to select that.
Or maybe the pipeline could depending on the data combine answers from different openai apis.

**Comment by tjbck** [comment]
Are you on our discord server?

**Comment by tjbck** [comment]
We introduced a new functions feature which include Filter, and Pipe function. They're largely compatible with Pipelines but they're built-in to Open WebUI natively.

For example, you'd be able to import the Filter "Function" below to open webui which can handle extracting the uploaded file lists. 

```py
from typing import List

class Filter:
    def __init__(self):
        # If set to true it will prevent default RAG pipeline
        self.file_handler = True
        pass

    def inlet(self, body: List[dict] = []) -> str:
        print(body["files"])
        return body
```

which would print something like:

```sh
[{'type': 'file', 'file': {'id': '8943b744-8724-407b-9e09-388d192faa01', 'user_id': 'a750f3d8-586a-48b9-b6d5-508463a18ad5', 'filename': '8943b744-8724-407b-9e09-388d192faa01_CHI-invoice.pdf', 'meta': {'content_type': 'application/pdf', 'size': 172345, 'path': '/Users/tim/Documents/workspace/open-webui/backend/data/uploads/8943b744-8724-407b-9e09-388d192faa01_CHI-invoice.pdf'}, 'created_at': 1719332133}, 'id': '8943b744-8724-407b-9e09-388d192faa01', 'url': 'http://localhost:8080/api/v1/files/8943b744-8724-407b-9e09-388d192faa01', 'name': 'CHI-invoice.pdf', 'collection_name': 'f18cd8e7f22150950b503545dfaba06ebb33fa3496db783e07a95fad36a0f8e', 'status': 'processed', 'error': ''}]
```

**Pull request closed without merging**
