### PR TITLE
💄 fix LaTex

### PR DESCRIPTION
**Pull request by Yanyutin753**
# Pull Request Checklist

### Note to first-time contributors: Please open a discussion post in [Discussions](https://github.com/open-webui/open-webui/discussions) and describe your changes before submitting a pull request.

**Before submitting, make sure you've checked the following:**

- [x] **Target branch:** Please verify that the pull request targets the `dev` branch.
- [x] **Description:** Provide a concise description of the changes made in this pull request.
- [x] **Changelog:** Ensure a changelog entry following the format of [Keep a Changelog](https://keepachangelog.com/) is added at the bottom of the PR description.
- [x] **Testing:** Have you written and run sufficient tests for validating the changes?
- [x] **Code review:** Have you performed a self-review of your code, addressing any coding standard issues and ensuring adherence to the project's coding standards?

# Changelog Entry

### Description

💄 Fix LaTex in  #3581 #3872 #3577 #3127 #2615 #2365

## Additional Information

- After my tests, all latex formulas can be displayed normally now！

image

## Screenshots or Videos

image

image

image

image

https://github.com/user-attachments/assets/d1355330-2f64-4ea2-8a80-3cc4805151d3

### If the formula is too long on the mobile side may exceed the scope of the page,  hope someone to resolve it!

### CODE REVIEW

**Comment by BryanLinVanyi** [comment]
Please ! I need this feature in my webUI

**Comment by Yanyutin753** [comment]
you can pull this branch and try to test it

**Comment by tjbck** [comment]
Closing in favour of https://github.com/open-webui/open-webui/commit/41fecb800d0f66b6aaa6edbf1af1563229f78130, if you could share your LLM responses so we can test all cases that would be great!

**Comment by tjbck** [comment]
For future reference, delimiter support for single `$` sign support won't be added as it's not the correct formatting for latex and will cause issues when being used as actual dollar sign.

As you can see below, ChatGPT also does not support single dollar sign as a delimiter:
image

**Comment by Yanyutin753** [comment]
ok, I' ll test it now.

**Comment by Yanyutin753** [comment]
### I think the spacing is a little too small
image

**Comment by Yanyutin753** [comment]
But if we use display to be true sometimes we can't watch all on mobile🤯

**Comment by rssrcr** [comment]
Shouldn't it be possible (by relying on Katex) to simply modify the head in the HTML template? Like so:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KaTeX Multiple Delimiters with Equation Environment</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/katex.min.css">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/katex.min.js"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/contrib/auto-render.min.js"
            onload="renderMathInElement(document.body, {
                delimiters: [
                    {left: '$$', right: '$$', display: true},
                    {left: '\\(', right: '\\)', display: false},
                    {left: '\\[', right: '\\]', display: true},
                    {left: '\\begin{equation}', right: '\\end{equation}', display: true},
                    {left: '$', right: '$', display: false}
                ]
            });"></script>
</head>
<body>
    <h1>KaTeX Multiple Delimiters with Equation Environment</h1>
    <p>Here is an inline equation using dollar signs: $ E = mc^2 $</p>
    <p>Here is an inline equation using LaTeX delimiters: \(\ E = mc^2 \)</p>
    <p>And here is a displayed equation using dollar signs:</p>
    <p>
        $$
        \int_0^\infty e^{-x^2} \, dx = \frac{\sqrt{\pi}}{2}
        $$
    </p>
    <p>And here is a displayed equation using LaTeX delimiters:</p>
    <p>
        \[
        \int_0^\infty e^{-x^2} \, dx = \frac{\sqrt{\pi}}{2}
        \]
    </p>
    <p>Here is an equation environment:</p>
    <p>
        \begin{equation}
        E = mc^2
        \end{equation}
    </p>
</body>
</html>
```

Notice the HEAD.

**Comment by MangoFF** [comment]
Any idea about how to fix it ？

**Pull request closed without merging**
