### PR TITLE
fix: ensure Dockerfile and github actions use the same nodejs version

### PR DESCRIPTION
**Pull request by nowheresly**
nodejs version from github actions and the Dockerfile should be the same

# Changelog Entry

Use nodejs 21. Ensure github actions and docker use the same nodejs version

### CODE REVIEW

**Comment by Nowheresly** [comment]
I could change this PR to stick with nodejs 21 if you prefer

**Comment by Nowheresly** [comment]
In order to run with node 22, cypress has to be updated as explained [here](https://docs.cypress.io/guides/references/changelog#13-14-0)

**Comment by tjbck** [comment]
Rationale behind this PR?

**Comment by Nowheresly** [comment]
> Rationale behind this PR?

Building and running the test with node 20 in github actions while using node 21 to build in the docker image may lead to discrepancies since the tests may succeed while the production docker image may fail because they don't use the same node version

**Comment by tjbck** [comment]
Makes sense, Thanks!

**Comment by Nowheresly** [comment]
the cypress integration tests seem to have issues with node 21.
Maybe should we rollback to node 20
(after all node 20 is LTS, not node 21. And node 22 is not yet LTS)

**Pull request merged**
