### PR TITLE
Fixed Arabic Translation

### PR DESCRIPTION
**Pull request by AlyMobarak**
# Pull Request Checklist

- **Label:** fix

# Changelog Entry

### Description

- As an Arabic user, I've noticed a couple of Arabic mistakes scattered all over. Also, a couple of translations weren't even done in Arabic. So I tried my best as an Arabic native to fix them all.

### Added

- Added new Arabic translations.

### Fixed

- Corrected several Arabic translations by fixing grammar or word choice.

### CODE REVIEW

**Comment by Yanyutin753** [comment]
In fact, this branch can be integrated into #2416, because in fact, many languages are not very perfect, I am a Chinese, some other languages use translation, translation is not necessarily accurate, but also we have to pr together, so that the page is better for family and friends to share

**Comment by Yanyutin753** [comment]
#2416 @AlyMobarak I have merged your branch together, now we are co-authors, let us pr together, OK?

**Comment by AlyMobarak** [comment]
Alright sounds good ig

**Comment by AlyMobarak** [comment]
Anytime!

**Pull request merged**
