### PR TITLE
feat: added ocr functionality to the pdf loader

### PR DESCRIPTION
**Pull request by jannikstdl**
Added OCR functionality to the PDF loader.

File used for the test:
[This is a pdf file with a screenshot.pdf](https://github.com/open-webui/open-webui/files/14501663/This.is.a.pdf.file.with.a.screenshot.pdf)

Before:
image

After:
image

Ressources:
[langchain](https://python.langchain.com/docs/modules/data_connection/document_loaders/pdf#extracting-images)

### CODE REVIEW

**Comment by justinh-rahb** [comment]
Only question I've got is how this affects the Docker image size?

**Comment by jannikstdl** [comment]
@justinh-rahb the wheel is 14.9 MB

**Comment by tjbck** [comment]
Amazing stuff, Thanks!

**Comment by leonardocunha2107** [comment]
Hi, I just started using open-webui today and I got a bug I think is related to this issue when I try loading pdfs in the Documents tab:
``` bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/rapidocr_onnxruntime/utils.py", line 85, in __call__
    return self.session.run(self.get_output_names(), input_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'p2o.Add.246' Status Message: std::bad_alloc

```

**Pull request merged**
