### PR TITLE
feat: Add more variables to prompts

### PR DESCRIPTION
**Pull request by sebdanielsson**
# Changelog Entry

### Description

This PR adds even more variables for the slash command prompts, allowing for even more creative prompts with more contextual information. It also adds three new variables to the system prompt.

### Added

- Added variables like {{CURRENT_DATE}}, {{CURRENT_TIME}}, {{CURRENT_DATETIME}}, {{CURRENT_WEEKDAY}}, {{CURRENT_TIMEZONE}}, {{USER_LANGUAGE}}, {{USER_LOCATION}} to the slash prompt, in addition to the already existing {{CLIPBOARD}} variable.
- Added variables {{CURRENT_WEEKDAY}}, {{CURRENT_TIMEZONE}}, {{USER_LANGUAGE}} to the system prompt.

---

### Screenshots or Videos

SCR-20240922-bidv

SCR-20240922-bikg

### CODE REVIEW

**Comment by silentoplayz** [comment]
I believe I see some duplicate work done here (Correct me if I am wrong).

See docs: https://docs.openwebui.com/features#-conversations
For reference:
image

**Comment by sebdanielsson** [comment]
> I believe I see some duplicate work done here (Correct me if I am wrong).
> 
> See docs: https://docs.openwebui.com/features#-conversations For reference: image

Those only work in the system prompt. Not using the / command for adding a prompt (unsure what the right word for those prompts is). This PR addresses the latter.👍

**Comment by silentoplayz** [comment]
Yes, I believe renaming the variables to match those that are used by the system prompt would be a good idea. My apologies for overlooking at first glance.

**Comment by sebdanielsson** [comment]
> My apologies for overlooking at first glance. Yes, I do believe that renaming the variables to match those used by the system prompt would be a good idea.

Done😎

**Comment by tjbck** [comment]
LGTM, Thanks!

**Pull request merged**
